### ISSUE TITLE
Styling Broken In Larger App

### ISSUE THREAD

**Issue by krishnaglick** [projectstorm/react-diagrams#100]
I'm attempting to utilize this library in an app and while I can get the nodes to render, the styling doesn't seem to be working correctly. If I include just the scss found in the app's src folder it looks like:
![process-editor-error](https://user-images.githubusercontent.com/4967694/31563822-a08130d6-b02e-11e7-8f36-a432adf0b315.png)
If I instead include the css file from dist I get what looks correct, but it also doesn't bound correctly:
![process-editor-error-2](https://user-images.githubusercontent.com/4967694/31563838-b28e261c-b02e-11e7-8b2d-efac1bee7740.png)
In the second one I'm able to pull it left all the way onto my app's menu. This might be some weird interaction with my app's styling itself, but I'd like to confirm so before mucking with currently working css.
Additionally if the `storm-diagrams-canvas` canvas has `position: relative` on it, it flies off screen. Once again, possibly due to the css of my top and side menus.

**Comment by JokerNN** [comment]
Well, it's hard to tell without looking at your code.
However, [demo5][1] works fine for the similar scenario. There are a header and sidebar that shifts diagram, but it still works as expected. You can take a look

[1]: http://www.projectstorm.io/react-diagrams/?selectedKind=React%20Diagrams&selectedStory=Embedded%20diagram&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by krishnaglick** [comment]
Glancing through demo5 gave me the inspiration to mess with my z-index. Setting the sidebar to `z-index: 1000;` made it appear over the drag-and-drop stuff. Still having issues w/ the svg background and panning though.
P.S: Why did you mention this issue in a PS?

**Comment by krishnaglick** [comment]
Dropping it in raw, styling is still broken. Should webpack be doing some auto-compiling for the styling? Are there a couple of `scss` files I should be grabbing?

**Comment by JokerNN** [comment]
There are few possible reasons of your broken layout:
1. This library styles
2. Your app styles
3. Incorrect usage of library styles

I can't say which one of them without looking at your code. I believe it's 2 or 3, because demo works fine

**Comment by krishnaglick** [comment]
What library style should I be using?
If I utilize: https://github.com/projectstorm/react-diagrams/blob/master/src/sass.scss
It doesn't show up at all. Is that the correct sass file?

**Comment by jardg** [comment]
@krishnaglick Im using the same sass file and its working fine. Just be careful you aren't using it as entry file on the config.I had the same problem and was because I was loading the sass file on the webpack entry point instead of importing the sass file on the component where I was using the library. Also can mess up other css files that uses svg .
Hope this helps.

**Comment by krishnaglick** [comment]
Are you using a babel loader to import the scss into the JS file? Cause I've been converting it to css and serving it up.

**Comment by jardg** [comment]
Im using [sass loader](https://github.com/webpack-contrib/sass-loader) and importing it in like: import "../../styles.scss"; in my component

**Comment by krishnaglick** [comment]
Importing it like that didn't change anything. I messed w/ the styles and it's mostly working except for a few minor things. Calling it good enough. Thanks for the help!

**Comment by sht5** [comment]
if anyone is still stuck with this, same thing happenned to me, what i did was look at the demos - they import test.scss which itself references sass.css which is under src. i just copied both into my component folder and referenced test to sass correctly then walla!
