### ISSUE TITLE
Set anchor point

### ISSUE THREAD

**Issue by bknill** [projectstorm/react-diagrams#101]
Hi, 

Is it possible to define where on the node where the connection happens? 

Thanks

Ben

**Comment by JokerNN** [comment]
Hello!
You can take a look at demo3, specifically here code for [DiamondNodeWidget][1].
You can position `PortWidget` in  as you want.

1: https://github.com/projectstorm/react-diagrams/blob/master/demos/demo3/DiamondNodeWidget.tsx
