### ISSUE TITLE
Documentation Needed

### ISSUE THREAD

**Issue by ehmadzubair** [projectstorm/react-diagrams#103]
Hi,

I am currently using react-diagrams in a project of my own. I couldn't help but point out the humungous amount of time i had to spend on how the examples were curated to figure out how to use the library. 

Is there a roadmap/thread for adding documentation to the project? If not, what is a good point to start? I'm happy to make a contribute to the documentation, are there any volunteers here?

**Comment by AnwarChakhar** [comment]
Hi
Same here. More than happy to help documenting some part of the library.

**Comment by ehmadzubair** [comment]
Okay, two people... Any other volunteers?

**Comment by tylerjharden** [comment]
As I learn more about it and use it I wouldn't mind contributing.

**Comment by dylanvorster** [comment]
FWIW: A good place to start is:

a) at the demos
b) https://github.com/projectstorm/react-diagrams/network/dependents
c) on the gitter channel (super helpful people)

**Comment by dylanvorster** [comment]
FWIW: docs are currently in the works. The docs will live alongside the demos. Will close this issue when all the demos are explained well enough :) I also now render the code alongside the demo, and the demo code will contain more comments.

**Comment by jc78** [comment]
@ehmadzubair (or anybody else who has had success), would you mind offering a really simple rundown of how to incorporate this library into a current react project. I'm having a hard time converting the code in the examples into a basic react component class that renders a graph.

I just created #169 with a little bit more detail on my problem. But if you have example code of how to do this (different from this repo's demo code), that would be super helpful.

Thanks!

**Comment by dylanvorster** [comment]
there is now a git-book project for the application, and while the docs are not complete, it is now being actively worked on https://projectstorm.gitbooks.io/react-diagrams/
