### ISSUE TITLE
Notification on Node movement

### ISSUE THREAD

**Issue by csterritt** [projectstorm/react-diagrams#105]
Hi - thanks for doing this library, it's pretty amazing!

I'm kind of surprised that there is no event to let you know that a node has moved.

We're replacing a less-appropriate library using this one, but saving any changes (including moving nodes around) is a big part of our work.

Have I missed it somehow?

And OH YEAH, it'd be great to be able to save the locations of 'elbows' that I put in links.

Thanks again!

**Comment by JokerNN** [comment]
DISCLAIMER: I haven't tried it by myself but don't see any reason why following shouldn't work.

You can subscribe to `actionStartedFiring`/`actionStillFiring`, and it will fire MoveItemsAction where you can access moved items from `action.selectionModels`

Hope this helps

**Comment by csterritt** [comment]
Thanks for the reply!  We decided not to use SRD after all.
