### ISSUE TITLE
Update node position after render through model access

### ISSUE THREAD

**Issue by alex-enchi** [projectstorm/react-diagrams#107]
Hi, is there any proper way to update node position via code after diagram was rendered?

I tried to update position of node directly through model or via serialize/deserialize. Positions of points/links are not updated accordingly.

I've created a small demo8 for the issue [err-node-position-update branch](https://github.com/alex-enchi/react-diagrams/tree/err-node-position-update)

Some screenshots

## initial diagram rendering
![01-initial](https://user-images.githubusercontent.com/24417201/32802176-f2a6ae32-c987-11e7-946d-47a7251a6132.png)

## direct updated node position
![02-after-update-positiion](https://user-images.githubusercontent.com/24417201/32802180-f550b43e-c987-11e7-9e02-c0ac276acc18.png)

## Moved node with mouse
![03-moved-mouse-around](https://user-images.githubusercontent.com/24417201/32802189-fa5e4dc4-c987-11e7-853f-59ee33a4dfc6.png)

**Comment by dylanvorster** [comment]
you need to update the node position as well as the co-ordinates of one of the points on the link. Alternatively: after first render, the system makes expensive DOM calls to calculate where the visual co-ordinates of the node are, after that you can change the node position and then set ```linksThatHaveInitiallyRendered``` back to an empty object and repaint. This will cause the engine to re-calculate all the links again.

**Comment by dylanvorster** [comment]
another thing which could be happening, is that you are not linking to the node correctly, at the very least, moving the node with the mouse, would move the link as well if it was linked correctly.

**Comment by dylanvorster** [comment]
I just had a look at your example 8, ill try see whats going on if I get a minute :C

**Comment by alex-enchi** [comment]
Cool thanks!
I checked with `engine.linksThatHaveInitiallyRendered` it works better especially when snap to grid is off. With snap to grid link tends to run away when mouse is moved.
But it doesn't feel like a good way. 
Besides mouse movement works great and I thought there supposed to be a similar way of moving around node.

**Comment by dylanvorster** [comment]
600a386f32bc06137458b2bacfc7fc183d5e9fab
