### ISSUE TITLE
A more complex sample

### ISSUE THREAD

**Issue by kfrajtak** [projectstorm/react-diagrams#108]
Hi,
would it be possible to share the code of the diagrams that are displayed on the main page (i.e. https://github.com/projectstorm/react-diagrams/blob/master/images/example1.png and similar)? I'd like to evaluate your library for my project and the samples in demos directory are not complex enough.

Thank you,
Karel Frajtak

**Comment by dylanvorster** [comment]
https://github.com/projectstorm/react-diagrams/issues/56

**Comment by dylanvorster** [comment]
but yes, I will be adding more complex examples soon.

**Comment by kfrajtak** [comment]
Great, I am looking forward to it!
