### ISSUE TITLE
Adding new Nodes

### ISSUE THREAD

**Issue by whito** [projectstorm/react-diagrams#12]
Hi there,

I really like what you have started here - its super fast and responsive. 

Is it possible to add new Node's and Connections dynamically to the diagram at runtime? I tried running the demos but not quite sure how to access the diagram  after its already rendered. Would like to have a button or do a drag and drop from outside the diagram to add new members.. let me know..

Cheers

**Comment by mwozniczak** [comment]
Kind of what I'm gonna be doing with my project, actually.

In the examples, you can see that you add a node (for which main diagramEngine's DiagramModel has a factory) by creating a new node object, and then adding it to the model, e.g. (note: using my `SceneNodeModel`, which is basically a specialized NodeModel I've made for my project)

```js
    var engine = new SRD.DiagramEngine()
    var model = engine.getDiagramModel()
    var node = new SceneNodeModel('Scene one!')
    node.x = 100;
    node.y = 120;

    model.addNode(node)
```

All you'd have to do is wrap something similar into a function, and make that a callback to your "add new node" button, or what have you

**Comment by mwozniczak** [comment]
Also, regarding this:

> not quite sure how to access the diagram after its already rendered

the `model` var in my above example should serve you well :)

**Comment by dylanvorster** [comment]
Lol you beat me to it xD but essentially you just modify the DiagramModel or any of its descendants and then re-render the DiagramWidget (basically a react forceUpdate()). Something I still need to do, is use my event layer which powers the models, and cause the DiagramWidget to forceUpdate when we mutate the models.

**Comment by dylanvorster** [comment]
Regarding the 
> drag and drop from outside the diagram to add new members
the DiagramEngine has methods that allow you to retrieve the virtual x and y co-ordinates of your mouse position in relation to the canvas translation and zoom levels, in my own program, I actually implemented drag and drop using those methods, its super easy to do actually. I think ill make a 'demo4' that showcases this functionality tomorrow

**Comment by whito** [comment]
thanks for the great response... look forward to see demo4! I think this library has a ton of potential

**Comment by DrummerHead** [comment]
> and then re-render the DiagramWidget (basically a react forceUpdate())

I was actually dealing with this right now, I assumed the diagram would re-render when changing the model.

I'm feeling tempted now to make the result of doing `model.serializeDiagram` a member of component state (or Redux store) and then create a method that calls `model.addNode` (for example), serializes the diagram, saves that to state, and then the diagram gets rendered from `deSerializeDiagram` what's in state... but it also sounds like I'm fighting with the library doing that; I don't think it's intended for the user to be serializing and de-serializing all the time to keep track of state.

What do you think about this situation? Thanks!

**Comment by dylanvorster** [comment]
I think... this is hard because I designed this library to specifically be imperative. The method you mention is probably the method I would also personally use if I wanted time travel. Declarative systems are awesome for this kind of thing, but make other problems hard at the same time.

I don't think you would be fighting the library :) Good luck :)

**Comment by SnehaParanjape** [comment]
In the solution that mwozniczak suggested about wrapping something similar into a function, what would the function return?
var engine = new SRD.DiagramEngine()
    var model = engine.getDiagramModel()
    // wrap the below part in a function that you could call with a button
    var node = new SceneNodeModel('Scene one!')
    node.x = 100;
    node.y = 120;

    model.addNode(node)
