### ISSUE TITLE
Control number of links that can be connected to a port

### ISSUE THREAD

**Issue by mcnewbk** [projectstorm/react-diagrams#122]
Is there a way to control the number of links that can come from/to a port. For example, I would like to limit my ports to only be able to have one link attached at any time.

**Comment by dylanvorster** [comment]
not yet without some hacks unfortunately. I would suggest doing a recursive check on all the node ports for the entire diagram model and then just pop them off if a user ever tries to do it. Im also looking at allowing a preventDefault on the new events system in the open PR, which could prevent this.

**Comment by tomitrescak** [comment]
For those interested I solved it like this:

```ts
const model = new DiagramModel();
const maxLinks = 1;

model.addListener({
    linksUpdated: e => {
      if (e.isCreated) {
        e.link.addListener({
          targetPortChanged: f => {
            if (Object.keys(f.port.links).length > maxLinks) {
		model.removeLink(e.link);
            }
          }
        });
      }
    }
  });
```

**Comment by ianchanning** [comment]
There is a `canLinkToPort` property on the NodeModel that you could use

**Comment by sinanyaman95** [comment]
any updates on this feature? Should we still use the same work around to limit the number of links for a port?

**Comment by renato-bohler** [comment]
Here's how I implemented it [on my project (logossim)](https://github.com/renato-bohler/logossim/blob/bde09afec0c590c103f5a779d17a367002f1bc78/packages/%40logossim/core/Port/PortModel.js#L77-L88).

**Comment by sinanyaman95** [comment]
Hey @renato-bohler as your example, I extended the port class and added some functions to it just like your `setBits`. However when I deserialize the custom port, those functions are sometimes registered as `undefined`. 

Here is my example:

```
import { DefaultPortModel } from '@projectstorm/react-diagrams'
import { RightAngleLinkModel } from '../../Diagram/links/RightAngleLinkModel'

export class RightAnglePortModel extends DefaultPortModel {

  constructor(options = {}) {
    super({
      type: 'rightAngle',
      ...options
    })
    this.maximumLinks = null
    if (this.getOptions().in) this.setMaximumLinks(1)
  }

  setMaximumLinks(maxLinks) {
    this.maximumLinks = maxLinks
  }

  getMaximumLinks() {
    return this.maximumLinks
  }

  isNewLinkAllowed() {
    return this.getMaximumLinks() === null ? true :
      Object.keys(this.getLinks()).length < this.getMaximumLinks()
  }

  canLinkToPort(port) {
    return port.isNewLinkAllowed()
  }

  createLinkModel() {
    if (this.isNewLinkAllowed()) return new RightAngleLinkModel();
    return null
  }

  serialize() {
    return {
      ...super.serialize(),
      maximumLinks: this.maximumLinks
    };
  }

  deserialize(event, engine) {
    super.deserialize(event, engine);
    this.maximumLinks = event.data.maximumLinks;
  }
}
```

When I deserialize a model, `this.getMaximumLinks()` is undefined (only sometimes). Do you think I am missing something, otherwise I will create an issue for this manner. If you have any ideas, much appreciated ^^

**Comment by renato-bohler** [comment]
How is your port factory defined?

What if you change the `'rightAngle'` (on model and factory) to something else? I'm pretty sure that there's a default port/link registered with this `type` already, so this might be causing the problem as well.

**Comment by sinanyaman95** [comment]
Yep, I think that was the problem. Thanks for the help, much appreciated as always
