### ISSUE TITLE
Passing data/callbacks between nodes on link event

### ISSUE THREAD

**Issue by ByronBecker** [projectstorm/react-diagrams#126]
#125  Hello,

I have a question regarding what is the best way to send data between nodes once a link is connected. I've implemented the listeners, but am having a bit of trouble figuring out how and where to send the callbacks tot the nodes already on the diagram.

Inside my node widgets, I have little applications (representing the type of the node), and I would like to be able to pass a callback from the receiving node to the sending node that can be used to send data. It seems to me that the best way to do this would be to give all the nodes callbacks as props from a diagram class, and then pass down the callback with a specific to all nodes so that the targetted node picks it up.

The problem is, its a bit hard to figure out how to correctly pass the props through the diagramWidget. Inside my diagram widgets I have content on a lower level that renders based on the data. This is my current strategy.

I'm assigning a sender and receiver function to my NodeModel, then onEvent passing the receiver's callback to the sender, passing the callback down, and then upon receiving data passing the data received down to the receiving node. The problem is, the data doesn't receive, and the events I want only seem to be firing when I drag the diagram. Below are snippets from my CustomNodeModel and Application.ts files.

**ExpandableNodeModel.ts**

- this is a snippet from the node model I created that expands on double click, I'm trying to pass initialize personal and sender callback props in the model that can be passed down to generate content within the node

```export class ExpandableNodeModel extends SRD.NodeModel {
        name: string;
	color: string;
	type: string;
	ports: { [s: string]: SRD.DefaultPortModel }; //can change this to expandableportmodel
	receiverInput:any = null
	personalDataCallBack: (data: any) => any = (data) => {
		console.log('sending data ', data)
		this.receiverInput = data;
	}
	senderDataCallBack: Function = null;
        constructor(name: string = "Untitled", color: string = 'green', type: string = null) {
        super("expandable");
        this.name = name;
		this.color = color;
		this.type = type;
		}
	public connections: Connections = {
		senderDataCallBack: null,
		personalDataCallBack: this.personalDataCallBack  //bind didnt work
	}```


**Application.ts**

- this is a snippet from the application.ts file (like in your demos) It's here that I attach event listeners to the addition of links and nodes. the testDataConnection(sender, receiver) function is trying to assign the receivers person callback the sender's sender call back prop.

```public testDataConnection(sender, receiver) {
		console.log('starts at', sender);
		console.log('sender node is', this.activeModel.getNode(sender.id))
		console.log('ends at', receiver);
		sender.extras.senderDataCallBack = receiver.extras.personalDataCallBack;
		console.log(sender.extras.senderDataCallBack)
}
public newModel() {
		this.activeModel = new SRD.DiagramModel();
		this.diagramEngine.setDiagramModel(this.activeModel);
		//added event listener
		this.activeModel.addListener({
			linksUpdated:(link:any, isCreated:boolean) => {
				console.log(isCreated?'added link':'removed link', link)
				link.addListener({
				sourcePortChanged:(source, sink) => {
						// haven't been able to trigger this one
						console.log('source', source);
						console.log('sink', sink);
					},
					// this is where the event listener is listening for connections
					targetPortChanged:(link, sink) => {
						let sender: ExpandableNodeWidget;
						let receiver: ExpandableNodeWidget;
						if (sink.in) {
							this.testDataConnection(link.sourcePort.parentNode, sink.parentNode);
							/*
							sender = link.sourcePort.parentNode;
							receiver = sink.parentNode;
							*/
						}
						else {
							this.testDataConnection(sink.parentNode, link.targetPort.parentNode);
						}
					}
				});				
			  },			  
			  nodesUpdated: (entity: SRD.DefaultNodeModel, isAdded:boolean) => {
				console.log(isAdded?'added node':'removed node', entity)
				}			  
		});```

Any tips? I'm really stuck :/

By the way, @dylanvorster aside from the documentation, I'm really enjoying the library. It's pretty dynamic and its obvious you put a ton of thought into it

**Comment by dylanvorster** [comment]
hey man, I'll try and take a look at this later today :)

**Comment by ByronBecker** [comment]
I guess the better way of doing this would be to have some overarching data structure/MVC architecture above that keeps a representation of what the graph is, and then on event listener can propagate the information down to that specific node. 

The tough part is that on link changed, this event targets the (Custom in my case) Node Model and not the individual node widget, so my medicore skills are having a tough time passing that information around outside of using props or state (the node model is not a react component).

Also, since the node.extras {} isn't part of the node's state, it's hard to rerender up to the minute data info such as changing pixel values inside the node, or without building a custom component and then nesting that information inside the node, or I guess using .forceUpdate a ton().

Let me know if my question or what I'm trying to accomplish is unclear in any way

**Comment by dylanvorster** [comment]
do you have a project I can take a look at that I can use to illustrate via comments how to go about doing this (or can you maybe re-format the code samples you provide :) ?) Thanks for the kind words by the way!

**Comment by ByronBecker** [comment]
Sure, and I just made a private copy of my personal repo for you to look at. The instructions are on there. I'd also be down to talk over the gitter if that's a better place to chat.
