### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by gen4sp** [projectstorm/react-diagrams#13]
Hey guys,
Is there any built-in way to make an image as scalable background? 
I've tried to set background for SVG, but result is not looking so good )
<img width="1388" alt="screen shot 2017-03-16 at 13 31 10" src="https://cloud.githubusercontent.com/assets/4303628/23992136/e45ce13e-0a4c-11e7-8fbc-c6ef49b2913b.png">

**Comment by dylanvorster** [comment]
Im not sure I understand the problem... What I can say is, that you should wrap the system in a layer:

-> Your parent widget
-----> your background layer
-----> react-diagrams

and then when the diagram changes, just scale your background in whatever way you want.
So basically I'm not sure this is a problem relating to this library?

**Comment by gen4sp** [comment]
Ok,  I've didn't know about events. Will try to use it
