### ISSUE TITLE
Click on node and change Parents state

### ISSUE THREAD

**Issue by harishmahajan** [projectstorm/react-diagrams#133]
Hi, I want to change the Parent state when i click on any node.

If i click on "label" then i can change the state of parent.

See attached screenshot.
![eventclick](https://user-images.githubusercontent.com/6470026/34639258-ab0175f4-f302-11e7-8f14-874ab90883c6.png)

**Comment by eugeneoeihanalytics** [comment]
Hi @dylanvorster , may i know if there is a solution to this question? I am trying to achieve something similar as well. I am trying to get the click event on the selected node.

I looked into your source code of `DiagramWidget.tsx` and saw that in the `onMouseDown` event, there is a `getMouseElement` method which appears to get the selected node/element (do correct me if i am wrong). It seems to me that that is the way to go. but how can i get the click event within the diagram which can then lead me to the `getMouseElement` method?

i tried doing the following:

`<DiagramWidget onMouseDown={(event) => console.log('clicking', event)} className='storm-diagrams-canvas' diagramEngine={this.engine} allowCanvasTranslation={false} allowCanvasZoom={false}  />` but the click event is not registering.

any suggestions or directions?

@harishmahajan did you menage to achieve what you would like to?
