### ISSUE TITLE
save and re-render diagram?

### ISSUE THREAD

**Issue by harishmahajan** [projectstorm/react-diagrams#135]
Hi, all
i want to save the diagram. How can i do it.?
is there any method? please suggest me.
once i saved the diagram and if i want to modify or update it then how can i do it?

is there any example for it?

**Comment by dylanvorster** [comment]
Take a look at the serialize demo as well as the programmatic mutate graph demo

**Comment by harishmahajan** [comment]
@dylanvorster 

i checked it, 
so first i have to
- setup the diagram engine.
- setup the diagram model
- create a node
- add the models to the root graph
- load model into engine

and save have to save this data to db?
and if i want to re-render it then i have to retrieve those data from database? 
am i right?

**Comment by dylanvorster** [comment]
see serialize and deserialize methods (as mentioned in gitter as well) :)
