### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by gen4sp** [projectstorm/react-diagrams#14]
Also, I am looking for a way to implement events, such as nodeSelected, nodeAdded, nodeRemoved and custom nodeConfigChanged.
I've looked through the code, but didn't get what is the best way to do it.

**Comment by dylanvorster** [comment]
Hi there, so every single model in this library is built onto of an event layer. Whenever a model changes, it can fire events that you can register listeners for. I have not implemented listeners for everything, but the framework has a good foundation to implement it in various places. If there is an event that I'm not firing, you are welcome to implement and push a change request.

Example of me **firing** an event:
https://github.com/projectstorm/react-diagrams/blob/master/src/Common.ts#L55

Example of me **listening** for an event:
https://github.com/projectstorm/react-diagrams/blob/master/src/DiagramModel.ts#L188

Example of where **I should be, but am not** just yet:
https://github.com/projectstorm/react-diagrams/blob/master/src/Common.ts#L101

**Comment by gen4sp** [comment]
Oh, great! Thank you for a quick response. Will try to use it.
