### ISSUE TITLE
Difference between published module (npm registry) and docs/sources

### ISSUE THREAD

**Issue by maxleiko** [projectstorm/react-diagrams#141]
Hi there,

I'd like to try out your library, but it seems like your documentation, that states that we have to use `installDefaultFactories()` is not synced with the published module on the npm registry as when we install `storm-react-diagrams`, `DiagramEngine` does not have any `installDefaultFactories()` function available.

Am I missing something, or are you in the process of updating the docs/sources and did not yet released it on the npm registry?

**Comment by dylanvorster** [comment]
Hey man, we were currently in the process of releasing 4.0.0, but I decided to just release it today anyways :) Sorry for the confusion.
