### ISSUE TITLE
legend for diagram?

### ISSUE THREAD

**Issue by dixitk13** [projectstorm/react-diagrams#152]
I dunno if it's too much to ask but is it possible to have a legend so we can describe our own Custom Links/Nodes/ Images etc?

Some higher level element which abstracts the legend maybe?

**Comment by dylanvorster** [comment]
not entirely sure I understand what you mean. If you are referring to some sort of overlay then it would be best to implement it yourself as an absolute panel.

**Comment by dixitk13** [comment]
I meant something like this. Where the legend could be a component which could be used to explain the diagram colors. The legend could be a prop to the diagram itself. 

Excuse my bad paint drawing. 


![example3](https://user-images.githubusercontent.com/8632659/35761026-4d33c854-0839-11e8-8887-ee1ffb5a71a4.png)

**Comment by dylanvorster** [comment]
Yeah I thought that was what you meant, its a cool idea but I don't think the library should do this because its quite easy to implement yourself with an absolute positioned div.
