### ISSUE TITLE
Programatically adding a link after the model was created will not refresh the diagram correctly.

### ISSUE THREAD

**Issue by tomitrescak** [projectstorm/react-diagrams#153]
Steps to reproduce:

1. Crate a model
2. Display a model
3. Add a link to the model programatically
4. forceRefresh
5. The link will not be there (the issue I see is that condition in "NodeLayerWidget" is false `t.props.diagramEngine.nodesRendered`);

For some reason it is first rendering LinkLayerWidget and then NodeLayerWidget

**Comment by eugeneoeihanalytics** [comment]
seems like an issue similar to #223 and #234 . take a look at the solutions there!
