### ISSUE TITLE
code of more complex examples

### ISSUE THREAD

**Issue by smeijer** [projectstorm/react-diagrams#157]
There are two awesome images shown in the `README`, of two more complex examples regarding custom controls. But I cannot find them in the demos folder or storybook.

Is this code somewhere available? Or if not, can it be made available? 

I'm referring to the image below:

![image](https://user-images.githubusercontent.com/1196524/35996069-abc0ca08-0d15-11e8-9e83-38fc1879a469.png)

**Comment by smeijer** [comment]
Self-closing due to #56, still request for example similar to above screenshots stands.

**Comment by tuckwat** [comment]
Shouldn't the screenshots be removed considering it contains "nodes and widgets" (and functionality) which are missing from this open source project?

**Comment by dylanvorster** [comment]
can u explain what functionality is missing?

**Comment by dylanvorster** [comment]
The whole point of this library is that you can create your own nodes, which is what the screenshot shows.
