### ISSUE TITLE
Error link location when setting sourceMap as true in css-loader

### ISSUE THREAD

**Issue by d9767192** [projectstorm/react-diagrams#158]
I faced a strange problem... Please checkout my testing repo:
[Repo] (https://github.com/d9767192/react-diagrams). 
In this repo, I simplified all settings and compiled program by webpack-dev-server. 
In the webpack settings, I only used style-loader and babel loader as plugins.
In the setting of babelrc the preset of env and react were used.
About the program, I tried the simple case (two node, one link)

When I ran the program, I got this result:
![default](https://user-images.githubusercontent.com/14174895/36009257-5ea772be-0d86-11e8-9f77-78a37ba4bb8f.png)

Then, I tried to set sourceMap in css-loader as false, The result is perfect:
![2](https://user-images.githubusercontent.com/14174895/36009355-c368c572-0d86-11e8-9293-b8c313a38279.png)

Finally I found an issue in css-loader repo seems match my problem:
https://github.com/webpack-contrib/css-loader/issues/613

I'm not sure if it is the reason. Now I can do is to remove the sourceMap in my project. But it's wierd! Is there any other solution?

Thanks.

**Comment by dylanvorster** [comment]
library no longer uses css
