### ISSUE TITLE
How to add <defs> element to svg ?

### ISSUE THREAD

**Issue by ndussart** [projectstorm/react-diagrams#159]
I would like to apply a linear gradient to my `LinkWidgets` so I need to create a `<linearGradient>` node inside a definitions section in the svg.

I've seen that the `LinkLayerWidget` component is responsible for creating the svg and adding the list of `LinkWidget`.

Maybe I could create a special type of Link that would create that `<defs>` section ?
Or I can use the canvas ref in the diagram engine instance ?

I'm not sure what is the best approach here, what do you think ?

**Comment by dylanvorster** [comment]
This can now be solved by using the pathSegment hook in the DefaultLinkFactory. Please take a look at the custom links demo to see how its done :)
