### ISSUE TITLE
Can't DeSerialize node with default port

### ISSUE THREAD

**Issue by lucanisi** [projectstorm/react-diagrams#162]
I'm trying to autoDistribute my nodes (using dagre, as the samples).
When I use the method and the Diagram contains a Node with a DefaultPortModel inside, it gives this error:
`cannot find factory for port of type: [default]`

I tried with no ports and it seems to be fine, is there a way to solve this? Why the "default" port can't be found?
Thank you!

**Comment by d9767192** [comment]
Try this:
engine.installDefaultFactories();

It seems that the factory of port is not defined.
