### ISSUE TITLE
Event listeners on Link not working

### ISSUE THREAD

**Issue by arieldf** [projectstorm/react-diagrams#163]
Hi!

Thanks for this great library.

I would like to monitor when links change source and/or target port, and I am unable to make it work. I would expect it to be possible to do this:

	link1.addListener({
		sourcePortChanged: action("sourcePortChanged"),
		targetPortChanged: action("targetPortChanged"),
	});

but I am getting the following error Type '{ sourcePortChanged: any; targetPortChanged: any; }' has no properties in common with type 'BaseModelListener'. I have been trying using the branch links_refactor as well, but I am unable to make this work.

**Where can I listen to sourcePortChanged and targetPortChanged events?**

**Comment by arieldf** [comment]
I have also tested setting the type of link to any so that I can compile and run, but I am still not able to make it work.

**Comment by jessehanley** [comment]
@arieldf how'd you fix this?
