### ISSUE TITLE
How to use events

### ISSUE THREAD

**Issue by Baudin999** [projectstorm/react-diagrams#164]
Hi there,

Is there documentation on how to work with events? I want to add some events to my project but don't even know where to begin.

If you could me give me some information on the different events and how to attach them I would happily write the documentation and add a PR.

Cheers

**Comment by lucanisi** [comment]
I figured it out by myself reading the source code for the events and a sample for adding the listener.
You can add the listener by using the addListener method 
```
var model=new DiagramModel();
model.addListener({
     nodesUpdated: function(e){
       // Do something here
     },
     zoomUpdated: function(e){
      // Do something here
     },
});
```
And here is the event list 😃 
Events for DiagramModel: 
```
nodesUpdated
linksUpdated
offsetUpdated
zoomUpdated
gridUpdated
selectionChanged
entityRemoved
```

Events for LinkModel:
```
sourcePortChanged
targetPortChanged
selectionChanged
entityRemoved
```

Events for NodeModel and PointModel:
```
selectionChanged
entityRemoved
```

Hope it helped!

**Comment by ganesh-sankey** [comment]
@lucanisi when I tried to call another function in '// Do something here' part, It through error as 'error function is undefined'.  when I tried console.log for print e value, it was working. how can I call function in that //Do something part.

**Comment by lucanisi** [comment]
@ganesh-sankey can you paste the code throwing you the error here? what are you trying to accomplish?

**Comment by ganesh-sankey** [comment]
@lucanisi I have resolved the issue. There was some syntax issue from my side. 
I was actually calling function inside //do something. like nodeUpdated: function (e) {
  this.myfunction ();
},

Instead I put it as - nodeUpdated :{ this.myfunction ();},

It worked for me.
Thank you for putting above documentation. It was huge help to understand how to add listeners

**Comment by ganesh-sankey** [comment]
@lucanisi Is there way to add listener to dynamically created links between nodes. means when you create link between nodes in diagram widget using drag from one port to another?

**Comment by lucanisi** [comment]
@ganesh-sankey you can add the listener to a new link inside the linksUpdated event
```javascript
model.addListener({
   linksUpdated: function(event){
      event.link.addListener({
         // New created link events here
      });
   }
});
```

**Comment by ganesh-sankey** [comment]
@lucanisi I got stuck up when implementing further functionality using dynamically created links.
Now I need to add label to that created link on selectionChanged.
Here is the code:
```
  addListenerToModel (diagramModel: DiagramModel) {
    diagramModel.addListener({
      /**
       * linksUpdated
       * Perform action when link is updated
       */
      linksUpdated: e => {
        this.linksUpdated(e);
      }
    });
  }
```

```
  linksUpdated (event: Object) {
    event.link.addListener({
      /**
       * selectionChanged
       * Perform action when link is selected
       */
      selectionChanged: e => {
        event.link.addLabel('welcome');
      },
      /**
       * entityRemoved
       * Perform action when link is removed
       */
      entityRemoved: e => {
        //
      }
    });
  }
```

I got error as Uncaught TypeError: path.getTotalLength is not a function.
Did I write something wrong? Any idea?

**Comment by lucanisi** [comment]
@ganesh-sankey I think there's something wrong here
```javascript
selectionChanged: e => {
        event.link.addLabel('welcome');
      }
```

I can't check it by myself because I'm not at home now, but I'd go for a console.log(e) to understand where is the link located in the object, maybe something like...
```javascript
selectionChanged: e => {
        e.link.addLabel('welcome');
        //Just to be sure, put a console.log(e) here and navigate the object to know more
      }
```
In Google chrome use the logged item to trigger the addLabel manually, so you'll know what to do in the code :)
Hope it helps! I will be at home the next week to try it, this is just an hint :D let me know if it helped you

**Comment by ganesh-sankey** [comment]
@lucanisi  Great! By the time, I will try to look into it. Thanks for help.  
If you get time to look into it. then let me know(solution).
You can reproduce the same error by modifying existing demo/drag-and-drop example. I am guessing the issue, it is somewhat similar with what am I facing it another tasks.
Steps to reproduce error that I also faced in another task:
```
1. In example - demo/drag-and-drop/components/BodyWidget.tsx, onDrop event, write the code for creating nodes, links and labels programatically.(copied code from demo/links with label  example)
	var node = null;
							if (data.type === "in") {
								node = new DefaultNodeModel("Node " + (nodesCount + 1), "rgb(192,255,0)");
								node.addInPort("In");
							} else {
								node = new DefaultNodeModel("Node " + (nodesCount + 1), "rgb(0,192,255)");
								node.addOutPort("Out");
							}
							var points = this.props.app.getDiagramEngine().getRelativeMousePoint(event);
							node.x = points.x;
							node.y = points.y;
							this.props.app
								.getDiagramEngine()
								.getDiagramModel()
								.addNode(node);


								// create four nodes
	const node1 = new DefaultNodeModel("Node A", "rgb(0,192,255)");
	const port1 = node1.addOutPort("Out");
	node1.setPosition(100, 100);

	const node2 = new DefaultNodeModel("Node B", "rgb(255,255,0)");
	const port2 = node2.addInPort("In");
	node2.setPosition(400, 50);

	const node3 = new DefaultNodeModel("Node C (no label)", "rgb(192,255,255)");
	const port3 = node3.addInPort("In");
	node3.setPosition(450, 180);

	const node4 = new DefaultNodeModel("Node D", "rgb(192,0,255)");
	const port4 = node4.addInPort("In");
	node4.setPosition(300, 250);

	// link node A and B together and give it a label
	const link1 = port1.link(port2);
	(link1 as DefaultLinkModel).addLabel("Custom label 1");
	(link1 as DefaultLinkModel).addLabel("Custom label 2");

	// no label for A and C, just a link
	const link2 = port1.link(port3);

	// also a label for A and D
	const link3 = port1.link(port4);
	link3.setTargetPort(port4);
	(link3 as DefaultLinkModel).addLabel("Emoji label: 🎉");

	// add all to the main model
	this.props.app
	.getDiagramEngine()
	.getDiagramModel()
	.addAll(node1, node2, node3, node4, link1, link2, link3);

	this.forceUpdate();
```

2. This should create set of nodes, links and labels on drag and drop of any In/Out node from TrayWidget. but It only generates node and links properly. labels are not getting generated properly.

![capture](https://user-images.githubusercontent.com/31685694/38257160-5caac2e2-377d-11e8-8157-1629178aa74a.PNG)

**Comment by ganesh-sankey** [comment]
@lucanisi Thanks bruhh.
Resolved the issue. It was related path.getTotalLength() function. since I modified the LinkWidget component for arrow head functionality which returns <g> tag instead of <path> tag. so I need to unwrap the path from <g> tag in those functions and use it.

**Comment by dmigo** [comment]
It would be awesome to get notified when some links appear/being changed. What is the best event for that purpose?

**Comment by Crecket** [comment]
For some reason the eventListeners no longer work after the initial render. It shows multiple linksUpdated and nodesUpdated events the first time I add new nodes and links. But any other events are never triggered when I interact with the diagram.

Adding event listeners to the separate links or nodes individually also does not seem to work.

```js
model.addListener({
    nodesUpdated: e => console.log("nodesUpdated", e),
    linksUpdated: e => console.log("linksUpdated", e),
    
    // these are never triggered
    zoomUpdated: e => console.log("zoomUpdated", e),
    gridUpdated: e => console.log("gridUpdated", e),
    offsetUpdated: e => console.log("offsetUpdated", e),
    entityRemoved: e => console.log("entityRemoved", e),
    selectionChanged: e => console.log("selectionChanged", e)
});
```

**Comment by gj1118** [comment]
I agree , I cannot see any `selectionChanged` event getting fired. I just copied the above code verbatim .

**Comment by morganddoane** [comment]
Hey there,

Having a hard time getting events to work properly.

With the following code, calling model.addListener returns an error saying "model.addListener is not a function." Any ideas what I'm doing wrong?

`import React from 'react';
import createEngine, {
    DiagramModel,
    DefaultNodeModel
} from '@projectstorm/react-diagrams';
import { CanvasWidget } from '@projectstorm/react-canvas-core';


// Vertice looks like this
var sampleVertex = {
    id: "5f17336bedfe541cd889f783",
    inputs: ["5f17330eedfe541cd889f77e", "5f173313edfe541cd889f77f"],
    name: "YDiff",
    type: "difference",
    project: "5f17270b344213203859c9ee",
    location: {
        x: 100,
        y: 150,
    }
}


function Algorithm(props) {
    const { vertices } = props;

    var engine = createEngine();
    engine.maxNumberPointsPerLink = 0
    var model = new DiagramModel();

    let nodes = {}
    let resultPorts = {}

    vertices.forEach((v, i) => {
        const n = new DefaultNodeModel({ name: v.name, color: 'rgb(192,255,0)' });
        n.setPosition(v.location.x, v.location.y);
        nodes[v.id] = n;
    });

    Object.keys(nodes).forEach((id, i) => {
        resultPorts[id] = nodes[id].addOutPort('Result');
    });

    Object.keys(nodes).forEach((id, i) => {
        const vertex = vertices.find(v => v.id === id);
        vertex.inputs.forEach((input, i) => {
            let inputPort = nodes[id].addInPort(`Input[${i}]`);
            let link = resultPorts[input].link(inputPort);
            model.addLink(link);
        });
    })

    Object.values(nodes).forEach(node => {
        model.addNode(node)
    });

    model.addListener({
        nodesUpdated: e => console.log("nodesUpdated", e),
    });

    engine.setModel(model);

    return <CanvasWidget className='canvas' engine={engine} />;
};

export default Algorithm;`

**Comment by morganddoane** [comment]
Hey there,

Having trouble getting events working. With the following code, I get the TypeError "model.addListener" is not a function. Any ideas what I'm doing wrong?

```javascript
import React from 'react';
import createEngine, {
    DiagramModel,
    DefaultNodeModel
} from '@projectstorm/react-diagrams';
import { CanvasWidget } from '@projectstorm/react-canvas-core';

// Vertice looks like this
var sampleVertex = {
    id: "5f17336bedfe541cd889f783",
    inputs: ["5f17330eedfe541cd889f77e", "5f173313edfe541cd889f77f"],
    name: "YDiff",
    type: "difference",
    project: "5f17270b344213203859c9ee",
    location: {
        x: 100,
        y: 150,
    }
}


function Algorithm(props) {
    const { vertices } = props;

    var engine = createEngine();
    engine.maxNumberPointsPerLink = 0
    var model = new DiagramModel();

    let nodes = {}
    let resultPorts = {}

    vertices.forEach((v, i) => {
        const n = new DefaultNodeModel({ name: v.name, color: 'rgb(192,255,0)' });
        n.setPosition(v.location.x, v.location.y);
        nodes[v.id] = n;
    });

    Object.keys(nodes).forEach((id, i) => {
        resultPorts[id] = nodes[id].addOutPort('Result');
    });

    Object.keys(nodes).forEach((id, i) => {
        const vertex = vertices.find(v => v.id === id);
        vertex.inputs.forEach((input, i) => {
            let inputPort = nodes[id].addInPort(`Input[${i}]`);
            let link = resultPorts[input].link(inputPort);
            model.addLink(link);
        });
    })

    Object.values(nodes).forEach(node => {
        model.addNode(node)
    });

    model.addListener({
        nodesUpdated: e => console.log("nodesUpdated", e),
    });

    engine.setModel(model);

    return <CanvasWidget className='canvas' engine={engine} />;
};

export default Algorithm;
```

**Comment by morganddoane** [comment]
Hey there,

I'm having issues getting events working. When I call addListener on the model, I get a TypeError saying "model.addListener is not a function." Any idea what I'm doing wrong?

```javascript
import React from 'react';
import createEngine, {
    DiagramModel,
    DefaultNodeModel
} from '@projectstorm/react-diagrams';
import { CanvasWidget } from '@projectstorm/react-canvas-core';


function Nodes(props) {
    const { vertices } = props;

    var engine = createEngine();
    engine.maxNumberPointsPerLink = 0
    var model = new DiagramModel();

    const node1 = new DefaultNodeModel({ name: "Node1", color: 'rgb(192,255,0)' });
    node1.setPosition(50, 50);
    const node1Port = node1.addOutPort('Out');

    const node2 = new DefaultNodeModel({ name: "Node2", color: 'rgb(192,255,0)' });
    node2.setPosition(150, 150);
    const node2Port = node2.addInPort('In');

    const link = node1Port.link(node2Port);

    model.addAll(node1, node2, link)

    model.addListener({
        nodesUpdated: e => console.log("nodesUpdated", e),
    });

    engine.setModel(model);

    return <CanvasWidget className='canvas' engine={engine} />;
};

export default Nodes;
```

**Comment by alexandernst** [comment]
If you got here from Google, `addListener` was renamed to `registerListener`

**Comment by jduncanRadBlue** [comment]
Does anyone know how to label the link with data that sits inside the node data (node data was attached upon creation of node)?  When the node is created, I attach a JSON object to the node for hopes of being able to access later for purposes of posting an API call.  When the node event for onDrop is called, I can see the data being logged in the event.dataTrasfer.getData() call, but on the linksUpdated event, I can't find said data?

I can't seem to dig through linksUpdated event to find the node data?

```
diagramEngine.getModel().registerListener({
              linksUpdated: (event) => {console.log(event)}
            });
```
Full BodyWidget Code:

```
import * as React from 'react';
import PropTypes from 'prop-types';
import * as _ from 'lodash';
import '../styles/App.css';
import createEngine, {
  DiagramModel,
  DefaultNodeModel,
  DefaultLinkModel,
} from '@projectstorm/react-diagrams';
import { CanvasWidget } from '@projectstorm/react-canvas-core';
import styled from '@emotion/styled';
import TrayWidget from './TrayWidget';


export default function BodyWidget() {
  const diagramEngine = createEngine();
  const activeModel = new DiagramModel();
  diagramEngine.setModel(activeModel);

  const [engine, setEngine] = React.useState(diagramEngine);

  const handleUpdateEngine = (engine) => {
    setEngine(engine);
  };

  const style = {
    Body: {
      flexGrow: 1,
      display: 'flex',
      flexDirection: 'column',
      minHeight: '100%',
    },
    Header: {
      display: 'flex',
      background: 'rgb(30, 30, 30)',
      flexGrow: 0,
      flexShrink: 0,
      color: 'white',
      fontFamily: 'Helvetica, Arial, sans-serif',
      padding: '10px',
      alignItems: 'center',
    },
    Content: {
      display: 'flex',
      flexGrow: 1,
    },
    Layer: {
      position: 'relative',
      flexGrow: 1,
      height: '100vh',
      width: '100%',
      background: 'rgb(30, 30, 30)',
    },
  };

  return (
    <div style={style.Body}>
      <div style={style.Header}>
        <div className="title">DnD demo</div>
      </div>
      <div style={style.Content}>
        <TrayWidget applications={applicationDefinition} />
        <div
          style={style.Layer}
          onDrop={(event) => {
            const data = JSON.parse(
              event.dataTransfer.getData('storm-diagram-node')
            );

            const nodesCount = _.keys(diagramEngine.getModel().getNodes())
              .length;
            let node = null;
            console.log(data);
            if (data.nodeType === 'in') {
              node = new DefaultNodeModel(
                data.name,
                'rgb(192,255,0)'
              );
              node.addInPort('In');
            } else {
              node = new DefaultNodeModel(
                data.name,
                'rgb(0,192,255)'
              );
              node.addOutPort('Out');
            }
            const point = diagramEngine.getRelativeMousePoint(event);
            node.setPosition(point);

            diagramEngine.getModel().addNode(node);
            diagramEngine.getModel().registerListener({
              linksUpdated: (event2) => {console.log(event2)}
            });
            handleUpdateEngine(diagramEngine);
            diagramEngine.repaintCanvas();
          }}
          onDragOver={(event) => {
            console.log(event)
            event.preventDefault();
          }}
        >
          <CanvasWidget className="canvas" engine={engine} />
        </div>
      </div>
    </div>
  );
}
```

**Comment by berabulut** [comment]
@jduncanRadBlue Have you find a way? I am trying to find connected nodes using same code as you.

**Comment by jduncanRadBlue** [comment]
@berabulut I haven't found a way.  I opened a new issue:
#740 

No comments yet.  :(

**Comment by berabulut** [comment]
@jduncanRadBlue if you have node id this works.
#340

**Comment by jduncanRadBlue** [comment]
@berabulut  do you happen to have example code snipped of how to accomplish that?  I've noticed on the event linksUpdated, nothing is fired for when a link is actually successfully connected to a port.  It fires when a link is started its drag, but no connection event.

**Comment by berabulut** [comment]
@jduncanRadBlue I don't have a code that fires an event after a connection.  ATM I can only access the data after board force updates itself.

**Comment by jduncanRadBlue** [comment]
@berabulut That would be very helpful actually!

**Comment by DrNguyen2525** [comment]
Hi. I'm wondering is there any way to know when a new point is created or removed on a link. I have tried to track the `DiagramModel` by registering `linksUpdated` and also `eventDidFire` listeners, but none of them seems to work.

**Comment by rzfzr** [comment]
'''js
		this.props.app.getDiagramEngine().getModel().registerListener({
			eventDidFire: () => { console.log('event did fire') }
		});
'''
This kinda of works, but it does not fire when a link is made...

**Comment by amith2368** [comment]
If you are looking for event listener when a connection is made, here you go
`model.registerListener({
        linksUpdated: (event) => {
           event.link.registerListener({
               targetPortChanged: (event) => {
                   console.log('Link Changed');
               }
           })
        }
    });`

**Comment by mjg123** [comment]
It's 2025 and this thread is still the best/only documentation for this feature?
