### ISSUE TITLE
Link is deleted while clicking on the right key

### ISSUE THREAD

**Issue by caffeinecodes** [projectstorm/react-diagrams#166]

**Comment by afzalvpm** [comment]
[](url)

**Comment by mcmicahelchan** [comment]
+1. @caffeinecodes Hi mate, have u solved the problem yet?

**Comment by alex-enchi** [comment]
[source code](https://github.com/projectstorm/react-diagrams/blob/master/src/defaults/widgets/DefaultLinkWidget.tsx) It is default link widget behaviour.

There are couple of options: 

1. Create your own link widget see [demo of a custom link widget](http://projectstorm.cloud/react-diagrams/?path=/story/custom-models--custom-animated-links)
2. Wait till @dylanvorster will wrap with refactoring and upgrading architecture #373 and decide from there. Changes are awesome there.

**Comment by dylanvorster** [comment]
closing due to investigation https://hackmd.io/@renato-bohler/react-diagrams-issues-analysis
