### ISSUE TITLE
Attaching a discretionary flag/field to model listeners/model editing events

### ISSUE THREAD

**Issue by ByronBecker** [projectstorm/react-diagrams#168]
When a node is deleted, the best way to trigger events is by using the model listeners, which update the rest of the user's program for each event.

However, if one is trying to delete a node that has multiple connections, it is likely that the user would want to delete all associated links with that node. Also, the best way to do this would be to attach a discretionary flag to let the rest of the application logic to update once the last link of the deleted node has taken place.

An example is if I want to "typecheck" my graph before and after each event, where the typechecking is looking at the number of inputs and outputs from each node, relative to what the node is expecting. 

After I delete a node, I want to delete all links associated with that node before typechecking again.
Therefore, one may want to have a discretionary flag so that based on the type of link/node deletion, a program can separate when to fire a corresponding event (outside of the automatic gui update) vs. when to wait.

Right now, an event for nodesUpdated has 
   `e.node, and e.isCreated. `

   I would want to add some boolean field like e.flag or e.custom to the listener, which is passed a value from events like removeLink, removeNode, addLink, and addNode, essentially requiring that removeLink would look like this

   `removeLink (link: LinkModel | string, flag: boolean): void`

And the flag would be passed to the listener

```
removeLink(link: LinkModel | string, flag:boolean) {
		link = this.getLink(link);
		delete this.links[link.getID()];
		this.iterateListeners((listener, event) => {
			listener.linksUpdated && listener.linksUpdated({ ...event, link: link as LinkModel, isCreated: false, flag: flag });
		});
	}
```

**Comment by dylanvorster** [comment]
I guess one way to do this is to register your own listener, override the removeLink method and then fire your own listener with this flag as you mention.

**Comment by dylanvorster** [comment]
Since I'm also busy rewriting the event system, bundled with the possible workaround listed above, im going to close this for now :)
