### ISSUE TITLE
On Move Node

### ISSUE THREAD

**Issue by ilrein** [projectstorm/react-diagrams#170]
How can one access an event based on a Node being repositioned?

**Comment by jschroeter** [comment]
Got the same question, didn't find a solution yet. Maybe this could have some relation to #189?

**Comment by wamujlb** [comment]
I have used `mouseUp` event on the `nodeWidget` component.

**Comment by dylanvorster** [comment]
there is now a listener for this https://github.com/projectstorm/react-diagrams/blob/23b174736c1858fa2ee5899505454bf1a408e1a7/packages/react-canvas-core/src/core-models/BasePositionModel.ts#L6
