### ISSUE TITLE
dangling lines despite allowLooseLinks 

### ISSUE THREAD

**Issue by smeijer** [projectstorm/react-diagrams#171]
First of all; the new functionality `allowLooseLinks` introduced by #147 is really, really awesome!

I do however experience a bug, which is also present in the [flow demo](http://www.projectstorm.io/react-diagrams/?selectedKind=Simple%20Usage&selectedStory=Simple%20flow%20example&full=1&addons=0&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel).

The link is still being created, when "dropping" the link "outside" of a port, but within the node. Moving the node shows that the link is dangling.

![2018-02-27_15h19_11](https://user-images.githubusercontent.com/1196524/36733749-cc1ec712-1bd1-11e8-8116-c0e02e15b4df.gif)

Browser: Chrome 63 on Windows 10.

**Comment by BrunoQuaresma** [comment]
@dylanvorster I'm not able to use this prop on 'import { CanvasWidget } from '@projectstorm/react-canvas-core''
