### ISSUE TITLE
straighten vertical links when curves are not required

### ISSUE THREAD

**Issue by smeijer** [projectstorm/react-diagrams#172]
I see that there is only a check for [horizontal links](https://github.com/projectstorm/react-diagrams/blob/master/src/defaults/widgets/DefaultLinkWidget.tsx#L311). Vertical links are still being curved, when not required. 

![image](https://user-images.githubusercontent.com/1196524/36752226-b7eb08ce-1c02-11e8-9108-4d6e3578ed0d.png)

*made the nodes transparent to make the issue clear*

The standard (default) nodes hide this issue, because of the position of the ports. In my custom nodes, the ports are all on the edge of the nodes. Resulting in the curves being on the outside of the node, instead of being hidden under it.

**Solution**: There should be a check in `DefaultLinkWidget` to see if the link is flowing horizontal or vertical. And adjust the `margin check` accordingly, by validating `y` instead of `x` positions.

https://github.com/projectstorm/react-diagrams/blob/446cc8cdffc506adb9a7a2b9466dfe6b6bcd42e3/src/defaults/widgets/DefaultLinkWidget.tsx#L308-L313

*edit, I guess `generateCurvePath` should then also be optimized to create "vertical curves" instead of horizontal. Depending on the direction of the link of course.

https://github.com/projectstorm/react-diagrams/blob/446cc8cdffc506adb9a7a2b9466dfe6b6bcd42e3/src/Toolkit.ts#L45-L49

**Comment by PikkaPikkachu** [comment]
How can I define custom paths for curved links ? Any suggestions to achieve that?
