### ISSUE TITLE
Trying to move a locked node, moves the link instead.

### ISSUE THREAD

**Issue by smeijer** [projectstorm/react-diagrams#176]
When locking a single node, a drag action on the node moves the link.

When a node is locked, the drag event should be ignored. The link should be locked in such a way, that moving the locked node doesn't do a thing. But the link is still moved when moving an unlocked node on the other end.

A picture is worth a thousand words:

Node 1 is locked, node 2 is not.

![2018-03-01_11h19_43](https://user-images.githubusercontent.com/1196524/36839725-19266976-1d43-11e8-870e-6beaf4706b81.gif)

```js
const node1 = new DefaultNode();
node1.locked = true;

const node2 = new DefaultNode();
node2.locked = false;

const link = node1.getPort('out').link(node2.getPort('in')),
```

**Comment by sjy** [comment]
I have come into the save problem,  I have to manually lock all the links and ports.

**Comment by dylanvorster** [comment]
This should be fixed now, as this logic is now governed by the node setPosition logic
