### ISSUE TITLE
Testing? (and Docs)

### ISSUE THREAD

**Issue by rivyx** [projectstorm/react-diagrams#177]
Hi. I was just wondering, what kind of testing is currently implemented? I am really enjoying the library, great job. If someone could point me in the right direction I wouldn't mind contributing to documentation.

**Comment by dylanvorster** [comment]
Hi there, you will notice there is a section in the docs called Testing.md it should explain everything :)

In a nutshell we have very basic end-to-end tests that we are looking to expand on, and we use snapshot testing where we render each storybook demo in an isolated way
