### ISSUE TITLE
Question: callback for addNode?

### ISSUE THREAD

**Issue by hamsterbacke23** [projectstorm/react-diagrams#180]
Hello, thank you for your amazing work with this lib!
While trying out a few things I encountered a problem and I'm not sure if I'm doing something wrong:
- when adding a new link between nodes I just added, it seems to mess up the positioning of the links: the target port position seems to be always somewhere at x:0 y:0, as if it doesn't have the correct position of the target port yet
- when I add the new link in the next eventloop, it seems to work 

My question is, is there a need for a callback after adding the new node or am I using it wrong?

```
      model.addNode(newItem);

      //Create new link
      let newLink = new DefaultLinkModel();
      newLink.setSourcePort(this.props.node.getPort('right'));
      let port = newItem.getPort('left');
      newLink.setTargetPort(port);

      // we need to wait until the element has been added ?
      window.setTimeout(() => {
        model.addLink(newLink);
        this.props.engine.repaintCanvas();
      }, 1);
```

**Comment by jonathanpipe** [comment]
I'm having a similar problem. In my case I'm rendering `index.tsx` directly from the demo example `demo-drag-and-drop` which works in the storybook, but for some reason my edge is in the top right hand corner. I also find if I use a timeout to add the edge, it will be placed properly.

**Comment by dylanvorster** [comment]
the root model now has a `nodesUpdated` method and with the new architecture you can implement more custom logic and event listeners yourself :)
