### ISSUE TITLE
Cannot Resolve Symbol "DiagramWidget"

### ISSUE THREAD

**Issue by GarrettFleischer** [projectstorm/react-diagrams#187]
I'm having roughly the same issue as #169 but I'm getting the error that DiagramWidget cannot be resolved. I don't see any other way to import it.

Importing the styles.css just renders a blank page, and the container I'm wrapping it in is set to have a height of 100vh.

![image](https://user-images.githubusercontent.com/18196120/37191553-4182bbea-2315-11e8-846c-85db6a368590.png)

**Comment by dylanvorster** [comment]
closing this as 5.1.0 should fix this

**Comment by Nahdus** [comment]
I am experiencing the same issue. except for getting the error that DiagramWidget part.
