### ISSUE TITLE
Links disappear when re-rendering using existing model

### ISSUE THREAD

**Issue by wader** [projectstorm/react-diagrams#188]
Hello! Im not sure if doing something wrong or if this is bug. What seems to happen is that `DiagramEngine` does no repaint if the canvas element gets update.

Here is a storybook demo of my problem. When the button is clicked the links disappear, if you move the canvas or move a node the links appear again.

**Update** Actually now I noticed that it works if i do engine `repaintCanvas` in `componentDidUpdate`.

```Typescript
import { DiagramEngine, DiagramModel, DefaultNodeModel, LinkModel, DiagramWidget } from "../../src/main";
import * as React from "react";
import { DefaultLinkModel } from "../../src/defaults/models/DefaultLinkModel";

export class Test2 extends React.Component<{diagramModel: DiagramModel},{}> {
	render() {
		var engine = new DiagramEngine();
		engine.installDefaultFactories();
		engine.setDiagramModel(this.props.diagramModel);		
		return <DiagramWidget className="srd-demo-canvas" diagramEngine={engine} />;
	}
};

export class Test extends React.Component<{},{diagramModel: DiagramModel}> {
	constructor(props) {
		super(props);

		var model = new DiagramModel();
		var node1 = new DefaultNodeModel("Node A", "rgb(0,192,255)");
		let port1 = node1.addOutPort("Out");
		node1.setPosition(100, 100);
		var node2 = new DefaultNodeModel("Node 2", "rgb(192,255,0)");
		let port2 = node2.addInPort("In");
		node2.setPosition(400, 100);
		let link1 = port1.link(port2);
		(link1 as DefaultLinkModel).addLabel("Hello World!");

		model.addAll(node1, node2, link1);

		this.state = {diagramModel: model};
	}

	render() {
		return <div>
			<button onClick={() => this.setState({})}>Click me</button>
			<Test2 diagramModel={this.state.diagramModel}/>
		</div>;
	}
};

export default function test() {
	return <Test/>;
}
```

If I change the `ref` update callback in `DiagramWidget` to this it seems to work:
```Typescript
if (!this.props.diagramEngine.canvas && ref) {
	this.props.diagramEngine.setCanvas(ref);
	this.forceUpdate();
}
```

I've tried various other things like not recreating the `DiagramEngine` instance but don't know if that should be needed or not.

Thanks again for a very useful project!

**Comment by dylanvorster** [comment]
Hi There:

* Dont store the diagram engine or set it up in your render method.
* Store the diagram engine in another place such as your business logic or application state layer.

Im also in the process of resesigning the event system which is responsible for the updates, but for now after you move your code around, you can call forceUpdate() or repaintCanvas() on the engine.

Hope you were able to come right :)

**Comment by wader** [comment]
Yes i think so, thanks for the help!

**Comment by gj1118** [comment]
HI Wader, I am also facing this issue. Were you able to resolve your problem ?  If you can, can you please share your code as well ?  

Thanks

**Comment by wader** [comment]
@gj1118 Hey, hmmm i'm trying to remember. Ill let you know if i come up with something
