### ISSUE TITLE
Better event system

### ISSUE THREAD

**Issue by maxleiko** [projectstorm/react-diagrams#189]
WIP [maxleiko/react-diagrams](https://github.com/maxleiko/react-diagrams)

**Comment by dylanvorster** [comment]
looks good, not sure about inverting the isCreated logic though since its an API change. FWIW, im about to start a rewrite of the event bus in the next hour or so.

**Comment by dylanvorster** [comment]
im going to implement a way model events to trigger repaints in an efficient manner (almost like how mobs uses actions to defer the events. Also going to add a way to cancel an event before it fires)

**Comment by maxleiko** [comment]
To be honest, I just wanted to get notified when links were connected, because as of now, we are just getting events when the link is first created, but not when it is actually connected to a port.  
And in the process of refactoring, I found myself changing a bit the API, but that is subject to discussions of course.  

But if you actually are going to refactor the event system then I might push this update to later and wait for your modifications.

**Comment by maxleiko** [comment]
Closing this as no longer necessary.  

In order to get notified when a link is connected, one can use the `targetPortChanged` event triggered on link listeners.
