### ISSUE TITLE
Error when importing in MacOS

### ISSUE THREAD

**Issue by m4rcelofs** [projectstorm/react-diagrams#19]
Hey there! 

I'm trying to spike the lib, currently on a create-react-app default install on MacOS. When I import it on a JSX as `import * as SRD from "storm-react-diagrams";` it throws the following error:

> Failed to compile.
> 
> Error in ./~/storm-react-diagrams/dist/main.js
> Module not found: [CaseSensitivePathsPlugin] `/Users/mzr/projetos/react-diagrams-example/node_modules/React/react.js` does not match the corresponding path on disk `react`.
> 
>  @ ./~/storm-react-diagrams/dist/main.js 1:82-98

Apparently this means something is requiring "React" while the folder is actually "react"; since the only placed that seemed to do that was `webpack.config.js`, I changed it to the following on my local (linked) file and rebuilt:

```
externals: {
  ...
-  "react": 'React',
+  "react": 'react',
  ...
}
```

It seemed to work (at least it compiled), but is that a proper fix?

(btw, the lib seems great. From the demos, it looks much easier to use than any other available ones)

**Comment by dylanvorster** [comment]
Hey man, you were literally like 15 mins late xD I pushed i 2.3.6 that fixes this literally 15 minutes ago because another guy was having a similar issue. Try the latest build and this problem should disappear :)

**Comment by m4rcelofs** [comment]
Hahaha, awesome, many thanks!
