### ISSUE TITLE
Adding Labels Programmatically

### ISSUE THREAD

**Issue by ilrein** [projectstorm/react-diagrams#192]
What if a user draws a link with the GUI? How can I get reference to the underlying LinkModel in order to  ```addLabel``` ?

**Comment by dylanvorster** [comment]
you can add a listener to any of the models (links/nodes/points/labels) and can then work with the models that are added/created. There are also numerous ways to extend the system and add/fire your own listeners by using inheritance with this library.

https://github.com/projectstorm/react-diagrams/blob/64ec2dd0a4ecd76a5f3ce7b683bca03ac2171bc0/src/models/DiagramModel.ts#L14
