### ISSUE TITLE
No factories directory in v5.0.0

### ISSUE THREAD

**Issue by jo-fu** [projectstorm/react-diagrams#193]
It seems like the current npm version 5.0.0 doesn't quite support the demo setup yet. Is the production build currently different than the demo setup?

For example:

`SimpleFactory.ts` in [**demo-custom-node1**](https://github.com/projectstorm/react-diagrams/blob/master/demos/demo-custom-node1/SimplePortFactory.ts) imports `AbstractPortFactory` which is not exported in v5.0.0's main.ts

```
import {AbstractPortFactory} from 'storm-react-diagrams';

console.log(AbstractPortFactory);
// -> undefined
```

Will there be a 5.0.x soon that contains the new factories directory?

**Comment by dylanvorster** [comment]
There was a PR that fixed this about a week ago, it will be fixed in 5.1.0
