### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bioslikk** [projectstorm/react-diagrams#194]
Hello and thank you very much for creating this this appealing diagramming library.

I'm currently trying to use this tool for my master's dissertation but I can't make anything just work and run a  demo on a react project created by me. Is there any documentation or examples  that aren't just snippets of code ?

On another note is it possible to extract the created diagram from the user in any format so that I can apply logic to it and do stuff like sending request based on some connections and things like that ?

Thanks in advance :+1:

**Comment by dylanvorster** [comment]
There is no official documentation as we are also currently working on it, but there is a very large set of isolated demos that illustrate the different concepts in interesting ways. If you want to extract the diagram, you can either use the DiagramModel directly, or you can serialise any part of the DiagramModel by going serialize() and the JSON.stringify-ing it.

Please also take a look at: https://github.com/projectstorm/react-diagrams/blob/master/docs/Architecture%20Questions.md

as well as http://www.projectstorm.io/react-diagrams/?selectedKind=Advanced%20Techniques&selectedStory=Serializing%20and%20de-serializing&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel
