### ISSUE TITLE
Error running demo: node_modules/storm-react-diagrams/dist/@types/src/actions/MoveItemsAction.d.ts(2,32): error TS2307: Cannot find module '../models/SelectionModel'

### ISSUE THREAD

**Issue by PippoApps** [projectstorm/react-diagrams#197]
I cannot run your demo code, I get his error.
node_modules/storm-react-diagrams/dist/@types/src/actions/MoveItemsAction.d.ts(2,32): error TS2307: Cannot find module '../models/SelectionModel'

Here is the package file:

{
  "name": "typescript-test",
  "version": "1.0.0",
  "description": "x",
  "main": "app.js",
  "scripts": {
    "test": "we are live!",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" "
  },
  "author": "F",
  "license": "ISC",
  "devDependencies": {
    "concurrently": "^3.5.1",
    "lite-server": "^2.3.0",
    "typescript": "^2.7.2"
  },
  "dependencies": {
    "@types/react": "^16.0.40",
    "storm-react-diagrams": "^5.1.0"
  }
}

**Comment by dylanvorster** [comment]
clone the repo and run `yarn run storybook`
