### ISSUE TITLE
Custom Node- DiamondNodeFactory is not a constructor

### ISSUE THREAD

**Issue by bknill** [projectstorm/react-diagrams#204]
This is probably a React question but I'm struggling to get help that way. 

I can run the code fine in my older React-scripts project using the defaultNodes. I'm not trying to get it to run with some new custom nodes and I can't for the life of me import the example typescript. 
i.e. 

` import {DiamondNodeFactory} from './DiamondNodeFactory.tsx'`

`    this.diagramEngine.registerNodeFactory(new DiamondNodeFactory())`

Results in

>  TypeError: __WEBPACK_IMPORTED_MODULE_3__DiamondNodeFactory_tsx__.DiamondNodeFactory is not a constructor

I've not made any changes to DiamondNodeFactory.tsx

 Is this a typescript into React problem!?  It doesn't have any problems running the typescript in node_modules.. any ideas why it's having such an issue with typescript I've imported into src? 

Thanks

**Comment by bknill** [comment]
react-scripts-ts-loader helped with this

**Comment by micahelriceio** [comment]
@bknill Could you elaborate on how you solved this? I'm facing the same issue.
