### ISSUE TITLE
node timeline

### ISSUE THREAD

**Issue by bknill** [projectstorm/react-diagrams#205]
I want to create a port timeline, i.e. you can drag a link to a point on a timeline. Am I best to do this with lots of port, i.e. one every second, or move the port based on mouse hovering along the timeline?

**Comment by dylanvorster** [comment]
Im not sure which will be the best. The library should be able to handle both cases quite well, but I'm not entirely sure if this library is the best for this. I would recommend using D3 for this since the problem is not entirely aimed at process flow or system design.
