### ISSUE TITLE
There is no way to temporarily suppress the delete behaviour

### ISSUE THREAD

**Issue by Azim-Palmer** [projectstorm/react-diagrams#211]
**Steps to reproduce**

1. Visit [The simple demo](http://www.projectstorm.io/react-diagrams/?selectedKind=Simple%20Usage&selectedStory=Simple%20example&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel)
2. Select a node
3. Click on anything other than the diagram inside the center panel (so you're still within the storybook iframe that holds the diagram)
4. Press backspace

**Expected** 
As the diagram doesn't have focus it shouldn't respond to the backspace key event. Nothing should happen.

**Actual**
The currently selected node is deleted.

This is an issue because I'm building a details edit panel, when I delete a character from the name it deletes the node. See [this](https://i.imgur.com/9OI8W46.png) to get a better idea.

https://github.com/projectstorm/react-diagrams/blob/40b4e14f156457acbd200db859172c99bd8251f4/src/widgets/DiagramWidget.tsx#L128

Poking into the code I can see that it's registering a page wide key hook and doesn't seem to:

1. Have any context if the diagram is focused
2. Have a way to temporarily disable the behaviour.

Let me know if I've missed something, but if you let me know your preferred solution I'll submit a pull request (because this library is awesome).

**Comment by Azim-Palmer** [comment]
Here's my naive/interim solution : https://github.com/Azim-Palmer/react-diagrams/commit/7ec6315d1ea7bc7d3b336cd404b33cb5ea9f3c1c

**Comment by dylanvorster** [comment]
Fixed in storm-react-canvas (the new foundation for react-diagrams thats currently in development) (you have full control over the event bus)

**Comment by rodobodolfo** [comment]
Hi! Is there any fix for this project? should I move to react canvas instead? Im having the exact same problem, a popup or a focus on another element will still delete the node on backspace/delete. 
thanks,

**Comment by sjy** [comment]
@rodobodolfo 
```jsx
..
   deleteKeys=[]

...

**Comment by rodobodolfo** [comment]
@sjy perfect, worked like a charm!! Thank you!!

**Comment by gj1118** [comment]
@sjy @rodobodolfo , Can you please let me know where should I make this change ? I am facing the same issue. 

Thanks
Gagan

**Comment by rodobodolfo** [comment]
> @sjy @rodobodolfo , Can you please let me know where should I make this change ? I am facing the same issue.
> 
> Thanks
> Gagan

pass it as a prop:

```
< SRD.DiagramWidget
				deleteKeys={[]}
				allowLooseLinks={false}
				className="srd-diagram"
				diagramEngine={this.engine} 
/>
```

**Comment by mitkpl** [comment]
Also its bad pattern, but in `entityRemoved` listener you can make controlled ES error like calling undefined function

**Comment by riyadshauk** [comment]
Here's a more complete example that you can run and interact with. The end result is that I modified the delete functionality to only fire when shift is simultaneously pressed down. https://github.com/riyadshauk/oracle-digital-assistant-flow-js/blob/master/builder-web-app/src/base-components/ModifiedDiagramWidget.js

This example is built off of the [Large Application example](http://projectstorm.cloud/react-diagrams/?selectedKind=Advanced%20Techniques&selectedStory=Large%20application&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel), but in the BodyWidget file, just use your own ModifiedDiagramWidget instead of { DiagramWidget } from 'storm-react-diagrams'.

**Comment by rascidomrani** [comment]
node.registerListener({
                  entityRemoved :(e:any)=>{
                    e.stopPropagation();
                  }                  
                });

then you can delete the node in your code
