### ISSUE TITLE
Error with cra: Failed to minify the code from this file...

### ISSUE THREAD

**Issue by cyyyu** [projectstorm/react-diagrams#213]
Hi, I'm using create-react-app(cra) while it fails on 'yarn build'. 
According to cra explanations, to make it works in cra, I suppose you should compile the source codes to es5 which does not remain any es6 features.

Not sure why no one complained with this before, as cra is so wide used in react community. Plz consider fix this : )

![image](https://user-images.githubusercontent.com/15100664/38068974-75fef2e4-3346-11e8-9ba2-f15dc1ee0b95.png)

**Comment by dylanvorster** [comment]
closing this, since I think its fixed already (re-open) if still an issue
