### ISSUE TITLE
"Redux" State

### ISSUE THREAD

**Issue by vron** [projectstorm/react-diagrams#216]
First of all thanks for a great lib.

I have been looking into how I could merge a diagram into my (redux) state - as I use that to allow modifications from multiple locations at the same time.

The best idea I have come up with this far is to listen to events serialize/deserialize but have not yet managed to get that to fully work.

Was wondering if this is a intended use case and/or if anyone else had suggestions for the best way to go about it?

**Comment by ajthinking** [comment]
I cant answer your question, but will fill in with my situation. Im initializing the engine onto the store and then attempt to attach custom data to the nodes.

engineReducer:
```
function defaultEngine() {
        ...
	return engine;
}

export default function (state = defaultEngine(), action) {
	
    if(action.type == "UPDATE_DIAGRAM_ENGINE") {
	state = Object.assign({}, action.payload);
        // I have also tried serialize/deserialize here without any success
    }

    return state;
}
```
Dispatching the action:
```
    setPath(event) {
        var path = event.target.value;
        var id = this.props.node.id;        
        this.props.diagramEngine.diagramModel.nodes[id].extraData = path;        
        this.props.updateDiagramEngine(this.props.diagramEngine);
    }
```
Action:
```
export const updateDiagramEngine = (diagramEngine) => {
    return {
        type: 'UPDATE_DIAGRAM_ENGINE',
        payload: diagramEngine
    }
};

```
I get:
> Uncaught TypeError: nextProps.diagramEngine.addListener is not a function


So no success so far. Did you make any progress @vron ?

**Comment by vron** [comment]
@ajthinking I did not go down the road to store the engine directly in the store as I was expecting that to lead to a lot of copying for large models, for now I simply listen to all events from react-diagrams and maintain the state in to places (engine and redux) and "manually" try to keep them in sync - seems to be working reasonably but it feels neither nice nor future proof

**Comment by dylanvorster** [comment]
This is also fixed in storm-react-canvas (the new foundation thats in development for this lib) (you can subscribe to state changes and use the HistoryBank) also thanks @ajthinking for a good answer
