### ISSUE TITLE
Label on link are not rendering properly

### ISSUE THREAD

**Issue by ganesh-sankey** [projectstorm/react-diagrams#218]
@dylanvorster I fresh cloned the library. Run the set of commands as mentioned in docs.
1. yarn install 
2. yarn run storybook

I came across issue **label not rendering properly on continuous drag of node and also after drag** in the section storybook/demo **Links with labels**. I have attached the gif for the same. 

![ezgif-4-47b70288ed](https://user-images.githubusercontent.com/31685694/38198029-c0160dda-36a8-11e8-817b-cd259aecb5a0.gif)

**Comment by Azim-Palmer** [comment]
I had this issue too but was time pressured and didn't have the time to verify if it was me or a genuine fault.

My hacky temp solution follows below in case you need a quick fix.

   ```
 constructor(props: any) {
        super(props);
        this.labelFixToken = setInterval(this.startFixLabels, 1);
        var state = new State();
        this.state = state;
    }

    startFixLabels() {
        var labels = document.getElementsByClassName('srd-default-link__label');
        for (var i = 0; i < labels.length; i++) {
            labels[i].setAttribute('width', '0px');
        }
    }
```

**Comment by josephjesseyoung** [comment]
I encountered this problem too? is this issue already addressed? 

![screen shot 2019-02-22 at 12 33 43](https://user-images.githubusercontent.com/23491683/53221911-24b3b300-369e-11e9-9ee2-066e1716c0ae.png)

Can someone tell me how to override the addLabel method? I'm using typescript

**Comment by josephjesseyoung** [comment]
UPDATE: just found a semi permanent solution without set interval, open the lib folder in node_modules and find main.js inside /dist/e2e. Open it and direcly find "__label", then change the width into 0.

Note that this fix will be reset everytime you update the library.

**Comment by dylanvorster** [comment]
closing due to investigation https://hackmd.io/@renato-bohler/react-diagrams-issues-analysis
