### ISSUE TITLE
Is there a way to change the CSS/highlight the IN port on selection of OUT port programmatically

### ISSUE THREAD

**Issue by akhilesh-sankey** [projectstorm/react-diagrams#219]
Thanks! for the awesome library.

I want to highlight the all available IN port on selection of any of the OUT port. Does the current event system support this? or is there any other way to get the available ports.

**Comment by dylanvorster** [comment]
It should, you would need to subscribe to the canvas actions and then use something like mobs / the internal event system to have your custom port (which wraps the standard port widget as HOC) and have it change its css internally.

**Comment by OscarCanek** [comment]
Could you post an example please?
