### ISSUE TITLE
How can I persist data on a Node?

### ISSUE THREAD

**Issue by brainmaniac** [projectstorm/react-diagrams#221]
How can I manipulate and persist node properties via a custom widget? I did find the node key in the widget props, but changing it directly does not work. I would like to be able to add an arbitrary key/value to the node. Using react with redux. Any ideas?

I understand this is a usage question, hope its ok anyways. Thanks!

**Comment by AnwarChakhar** [comment]
@brainmaniac why not create specific node with "proporties" key where you can add anything you want ?
don't hesitate to jump into [gitter](https://gitter.im/projectstorm/react-diagrams), you might have more answers there

**Comment by brainmaniac** [comment]
Thanks, @AnwarChakhar! Turns out I just missed to implement serialize in my custom model, therefor nothing I added showed up :)

If anyone else wonders
Add an object to your models constructor 
```
this.data = {};
```
Remember to implement serialize
```
return _.merge(super.serialize(), {			
	data: this.data
});

```

In your widget (or wherever):
```
this.props.node.data.SomeKey = "SomeValue";
```

Serializing will now add the key "data" on your nodes.
