### ISSUE TITLE
Typescript false Linter error

### ISSUE THREAD

**Issue by doureyd** [projectstorm/react-diagrams#222]
Hello there, I'm currently trying to move my project to TypeScript. In VsCode I have some false error when importing  :
```[ts] Module '"c:/.../react/node_modules/storm-react-diagrams/dist/@types/src/main"' has no exported member 'DiagramWidget'.```

Is this related to a bad IDE configuration or it's the lib fault?
I'm new to TS, in other lib they are using a second dependency like `@types/graphql`. Is that what missing to have correct intellisense from the lib?

Thx!

**Comment by dylanvorster** [comment]
hard to tell based on the information you provided. Re-open if this is still an issue
