### ISSUE TITLE
Link labels have unexpected right offset

### ISSUE THREAD

**Issue by robotanz** [projectstorm/react-diagrams#225]
When I run the very first simple demo with React 16.3.1 the link label is displayed with a large right offset. And yet with React 16.2.0 the same code works fine!

**Comment by Azim-Palmer** [comment]
@robotanz Could this be a duplicate of https://github.com/projectstorm/react-diagrams/issues/218 with additional information?

**Comment by robotanz** [comment]
This issue was different, but it probably was some side effect. Today I've made another clean environment with react 16.3.1 and labels are correctly displayed. So I will close this issue. By the way, I've also experienced the issue mentioned in #218
