### ISSUE TITLE
About locking ports

### ISSUE THREAD

**Issue by yanjun0501** [projectstorm/react-diagrams#226]
Hello, sir. Is there a API that can not connect manually to ports?

**Comment by dylanvorster** [comment]
If I understand your question correctly, then yes ports can now be locked. and the behaviour that adds this functionality is also now pluggable

**Comment by dylanvorster** [comment]
https://github.com/projectstorm/react-diagrams/blob/23b174736c1858fa2ee5899505454bf1a408e1a7/packages/react-diagrams-core/src/states/DragNewLinkState.ts#L44
