### ISSUE TITLE
[question] Is it Possible to create a Link without Dragging?

### ISSUE THREAD

**Issue by ilrein** [projectstorm/react-diagrams#231]
Just click to extend the line, and click again to stop drawing the path (no dragging necessary). Is it possible to generate a LinkModel to be used in such a fashion?

**Comment by ray-millward-tessella** [comment]
I'd like to know the answer to this too please - the use case is if we have a large diagram where we might want to connect a block on the left with a block on the far right without having to have dangling links (this is possible in the performance demo by starting a link, leave it in the middle of the page, zoom in and out, then pick up the link again to connect it to the destination port).

**Comment by dylanvorster** [comment]
Yes although a bit tricky to implement, it is now possible to do this with the State machine. Essentially you would have some event on the ActionEventBus (mouse down) which checks to see if you are in a port. If so, it would push a state onto the stack that then listens for a mouse down on another port, and if so, creates that link.

**Comment by dylanvorster** [comment]
theres a demo for this now
