### ISSUE TITLE
[question] is there a way to export the graph to JSON or something else?

### ISSUE THREAD

**Issue by howarth** [projectstorm/react-diagrams#233]
I started looking into the source and I see how I could write my own graph exporter, but I was wondering if there's already something around that does that.

**Comment by sjy** [comment]
Perhaps this is story can meet your requirement.
http://www.projectstorm.io/react-diagrams/?selectedKind=Advanced%20Techniques&selectedStory=Serializing%20and%20de-serializing&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel
![image](https://user-images.githubusercontent.com/1523060/39222879-97d5cbf0-4871-11e8-870d-c104a90d0fb1.png)

**Comment by dylanvorster** [comment]
Thanks @sjy for answering the question :)

**Comment by lukethacoder** [comment]
updated [link](http://projectstorm.cloud/react-diagrams/?selectedKind=Advanced%20Techniques&selectedStory=Serializing%20and%20de-serializing&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel) to the example if anyone stumbles upon this issue
