### ISSUE TITLE
links added through code not rendered properly

### ISSUE THREAD

**Issue by eugeneoeihanalytics** [projectstorm/react-diagrams#234]
I am trying to add nodes and link to the diagram on the click of a button. it will be triggered by a 'Load Diagram' button.

this following is executed when the button is clicked.

    var node1 = new DefaultNodeModel("Node 1", "rgb(0,192,255)");
    var port1 = node1.addOutPort("Out");
    node1.setPosition(100, 100);

    var node2 = new DefaultNodeModel("Node 2", "rgb(192,255,0)");
    var port2 = node2.addInPort("In");
    node2.setPosition(400, 100);

    var node3 = new DefaultNodeModel("Node 3", "rgb(0,192,255)");
    node3.addOutPort("Out");
    node3.setPosition(100, 200);

    var link1 = port1.link(port2);
    
    this.engine.getDiagramModel().addAll(node1, node2, node3, link1);

    console.log('getNodes() >>', this.engine.getDiagramModel().getNodes())
    console.log('getLinks() >>', this.engine.getDiagramModel().getLinks())

    this.forceUpdate();

both `getNodes()` and `getLinks()` capture the nodes and links added to the diagram model.

however, this is what i see when the graph renders. the nodes renders correctly but not the link.
<img width="1437" alt="screen shot 2018-04-26 at 9 24 08 pm" src="https://user-images.githubusercontent.com/30927196/39308807-f98f9bd2-4998-11e8-96e0-ef615502fe01.png">

when i click on any of the nodes, the link renders.

when i move `Node 1`, the link starts from the `targetPort` which is `Node 2` and points to the `0, 0` coordinates as seen here
<img width="1437" alt="screen shot 2018-04-26 at 9 33 05 pm" src="https://user-images.githubusercontent.com/30927196/39308967-72656712-4999-11e8-89cb-2947aeec3288.png">

when i move `Node 2`, the link starts from the `sourcePort` which is `Node 1` and points to the `0, 0` coordinates as seen here
<img width="1431" alt="screen shot 2018-04-26 at 9 35 54 pm" src="https://user-images.githubusercontent.com/30927196/39309124-d495b86a-4999-11e8-8034-9f6486787a5e.png">

i have looked at #223, which seems like a very similar problem. tried the `setTimeout` method but does not seem to work. And, the solution uses the `reDrawDiagram` method which gave me an error.

perhaps i can trigger a select event on any of the nodes so the link renders correctly. but that sounds too much of a hack. has anyone come across this problem? what possible solutions are there?

im using version `5.1.1`

**Comment by jonathanpipe** [comment]
It might help you to debug if you put a breakpoint here:
https://github.com/projectstorm/react-diagrams/blob/master/src/widgets/layers/LinkLayerWidget.tsx#L57
and here:
https://github.com/projectstorm/react-diagrams/blob/master/src/widgets/layers/LinkLayerWidget.tsx#L70

These exceptions being caught in these trys are what causes https://github.com/projectstorm/react-diagrams/issues/223 to occur. If you're entering into those catches, then I think you have the same problem as https://github.com/projectstorm/react-diagrams/issues/223 in which case I'd think a setTimeout in some form should help. I image it would look like this:

```
var node1 = new DefaultNodeModel("Node 1", "rgb(0,192,255)");
var port1 = node1.addOutPort("Out");
node1.setPosition(100, 100);

var node2 = new DefaultNodeModel("Node 2", "rgb(192,255,0)");
var port2 = node2.addInPort("In");
node2.setPosition(400, 100);

var node3 = new DefaultNodeModel("Node 3", "rgb(0,192,255)");
node3.addOutPort("Out");
node3.setPosition(100, 200);

this.engine.getDiagramModel().addAll(node1, node2, node3);

console.log('getNodes() >>', this.engine.getDiagramModel().getNodes())
console.log('getLinks() >>', this.engine.getDiagramModel().getLinks())

this.forceUpdate();

setTimeout(() => {                
    var link1 = port1.link(port2);
    this.engine.getDiagramModel().addAll(link1);
    this.forceUpdate();
}.bind(this), 0);
```
The reason we use setTimeout is to merely ensure that the edge is added on the next Execution Context (http://davidshariff.com/blog/what-is-the-execution-context-in-javascript/) and therefore the node should have been rendered before the link. I use redux in my solution. When I fire an add node action, I have an epic (https://github.com/redux-observable/redux-observable) that does debounceTime(0) to achieve the same thing as setTimeout(0).

If you're not entering those catches, then you must have some different bug.

**Comment by eugeneoeihanalytics** [comment]
thanks @jonathanpipe ! your suggestion worked! reading the execution article link made things clearer for me. will definitely consider including redux in what i am trying to do subsequently. still experimenting and getting the basic framework up for now. thanks again!

**Comment by iyobo** [comment]
This is still an issue when deserializing!

**Comment by PikkaPikkachu** [comment]
Yeah, I am facing the same issue
