### ISSUE TITLE
Wrong label positioning

### ISSUE THREAD

**Issue by unsafecode** [projectstorm/react-diagrams#237]
Looks like label position is broken, even in the demo:

http://www.projectstorm.io/react-diagrams/?selectedKind=Simple%20Usage&selectedStory=Links%20with%20labels&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel

(Tested with Chrome 66)

**Comment by dylanvorster** [comment]
<img width="582" alt="screen shot 2018-05-08 at 09 47 08" src="https://user-images.githubusercontent.com/6099427/39744515-d029779e-52a4-11e8-9c82-a4540e1fa0fe.png">

Looks fine on my side >.>

**Comment by unsafecode** [comment]
@dylanvorster You sure?

![image](https://user-images.githubusercontent.com/1794924/39758032-03c52bdc-52cf-11e8-926d-5dcec1100068.png)

**Comment by unsafecode** [comment]
@dylanvorster I'm still experiencing issues. Based on my investigations, it looks like screen DPI matters, as my Surface Pro looks different than my colleague's notebook. Yet still position is not perfect and dragging yields strange rendering defects.

IMHO, the strangest thing happens when inspecting labels from Chrome Dev Tools: their <div>s are actually positioned as I would expect, close to the link, but the text is missing. I played a lot trying to make it appear, but without luck...

**Comment by unsafecode** [comment]
@dylanvorster It looks like to be a Chrome-specific issue, as Edge and Firefox do NOT show the same behavior....

**Comment by unsafecode** [comment]
I can confirm it was a [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=616864), now fixed in v67.
