### ISSUE TITLE
How to make a custom diamond node  ! I need help!!! thanks

### ISSUE THREAD

**Issue by yanjun0501** [projectstorm/react-diagrams#238]
please tell me how to make a custom diamond node, or give me the config !Thank you very much!

**Comment by dylanvorster** [comment]
See the demo code for the demo?

http://www.projectstorm.io/react-diagrams/?selectedKind=Custom%20Models&selectedStory=Custom%20diamond%20node&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel
