### ISSUE TITLE
How to make custom shapes, arrowheads and change line thickness?

### ISSUE THREAD

**Issue by Nahuel92** [projectstorm/react-diagrams#239]
Hi everyone!! I'm new to React and I love this project. I've started to use it and found somethings I want to ask for.
I'm needing to make arrowheads and be able to change line thickness (not in all lines just in a few, for example one to three lines).
Also I need to use custom shapes. A square edge corner shape, a square rounded corner shape(a little more pronounced that default shape) and a rectangle with one opened side and a vertical line.
I made a sketch to be more descriptive. You can see it below:

![image](https://s7.postimg.cc/gtgffygjf/image.png)
Can you help me, please?

Thanks in advance!!
Regards!

**Comment by dylanvorster** [comment]
For the custom shapes, take a look at the demo:

* http://www.projectstorm.io/react-diagrams/?selectedKind=Custom%20Models&selectedStory=Custom%20diamond%20node&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel

For the custom links (where you could implement your own arrows):
* http://www.projectstorm.io/react-diagrams/?selectedKind=Custom%20Models&selectedStory=Custom%20animated%20links&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel

**Comment by dylanvorster** [comment]
Same as #238

**Comment by ganesh-sankey** [comment]
@dylanvorster can you update the above demo links ?

**Comment by nicolashorbacz** [comment]
Hi everyone :) 

I got the exact same problem. I would like to create class diagrams and UML diagrams so I need several types of arrows and lines.

Someone knows how to do it or saw some examples ?

@dylanvorster if you are still here :) Maybe you could help.

Thank you in advance.

**Comment by abhiravredox** [comment]
Hi, How did you finally do it? I tried the story book code piece but the circle moves only from left to right!

How to make a link with something like a static arrow or something similar.

Thanks in advance.
