### ISSUE TITLE
TypeError: Cannot read property 'getInstance' of undefined (_class and uglify.js related)

### ISSUE THREAD

**Issue by yuraxdrumz** [projectstorm/react-diagrams#241]
Hey, I am using storm-react-diagrams 3.2.0 and it worked great in development. When switching to production i noticed the following error:
![screenshot from 2018-05-10 12-32-56](https://user-images.githubusercontent.com/17418978/39863107-62d6c998-544e-11e8-85ae-1e03d2fcbdf3.png)
After intense debugging i noticed that there is a place in your code that tries to find the _class of the node/port:
![screenshot from 2018-05-10 12-35-26](https://user-images.githubusercontent.com/17418978/39863218-b402ca38-544e-11e8-9b2d-737d713cfa9b.png)

Now, I checked my database, where i store the diagram json entirely and I noticed that _class in development mode is DefaultNodeModel/DefaultPortModel and in production, where i get the error it stores it as "t".
![screenshot from 2018-05-10 12-38-57](https://user-images.githubusercontent.com/17418978/39863373-1e876346-544f-11e8-83b3-49456fcf84d5.png)

I noticed it happens after i serialize it again in production mode. 
Here is the function that looks up the factories keys:
![screenshot from 2018-05-10 12-44-15](https://user-images.githubusercontent.com/17418978/39863750-3664f0b8-5450-11e8-86ff-282ed5d2108b.png)
You can see it here that all the original names are saved, but it tries to find a non existing key "t"
![screenshot from 2018-05-10 12-45-49](https://user-images.githubusercontent.com/17418978/39863832-70ec9b64-5450-11e8-87b5-9e7ef2f24fee.png)
![screenshot from 2018-05-10 12-47-27](https://user-images.githubusercontent.com/17418978/39863874-94bca8f4-5450-11e8-8ffb-e1789ea4b250.png)

My guess is that something in uglify.js changes the string name to "t" when you serialize.
I do not know if its on my side or the libraries side,
Thanks for the help in advance, Love your project!

**Comment by dylanvorster** [comment]
I no longer rely on the className :) so this issue should be fixed now
