### ISSUE TITLE
Can't delete links sometimes

### ISSUE THREAD

**Issue by iddan** [projectstorm/react-diagrams#245]
In some cases I cant identity (the simplest case is one of them) when pressing the `Backspace` key while a link is selected it is not being deleted. If one of it's parents are deleted it is deleted though.

**Comment by Nandez89** [comment]
Might be related with this https://github.com/projectstorm/react-diagrams/issues/49

**Comment by iddan** [comment]
Might be, but it's a different issue.

**Comment by dylanvorster** [comment]
closing due to investigation https://hackmd.io/@renato-bohler/react-diagrams-issues-analysis
