### ISSUE TITLE
Copy diagram as image

### ISSUE THREAD

**Issue by unsafecode** [projectstorm/react-diagrams#248]
Is there a way to copy the whole rendered diagram as an image to clipboad?

Since no `<canvas>` element is used, I'm afraid this can't be done natively...

**Comment by ipassynk** [comment]
You try to use html2canvas library

**Comment by dylanvorster** [comment]
The only way you will be able to get this right (and done properly) is by spawning up a docker container with puppeteer and rendering this on the server side into pdf , svg etc... (thats how I would do it) <- I assume Lucid chart also works like this

**Comment by stanislav-grin** [comment]
Is there really no other way to export as PDF/PNG, other than by spawning up a docker container with puppeteer? I think that in 80% of cases for those who are using this wonderful library, it is needed to have support for export in different formats. At least in some single format - PDF or PNG. Can this feature be requested for future?

**Comment by miso-belica** [comment]
The only way I was able to figure out is here https://github.com/projectstorm/react-diagrams/issues/716#issuecomment-689403393 but it's far from perfect and I am trying to find a better solution again :(
