### ISSUE TITLE
Change the React dependency to a peerDependency

### ISSUE THREAD

**Issue by MrBlenny** [projectstorm/react-diagrams#250]
`peerDependency` is the standard way of dealing with the react depency in a react library. For example, here are 3 randomly selected react libs:

* https://github.com/tleunen/react-clickdrag/blob/master/package.json
* https://github.com/nfl/react-helmet/blob/master/package.json
* https://github.com/moroshko/react-autosuggest/blob/master/package.json

I looked through through about 10 libraries in my package.json and every one of them sets react to a peerDependency except for this. Currently, this library dictates the version of react for the rest of my application.

---

In my specific case, my project uses react@15.3.1. I cannot build production because this library has a newer react version in dependencies. Nonetheless, it seems to works perfectly with react@15.3.1. I have created my own fork and npm package that this fixes this issue for me.

https://github.com/MrBlenny/react-diagrams/commit/2e64952d7d4d11792ad725fef327756d3acf8774

`npm i mrblenny-storm-react-diagrams@5.2.1`

**Comment by donomans** [comment]
This is really problematic to have as a dependency, it's just guaranteeing multiple versions of react being included in a person's project.

**Comment by dylanvorster** [comment]
It is now a peer dep in ver 6
