### ISSUE TITLE
events for adding/moving points

### ISSUE THREAD

**Issue by bknill** [projectstorm/react-diagrams#253]
Is there anyway to capture a  link point being added/removed?

**Comment by Atvo** [comment]
Hi bknill,

Check this link [https://github.com/projectstorm/react-diagrams/issues/164](url)

**Comment by ianchanning** [comment]
@Atvo For some reason your link is different from the text, but you can just write #164 and the link is automatic

**Comment by dylanvorster** [comment]
All `BasePositionModel` models now fire `positionChanged` which includes Points
