### ISSUE TITLE
error on Toolkit.ts

### ISSUE THREAD

**Issue by rdbl** [projectstorm/react-diagrams#255]
Info	Typescript	Could not find a declaration file for module 'closest'. '/home/bitout/Documents/1.code/2-tmpProjects/my-app/node_modules/storm-react-diagrams/node_modules/closest/index.js' implicitly has an 'any' type. Try `npm install @types/closest` if it exists or add a new declaration (.d.ts) file containing `declare module 'closest';`	2:26

Info	Typescript	Could not find a declaration file for module 'paths-js/path'. '/home/bitout/Documents/1.code/2-tmpProjects/my-app/node_modules/storm-react-diagrams/node_modules/paths-js/path.js' implicitly has an 'any' type. Try `npm install @types/paths-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'paths-js';`

do you know why ?

**Comment by dylanvorster** [comment]
think this is fixed now, also make sure to add `closest` as a dependency

**Comment by erikyudi** [comment]
Hi Dylan, 
How i add closest as a dependency?
