### ISSUE TITLE
Anyway to link both in and out link in same port instead of creating two different ports

### ISSUE THREAD

**Issue by gaurav110** [projectstorm/react-diagrams#261]
Anyway to link both in and out link in same port instead of creating two different ports?

**Comment by tabdon** [comment]
@gaurav110 did you ever figure out a way to do this?

**Comment by DawaHIT** [comment]
@gaurav110 @tabdon
https://github.com/DawaHIT/react-diagrams/commit/20f2815ecac7b98eccaba543939a6e74105122bb

**Comment by riyadshauk** [comment]
As @DawaHIT suggested, we just need to override the canLinkToPort method of whatever class is used to extend PortModel (or if you directly use PortModel). For example, if we're trying to make this work on the DiamondPortModel from one of the demos, just override canLinkToPort inside DiamondPortModel:

```javascript
canLinkToPort = () => true;
```

**Comment by gaurav110** [comment]
I was not able to find a solution. I took a different approach in displaying the same but still had to use two different ports. Thank you @DawaHIT for this suggestion. I will definitely try it.

**Comment by dylanvorster** [comment]
@riyadshauk knows whats up :P
