### ISSUE TITLE
Is it possible to use "overflow: auto"?  Link alignment problem.

### ISSUE THREAD

**Issue by mreishus** [projectstorm/react-diagrams#262]
The `srd-diagram` comes with an `overflow: hidden` rule out of the box, but I would like to use `overflow: auto`.  I've found a bug that happens when programmatically updating the diagram while using `overflow: auto`.  Do you know another approach that can provide scrollbars to the user, so they don't get lost in the canvas, that does not have this bug?

Steps to reproduce:

- Load the "Programmatically modifying graph" example from storybook
- Open chrome dev tools and locate the div with class `srd-diagram`.
- Turn off the `overflow: hidden` CSS rule.
- Add a new rule for `overflow-y: auto`.
- Shorten the browser window such that a scroll bar appears.  You may need to drag nodes downward.
- Scroll the inner scrollbar.
- Press the `Update position via Serialize` button
- The links are no longer aligned.

Gif:

![2018-07-13_09-29-15](https://user-images.githubusercontent.com/937354/42696936-526b729e-867f-11e8-8246-73ad972dc984.gif)

**Comment by quentingirard** [comment]
Any one find a solution ?

**Comment by dylanvorster** [comment]
Fixed in 6.0

**Comment by khoaanh2212** [comment]
Dear @dylanvorster 
for some reason i can not use 6.0 for now,just only can use version 5.how can i fix this?
Thanks
