### ISSUE TITLE
Any way to add multi line text to node?

### ISSUE THREAD

**Issue by isrplo** [projectstorm/react-diagrams#263]
I tried using \n in the string, but i guess that there's a function that removes it.
Thanks

**Comment by JokerNN** [comment]
I think the proper way of doing what you want is having custom node with textarea inside. You can take a look at custom node example to understand how it can be done.

**Comment by dschoon** [comment]
You should be able to do this with some CSS. Something like...

```
.srd-default-node__name {
    text-align: center;
    max-width: 50px;
    white-space: pre-wrap;
    overflow: hidden;
}
```

**Comment by dylanvorster** [comment]
Yeah, best way to do this is to create a custom node, see the http://projectstorm.cloud/react-diagrams/?path=/story/custom-models--custom-diamond-node demo for an example of making your own node
