### ISSUE TITLE
Demo link is down? 

### ISSUE THREAD

**Issue by wadyybb** [projectstorm/react-diagrams#264]
Hi, I found the demo really useful but seems like it's down recently. Would it be possible to bring it back? Thanks a lot!

**Comment by zimekx** [comment]
@wadyybb 
Not sure why the demo is down but you can set it up locally and bump `@storybook/addons@alpha` and `@storybook/react@alpa` to make it work.

**Comment by dylanvorster** [comment]
Fixed its now `projectstorm.cloud/react-canvas` :3
