### ISSUE TITLE
Update Dimensions of default Node Model is not working 

### ISSUE THREAD

**Issue by qpixHassaballah** [projectstorm/react-diagrams#265]
I am getting start with this project it works fine with my react app but when i define an engine and nodes within my code in a single component which i call in my home.js ("Consider this my basic template") 
I can not resize neither the Nodes in the project or the area of the "canvas" on which the nodes are present 
I've placed the component inside a div and gave the div a background color and it only occupies 20-30% of the page height although it fills 100% of the width , 
I 've searched into the source code trying to update the dimensions or the width or the height but with no use 
Any help on why this is happening ? 

Note ("I fully acknowledge that this problem might be due to my insufficient knowledge with this project's code ")

**Comment by JokerNN** [comment]
If you can share code that is not working - I can help you. But otherwise it's unclear to me what you've tried to do and how. Please elaborate
