### ISSUE TITLE
Can you add an event listen on node move? If so, how?

### ISSUE THREAD

**Issue by Grandclosing** [projectstorm/react-diagrams#267]
I've tried everything and I can't for the life of me figure out how to determine if a node on the grid is moved. Specifically I'd like to know the node's position when the movement completes so I can persist that information in my app. 

Thanks in advance.

**Comment by JokerNN** [comment]
Hello @Grandclosing , there's 3 props of diagram widget - `actionStartedFiring`, `actionStillFiring`, and `actionStoppedFiring` which are callbacks and provide you with current action happening. Action you're looking for is `MoveItemsAction`

**Comment by Grandclosing** [comment]
@JokerNN 
Is there any place that documents this kind of stuff and is up to date? 
I looked at the advertised docs here: https://projectstorm.gitbooks.io/react-diagrams/

But those docs seem to be incomplete, offering only really simple 'quick-start' information. 

The demos here: http://projectstorm.cloud/react-diagrams/

Also offer only simple examples...

**Comment by JokerNN** [comment]
Hey @Grandclosing , I read the code. I understand your frustration, but this project has no commercial support, so some parts are not perfect. But everyone are more than welcome to contribute, so if you succeed in listening to moving event, you can share your demo, that would be just great.

Also you can let me know if you need any help

**Comment by Grandclosing** [comment]
Thanks @JokerNN ! I will definitely contribute whatever knowledge/code I can. :)

**Comment by ianchanning** [comment]
The [Build interactive diagrams with storm-react-diagrams][1] blog post has some good notes on the API for events

> Events for the diagram model
> 
> ```
> nodesUpdated
> linksUpdated
> offsetUpdated
> zoomUpdated
> gridUpdated
> selectionChanged
> entityRemoved
> ```
>
> Events for Link models
> 
> ```
> sourcePortChanged
> targetPortChanged
> selectionChanged
> entityRemoved
> ```
> 
> Events for Node models and Point models
> 
> ```
> selectionChanged
> entityRemoved
> ```


[1]: https://blog.sourcerer.io/build-interactive-diagrams-with-storm-react-diagrams-f172ae26af9d#f0a4

**Comment by ianchanning** [comment]
The ['events and listeners' example][1] has the basics if you haven't already seen that.

[1]: http://projectstorm.cloud/react-diagrams/?selectedKind=Simple%20Usage&selectedStory=Events%20and%20listeners&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

**Comment by ianchanning** [comment]
Also see #287

**Comment by JoeCase** [comment]
@Grandclosing Did you figure out how to implement this? It seems from the thread that it is possible, but I can't figure out how to implement it.

**Comment by matthax** [comment]
@ianchanning The referenced example no longer exists, has it moved?

**Comment by dylanvorster** [comment]
its now core in version 6 https://github.com/projectstorm/react-diagrams/blob/23b174736c1858fa2ee5899505454bf1a408e1a7/packages/react-canvas-core/src/core-models/BasePositionModel.ts#L6
