### ISSUE TITLE
Disable node suppression on backspace input

### ISSUE THREAD

**Issue by FlynnTheInfinite** [projectstorm/react-diagrams#271]
Hi.
I'm using input within custom nodes, and whenever I press backspace to delete a character, it removes the node.
I know this is a default behaviour, but I can't find how to disable that. (stopping input event propagation does nothing)

Is there a way to avoid this behavior ?

**Comment by JokerNN** [comment]
Hey @FlynnTheInfinite . I had same problem and I stopped propagation of `keyUp` event.
Let me kno if it helps, if not -you can share the code bit, so I can take a look.

**Comment by FlynnTheInfinite** [comment]
Yes, it worked ! Thanks 😄

**Comment by iyobo** [comment]
I resolved this by adding CTRL key modifier to deletion hotkey. This is in onKeyUp in DiagramWidget.

**Comment by puckwang** [comment]
> I resolved this by adding CTRL key modifier to deletion hotkey. This is in onKeyUp in DiagramWidget.

Thanks, it worked！

for example: 
```jsx
<DiagramWidget deleteKeys={[]} />
```

**Comment by jestingthomas** [comment]
Can any of you share a code snippet where you are overriding the keyup event?

**Comment by ccapeng** [comment]
This is how I get it work.

Handle focus event on the form, and set
`model.setLocked(true);`

Then, in the container of diagram area, handle click event, and 
`model.setLocked(false);`

Currently, I am looking how to prevent node/edge deletion, but still allow drag around node.

**Comment by renato-bohler** [comment]
@ccapeng `react-diagrams` has a set of "States", which are¹ a set of handlers for events like creating links, dragging the canvas and dragging nodes.

By default, all diagrams come with [`DefaultDiagramState`](https://github.com/projectstorm/react-diagrams/blob/a399f135ba86ed16d29c87c2b562ba6ad0e0b11a/packages/react-diagrams-core/src/states/DefaultDiagramState.ts), which uses [`DragDiagramItemsState`](https://github.com/projectstorm/react-diagrams/blob/a399f135ba86ed16d29c87c2b562ba6ad0e0b11a/packages/react-diagrams-core/src/states/DragDiagramItemsState.ts) to handle item dragging, which extends [`MoveItemsState`](https://github.com/projectstorm/react-diagrams/blob/4a57ecdc97d319986f12cb8e84112e2d3cd5f946/packages/react-canvas-core/src/states/MoveItemsState.ts). The disallowing of moving locked entities is found on [these lines](https://github.com/projectstorm/react-diagrams/blob/4a57ecdc97d319986f12cb8e84112e2d3cd5f946/packages/react-canvas-core/src/states/MoveItemsState.ts#L46-L48).

So, to achieve what you want, you could make your own `CustomDiagramState` (copy of `DefaultDiagramState`) and set it to use `CustomDragDiagramItemsState`, which can override the `fireMouseMoved` function (or you can make your `CustomMoveItemsState`, change the implementation and make `CustomDragDiagramItemsState` to extend it).

You could change the implementation to allow only the moving of nodes:
```JavaScript
if (item instanceof BasePositionModel) {
//if (item.isLocked()) {
  if (!(item instanceof NodeModel) && item.isLocked()) {
    continue;
  }
}
```

Hope this helps.

---
_¹ In my understanding. I would really like documentation on this part, to better understand the concepct and the name choice_

**Comment by noahtren** [comment]
This was the first result for my problem and the solution I found isn't here so thought I'd share:

For version 6, there's a demo in the demo gallery that does exactly this. See: https://github.com/projectstorm/react-diagrams/blob/508fbf27779e3a1e22ab09d9b24f3c68db9617ab/packages/diagrams-demo-gallery/demos/demo-custom_delete_keys/index.tsx

**Comment by d2askif** [comment]
how i solved it for input 
onFocus={() => this.props.node.setLocked(true)}
          onBlur={() => this.props.node.setLocked(false)}
