### ISSUE TITLE
Link labels are not properly aligned due inheriting CSS "text-align" setting

### ISSUE THREAD

**Issue by highfield** [projectstorm/react-diagrams#273]
I realized that the link labels are drawn in the wrong place when the `svg` island inherits a CSS `text-align` value which is not `start`. Try to set it as `center`, for instance, and the result is immediately visible.

I believe an explicit set of `text-align: initial` (or `start`) at the `svg` element level should be enough.

**Comment by dylanvorster** [comment]
Dont think this is an issue anymore, also you can create your own labels now using the pluggable LabelModel and corresponding widget

**Comment by dylanvorster** [comment]
https://github.com/projectstorm/react-diagrams/tree/master/packages/react-diagrams-defaults/src/label
