### ISSUE TITLE
Gantt chart using  react - diagram

### ISSUE THREAD

**Issue by chathuraa** [projectstorm/react-diagrams#276]
Hi there,

Is it possible to add an example of the gantt chart using react diagram?

Thanks,
Chat

**Comment by JokerNN** [comment]
Hey, I believe this library is not for charts at all. It's for diagramming in browser. So no charts (bar, pie, line, plot, gantt etc...) supported with this library. You're probably looking for something like chartjs/highcharts

**Comment by dylanvorster** [comment]
Yeah, I think this is out of scope of this project.
