### ISSUE TITLE
Are the diagrams responsive?

### ISSUE THREAD

**Issue by ahsanbagwan** [projectstorm/react-diagrams#278]
I've searched the documentation as well as the issues tab however couldn't find any. Is there any information about making this responsive that I missed?

**Comment by JokerNN** [comment]
Hello @ahsanbagwan , what do you mean by making them responsive? You can make the container of flexible width, and all nodes are just html - so you can write styles with media queries for them.

I think little bit of context from your side will be helpful to understand what you're trying to achieve

**Comment by ahsanbagwan** [comment]
Thanks for your reply. I'm a little rusty with the CSS. I'm assuming the container is `.srd-diagram` or `srd-demo-canvas` class.

If so do you mean something like below?

```
.srd-diagram .srd-demo-canvas {
   width: 100%;
   height: 100%;
}
```

**Comment by JokerNN** [comment]
Yes, that what I meant. Only except css selector will be more like just
`.srd-diagram`

Because demo-canvas is only applied on demos level, not in library itself
