### ISSUE TITLE
Is there a way to set colors with css instead?

### ISSUE THREAD

**Issue by bartvde** [projectstorm/react-diagrams#288]
Is there a way to set colors or borders etc. with css on the nodes?

**Comment by JokerNN** [comment]
Yes, nodes are just html with classes and other attributes. For example for default node classes are the following: 

```
.srd-default-node
.srd-default-node__title
.srd-default-node__name
.srd-default-node__ports
```
etc...

However if you implement your own widget - you can use your own markup and any classNames you want

**Comment by bartvde** [comment]
ok, so it would need a custom widget to set a custom className on a node, thanks for confirming

**Comment by bartvde** [comment]
ideally I would like to have seen an option on the constructor to pass a className, just like we can pass a color for a node
