### ISSUE TITLE
How to implement nodeSelected event

### ISSUE THREAD

**Issue by vallibe** [projectstorm/react-diagrams#290]
Someone could you please help me to implement nodeSelected event only if a single node is selected?.
I just want to display the selected node details (name, etc.) in another component (like property grid) while clicking on a node.
Please can someone give me some example code like where to add listener and invoke and implement the action.
I know what i am asking is basic stuff, but pls help me to kick start on this awesome library.
Thanks.

**Comment by JokerNN** [comment]
Hello there! I'm aware that there is `selectionChanged` event like in [Demo 4](https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/demos/demo-listeners/index.tsx#L45)

Also there is `getSelectedItems` method for DiagramModel which can give you all selected entities.

You can try to use them those! Let me know if it helps

**Comment by vallibe** [comment]
Thanks @JokerNN, it was really helpful.
Sorry for the delayed response.

**Comment by gj1118** [comment]
@vallibe , Can you please let me know if `selectionChanged` event worked for you ? I have this code and it is not firing for me. 
```
		model.addListener({
		    nodesUpdated: e => console.log("nodesUpdated", e),
		    linksUpdated: e => console.log("linksUpdated", e),
		    
		    // these are never triggered
		    zoomUpdated: e => console.log("zoomUpdated", e),
		    gridUpdated: e => console.log("gridUpdated", e),
		    offsetUpdated: e => console.log("offsetUpdated", e),
		    entityRemoved: e => console.log("entityRemoved", e),
		    selectionChanged: e => console.log("selectionChanged", e)
		});
```

**Comment by vallibe** [comment]
@gj1118, Yes it is working. As mentioned above in [Demo 4](https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/demos/demo-listeners/index.tsx#L45), I have added `selectionChanged` event for node not for model. Please have a look at `entityRemoved` event to get some idea.
