### ISSUE TITLE
Support this library

### ISSUE THREAD

**Issue by azotklas** [projectstorm/react-diagrams#295]
Hello. This is a good library that I want to use in my project. I am confused by the fact that it does not updated... there are no new changes, improvements, fix bugs ...  Will you continue working on the library?

**Comment by JokerNN** [comment]
Hey, I think most of the work is happening in react-canvas, since Dylan wants to refactor the whole thing:

https://github.com/projectstorm/react-canvas

**Comment by dylanvorster** [comment]
So I finally did the thing xD
