### ISSUE TITLE
How can I resize nodes?

### ISSUE THREAD

**Issue by vallibe** [projectstorm/react-diagrams#296]
I want to resize the node by dragging the edges along with ports and links. Can someone help me, please?.

**Comment by jason-sqpm** [comment]
Default nodes included with storm-react-diagrams aren't resizeable.   You would have to implement a NodeWidget class that responds to resize events.  You might want to look at a library like react-resizeable to help you implement it.

**Comment by dylanvorster** [comment]
correct
