### ISSUE TITLE
Declarative API

### ISSUE THREAD

**Issue by lordi** [projectstorm/react-diagrams#297]
Right now it seems that the way to influence the graph is by calling "addAll", "link", etc. on the Model, Nodes and Ports. 

While this seems a reasonable start, it does not fit the React model very well. Have you thought about a declarative API, like:

```
<DiagramWidget onNodeMove={...} onConnect={...} >
  { nodesA.map((n) => <MyNodeA id={...} node={n} /> }
  { nodesB.map((n) => <MyNodeB id={...} node={n} /> }
  { links.map((link) => <Link from={...} to={...} /> }
</DiagramWidget>
```

**Comment by JokerNN** [comment]
That's a good idea. However I think render props might be even more suitable and scalable than just children.

**Comment by ianpogi5** [comment]
I agree with declarative api.

**Comment by MrBlenny** [comment]
I'm working on a declarative flow chart lib [here](https://github.com/MrBlenny/react-flow-chart)
