### ISSUE TITLE
Doubt: CustomNodes on ES6 Project

### ISSUE THREAD

**Issue by AyozeVera** [projectstorm/react-diagrams#298]
Hello, first of all nice project. I have a doubt, I am trying to use react-diagrams on an existing project completely written in ES6, but when I try to create my own Custom Node, I get the error: 
TypeError: __WEBPACK_IMPORTED_MODULE_1__components__.c is not a constructor
This error may occur because I am trying to extend and Class on a .ts file (AbstractNodeFactory) in a .js file (CustomNodeFactory, or in the example DiamondNodeFactory) ?
I made a [github gist](https://gist.github.com/AyozeVera/bde1b43e8d6feba705f4ed4bebce19d1) to show the code, maybe someone can help o see something that i cannot see.

Thanks for all!

**Comment by micahelriceio** [comment]
@AyozeVera Did you have solve this?
