### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by hashwin** [projectstorm/react-diagrams#301]
Any way to use this library on mobile? Right now on my android phone, it renders, but I cannot scroll.

**Comment by alexandrudanpop** [comment]
+++ would be great to have it work on mobile.

**Comment by prateekgoel** [comment]
Any plans for this?

**Comment by DorisOu** [comment]
@hashwin did you solve the problem?
could it run on ios ?

**Comment by dylanvorster** [comment]
This is too-big an effort to implement right now

**Comment by yuri-denysenko-codefresh** [comment]
@dylanvorster Hi mobile support is the thing we need for our project. Will you assist if we create a pr for it? I saw 1 pr rejected that tried to solve the  issue.
