### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by tangert** [projectstorm/react-diagrams#302]
Hi, love this project and it's going to be absolutely indispensable to me in creating one of my interfaces. I just wish there was stronger documentation behind creating custom nodes. Are there any plans on updating the docs site? I read on the react-canvas repo that you are quite busy and haven't been working on this... I'll do my best to contribute with my own work as well.

**Comment by kmannislands** [comment]
Also have to crack open the source to figure out how anything (outside of examples) works with this lib

I think the exercise of documenting may actually lead to improvements to the api interface where things are counter-intuitive.

Would also be willing to coordinate on a doc effort, perhaps TSDoc?

**Comment by tangert** [comment]
@kmannislands what do you want to focus on?

**Comment by emmagoldblum** [comment]
Hi, thanks for all your work on this really interesting API ! However, so you think it would be possible to prepare a documentation of the API, with the props of each important components ? The demos are quite useful to understand pretty well how it works, however it is hard to be really productive without this kind of documentation.

**Comment by dylanvorster** [comment]
yes yes xD No disagreements here. But I am only one person :(

**Comment by emmagoldblum** [comment]
I'd gladly help you out :)

**Comment by dylanvorster** [comment]
its finally happening https://projectstorm.gitbook.io/react-diagrams
