### ISSUE TITLE
Links layer disappears on zoom

### ISSUE THREAD

**Issue by kmannislands** [projectstorm/react-diagrams#303]
Might be related to #188 
Seeing an unexpectedly empty 'links' layer (actually empty, you see the react empty comments) after implementing a simple 'zoom in' until the next interaction (ie a click or zoom will cause the links to show up).

Modified the ['zoom to fit' demo in a fork to serve as minimal repro](https://github.com/kmannislands/react-diagrams/commit/58db1f2c4d6dcbb304933eb68f0a329deb0b9ed9)

Here's a gif of the behavior:
![zoom-in-links-missing](https://user-images.githubusercontent.com/15148927/48386939-97c58a80-e6a8-11e8-8f5f-1d63dd26790e.gif)

**Comment by JokerNN** [comment]
I'm not sure if that's the reason but you're doing `engine.setDiagramModel(model);` in your event handler, and it is completely unnecessary

**Comment by kmannislands** [comment]
@JokerNN removing that call does fix the bug for me, thanks!
Didn't realize the engine would pick up changes to the mutable model automagically. Neato.

**Comment by JokerNN** [comment]
Hey @kmannislands glad it helped!
`Didn't realize the engine would pick up changes to the mutable model automagically`
- for this case it's not really picking it up. It's just `repaintCanvas` call.
In lots of different cases it does subscribe on model changes
