### ISSUE TITLE
Event for link deletion?

### ISSUE THREAD

**Issue by eramstein** [projectstorm/react-diagrams#304]
I could intercept all the events I needed with the actionStoppedFiring prop of DiagramWidget.

But when I delete a link nothing triggers. Am I missing something or is this not implemented?

**Comment by JokerNN** [comment]
`linksUpdated` on `DiagramModel` should fire when link is removed. Arguments are `linkModel` and `isCreated=false`

**Comment by eramstein** [comment]
Thanks a lot!

For those who have the same question later, you can add listeners on the diagram model directly like this:

const model = new DiagramModel();
model.addListener({ linksUpdated: handleLinksUpdated });
