### ISSUE TITLE
Double click on node event

### ISSUE THREAD

**Issue by alexandrudanpop** [projectstorm/react-diagrams#310]
Is there a possibility to hook to a doubleClick event - or even better specify some custom events for nodes or links?

**Comment by JokerNN** [comment]
I think yes, you basically can implement any logic in your own NodeWidgets, including listening of `dblclick`. You can check custom node demo

**Comment by alexandrudanpop** [comment]
Is that possible only if I create custom nodes?

**Comment by JokerNN** [comment]
Yes, the whole extensibility feature of this library based on idea of custom widgets/models

**Comment by mitkpl** [comment]
I have made on my fork a global handler for doubleClick it is better solution because of best practices (one source of true). 
*file: `./src/widgets/DiagramWidget.tsx`
and add a handler after/before `onMouseDown` definition
```
	onDoubleClick={event => {
		...
	}}
```
