### ISSUE TITLE
Is it possible to re-order ports within a node?

### ISSUE THREAD

**Issue by AM1467** [projectstorm/react-diagrams#311]
I am looking for a way to change the order of the ports after the node has been rendered, for example letting a user select a port and move it up or down in a node (doesn't have to be drag & drop, up/down arrows would work). I can successfully select a port by clicking on it (had to implement this bit myself) but now I'm trying to figure out how the order of the ports is being decided in order to manipulate it.

Getting the ports of a node shows that it's just an object containing the ports as properties. Unlike an array, this is not structured in a set order and when I add a new port to an existing node programmatically it even seems to be added in the middle of "ports" even though on the diagram it appears at the bottom.

![image](https://user-images.githubusercontent.com/14926899/50056990-1b254080-016d-11e9-894c-4b7ea0762281.png)

I would appreciate some help on this, if anyone can figure it out.

**Comment by JokerNN** [comment]
You can take a look at those methods to override: [getInPorts](https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/defaults/models/DefaultNodeModel.ts#L43), [getOutPorts](https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/defaults/models/DefaultNodeModel.ts#L49).

**Comment by dylanvorster** [comment]
yes! this is now possible either by using your own node and ports: https://projectstorm.gitbook.io/react-diagrams/customizing/ports and is shown off quite well in this demo: http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--dynamic-ports (click add more ports) <- will prepend ports
