### ISSUE TITLE
is it possible to achieve modal popup while clicking on link(connection between two nodes)

### ISSUE THREAD

**Issue by hamsa95** [projectstorm/react-diagrams#312]
Need to achieve the modal popup kind of thing that needs to be a popup while just clicking the link between the two nodes??

Can you please suggest me the idea.

**Comment by Laykou** [comment]
Hi, I'd like to ask the same question - how to achieve custom modal popups and buttons like in this screenshots?

![image](https://user-images.githubusercontent.com/2313005/61853980-677fee00-aebd-11e9-9c89-14d14f4aa9d0.png)

![image](https://user-images.githubusercontent.com/2313005/61853983-6e0e6580-aebd-11e9-95aa-35dea413dc99.png)

Or can you @hamsa95 maybe recommend some other Vue/React plugin if you have done similiar things? Thank's alot

**Comment by Laykou** [comment]
Or maybe @dylanvorster could help to answer this please?

**Comment by maxtsh** [comment]
@Laykou any solution on this ?

**Comment by Laykou** [comment]
Unfortunatelly no :/
