### ISSUE TITLE
Pass extraProps to port

### ISSUE THREAD

**Issue by bknill** [projectstorm/react-diagrams#314]
Hi, 

I've got some dynamic ports on the node that are generated with the same name. 

I'm trying to pass a variable so I can store the data when this port is linked. 

I can see there is an extraProps attribute, which I'm using to add the variable, however on the Port Changed event I can't find this data. 

`<PortWidget extraProps={{choiceid:choice.id}} className={'point'} name="choice" node={this.props.node} />`

Is there an easy way to get this?

**Comment by dylanvorster** [comment]
You can now do this with a custom port, along with a custom port model: https://projectstorm.gitbook.io/react-diagrams/customizing/ports
