### ISSUE TITLE
problem with offset

### ISSUE THREAD

**Issue by gen4sp** [projectstorm/react-diagrams#32]
I've placed SRD with little offset and moving event now is broken.
I've tried to fix it with this code, but it didn't workout. 
```
DiagramWodget:345
var relative = diagramEngine.getRelativePoint(event.pageX + diagramModel.getOffsetX(), event.pageY + diagramModel.getOffsetY()); //here
diagramModel.clearSelection();
this.startFiringAction(new MoveCanvasAction(relative.x, relative.y, diagramModel));
```

Give me a hint and I'll fix it
http://take.ms/61vkV

**Comment by dylanvorster** [comment]
will have a look at this shortly, its probably because of

https://github.com/projectstorm/react-diagrams/blob/master/src/DiagramEngine.ts#L185

specifically: 

https://github.com/projectstorm/react-diagrams/blob/master/src/DiagramEngine.ts#L187

I'll do some investigation

**Comment by gen4sp** [comment]
Hey @dylanvorster, any updates here or with next version?

**Comment by dylanvorster** [comment]
still nothing yet, haven't actually had time to look at it yet... but i promise I'm going to sort it out.

**Comment by dylanvorster** [comment]
busy looking at it, also busy with a new demo and fix

**Comment by dylanvorster** [comment]
also see that there is a new demo (demo 5). Im going to build this into a much larger demo that has droppable nodes (much like in my own program) as well as property viewers etc..

**Comment by gen4sp** [comment]
@dylanvorster perfect. Just exactly what I need.
But I would say, group are more important.
<img width="1386" alt="screen shot 2017-04-11 at 11 37 40" src="https://cloud.githubusercontent.com/assets/4303628/24900150/85e9a39e-1eab-11e7-81ce-2ded1d4a6c9b.png">

**Comment by dylanvorster** [comment]
Im sure it is xD its just a bit more complicated to implement :P
