### ISSUE TITLE
Generate node having input and output

### ISSUE THREAD

**Issue by Harshmakadia** [projectstorm/react-diagrams#320]
Hello I was looking for a node which has both input and output as shown in the image of the repo 

Please find the attached image below

<img width="166" alt="screenshot 2019-02-18 at 10 01 57 pm" src="https://user-images.githubusercontent.com/13532530/52964734-0f523680-33c9-11e9-9695-1576985c18ac.png">

How can I generate this? I mean what **_type_** should I specify?

**Comment by wader** [comment]
With `DefaultNodeModel` i think you can use `addInPort()` and `addOutPort ` and then `DefaultNodeWidget` will render it similar to your image if it was both in and out ports.

**Comment by Harshmakadia** [comment]
Thanks, @wader this worked! closing this.
