### ISSUE TITLE
Connecting links and custom node I/O

### ISSUE THREAD

**Issue by torbgy** [projectstorm/react-diagrams#321]
Hi,

Just have a quick question: Is it possible to connect links together like the figure below?

![nodeex](https://user-images.githubusercontent.com/10559455/53019557-4bcb7400-3455-11e9-9c53-6398442d408b.png)

And is it possible to specify link connection points on nodes? i.e. ignore in/out and accept all connecitons?

![customio](https://user-images.githubusercontent.com/10559455/53019574-52f28200-3455-11e9-9b10-0a0e1ba41827.png)

**Comment by JokerNN** [comment]
For the second one: it is definitely possible.

For the first one formal answer is no, there's no way to connect links. However I think it is easy to mimic with having connector node which will look like small dot, but have the same functionality as proper node.

**Comment by torbgy** [comment]
@JokerNN , thanks for the response!

so for the first one: Maybe make a custom node that can be connected like a small black circle as shown in the figure? I'll see what I manage to do.

**Comment by torbgy** [comment]
closing the issue, in regards to response
