### ISSUE TITLE
Remove created link if it is not connected to any node

### ISSUE THREAD

**Issue by josephjesseyoung** [projectstorm/react-diagrams#322]
Hi there, kudos to the devs for this amazing lib.

I'm wondering how to remove link if it is not connected to any node. Is there any way to modify the link after it is created (when you are finished dragging the link / stop holding the mouse click)?. It seems all the available function related to link gets fired directly when creating a link by dragging the port for the first time.

Any insight is appreciated!!

**Comment by Nijooke** [comment]
Hey, maybe the allowLooseLinks props for DiagramWidget may help you ?
`<DiagramWidget
      css={css`
        background-color: #000;
        height: 100vh;
      `}
      diagramEngine={engine}
      allowLooseLinks={true}
    />`

**Comment by josephjesseyoung** [comment]
Oh right, I missed that props. Thankyou very much!

**Comment by BrunoQuaresma** [comment]
I tried using `import { CanvasWidget } from '@projectstorm/react-canvas-core'` but this prop is not recognize.

**Comment by Yaroslav-Melnychenko** [comment]
> I tried using `import { CanvasWidget } from '@projectstorm/react-canvas-core'` but this prop is not recognize.

Have the same issue

**Comment by Yaroslav-Melnychenko** [comment]
> I tried using `import { CanvasWidget } from '@projectstorm/react-canvas-core'` but this prop is not recognize.

Try this, when creating an engine 
const state = engine.getStateMachine().getCurrentState();
if (state instanceof DefaultDiagramState) {
    state.dragNewLink.config.allowLooseLinks = false;
}

**Comment by Hkbm77** [comment]
@Yaroslav-Melnychenko The above config to set allowLooseLink to false doesn't work properly, we are also trying the same like one you mentioned but it is so sporadic that if we are trying to extend the link from the ports for 3-4 times the react-diagram is allowing the loose links.

   if (state instanceof DefaultDiagramState) {
      state.dragNewLink.config.allowLooseLinks = false;
    }

**Comment by erfoon** [comment]
Probably there is no good way to fix it natively, I wrote this function and called it `onMouseUp`

```
  const removeLooseLinks = () => {
    const model = diagramEngine.getModel()
    const links = model?.activeLinkLayer?.models
    Object.values(links).map((value) => {
      if (value.sourcePort === null || value.targetPort === null) {
        model.removeLink(value)
      }
    })
  }
```
