### ISSUE TITLE
Can't get Storm react diagrams to work

### ISSUE THREAD

**Issue by Nijooke** [projectstorm/react-diagrams#323]
Hi there,

My link is not displayed and I don't know why :/

![image](https://user-images.githubusercontent.com/16818361/53110358-0a14f900-353b-11e9-90b5-246babe6ae8d.png)

Here is my code : 

```
    this.engine = new DiagramEngine();

    this.engine.registerNodeFactory(new DefaultNodeFactory());
    this.engine.registerLinkFactory(new DefaultLinkFactory());

    const model = new DiagramModel();

    const node1 = new DefaultNodeModel("Node 1", "rgb(0,192,255)");
    const port1 = node1.addPort(new DefaultPortModel(false, "out-1", "Out"));
    node1.x = 100;
    node1.y = 100;

    const node2 = new DefaultNodeModel("Node 2", "rgb(192,255,0)");
    const port2 = node2.addPort(new DefaultPortModel(true, "in-1", "IN"));
    node2.x = 400;
    node2.y = 100;

    const link1 = new LinkModel();
    link1.setSourcePort(port1);
    link1.setTargetPort(port2);

    model.addNode(node1);
    model.addNode(node2);
    model.addLink(link1);

    this.engine.setDiagramModel(model);


  render() {
    return ( <DiagramWidget
      css={css`
        background-color: #f5f5f5;
        height: 100vh;
      `}
      diagramEngine={engine}
    />)
}
```

**Comment by top4e** [comment]
![sd_links_issue](https://user-images.githubusercontent.com/386395/53173220-e8c21480-35ef-11e9-94fa-71f71d00c129.png)

 I have similar (possibly the same) issue. I see links displayed, but out of place (see screenshot). Although links are OK when created with mouse. Issue was not observed with previous installation I have from few weeks ago.

**Comment by top4e** [comment]
Reverting to react@16.7.0 react-dom@16.7.0 and react-scripts@2.1.3 fixed the issue for me

**Comment by Nijooke** [comment]
Strangely, I don't have this problem in production, when I serve a build. I'll try your answer @top4e

**Comment by goosecoid** [comment]
> Reverting to react@16.7.0 react-dom@16.7.0 and react-scripts@2.1.3 fixed the issue for me
Unfornately for me, the problem still persists after downgrading.

**Comment by erindru** [comment]
I had the same issue as top4e (with regards to predefined links not rendering correctly) and reverting react / react-dom worked for me
