### ISSUE TITLE
Changing link color

### ISSUE THREAD

**Issue by ianchanning** [projectstorm/react-diagrams#325]
I've got the various examples working nicely, thank you for this excellent project.

However I wanted to change the colour of the links. Conceptually this seems like a relatively simple idea, but it seems that I need to almost fully implement the [custom animated links][1] example to change the colour. 

I'm sure I can get this to work - but I was wondering if there is a simpler way?

[1]: http://projectstorm.cloud/react-diagrams/?selectedKind=Custom%20Models&selectedStory=Custom%20animated%20links&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Fcode%2Fpanel

**Comment by ianchanning** [comment]
This is the simplest that I could come up with, effectively re-creating the `DefaultLinkModel` `generateLinkSegment`:

```javascript
class AdvancedLinkModel extends DefaultLinkModel {

  constructor() {
    super('advanced');
    this.color = 'rgba(0,0,0,0.5)';
  }

}

class AdvancedPortModel extends DefaultPortModel {

  createLinkModel(): AdvancedLinkModel | null {
    return new AdvancedLinkModel();
  }

}

class AdvancedLinkFactory extends DefaultLinkFactory {

  constructor() {
    super();
    this.type = 'advanced';
  }

  getNewInstance(): AdvancedLinkModel {
    return new AdvancedLinkModel();
  }

  generateLinkSegment(model: AdvancedLinkModel, widget: DefaultLinkWidget, selected: boolean, path: string) {
    return (
      <path
        className={selected ? widget.bem('--path-selected') : ''}
        strokeWidth={model.width}
        stroke={model.color}
        d={path}
      />
    );
  }

}
```

**Comment by dailinyi** [comment]
`const link = outputPoint.link(inputPort);
  link.setColor('#123456');
  model.addLink(link);
`
isn't ok?

**Comment by ianchanning** [comment]
@dailinyi That is auto generating the links but I want users to be able to drag and drop links themselves

**Comment by PikkaPikkachu** [comment]
Same question, is there a simple css way to change the color?

**Comment by ianchanning** [comment]
@PikkaPikkachu I'm pretty sure the answer is no. This library seems to work around the idea of just creating a new object/class to extend the functionality rather than config.

**Comment by PikkaPikkachu** [comment]
@ianchanning I guess your solution to recreating the DefaultLinkModel class is the best, thanks!!

**Comment by dylanvorster** [comment]
You can also just change this: https://github.com/projectstorm/react-diagrams/blob/2df09edb7e5716a68884ed6d68faa78068003f52/src/sass/defaults/_DefaultLinkWidget.scss#L18

**Comment by dylanvorster** [comment]
But I will split out the defaults as a separate Lerna project

**Comment by magnafilix** [comment]
> This is the simplest that I could come up with, effectively re-creating the `DefaultLinkModel` `generateLinkSegment`:
> 
> ```js
> class AdvancedLinkModel extends DefaultLinkModel {
> 
>   constructor() {
>     super('advanced');
>     this.color = 'rgba(0,0,0,0.5)';
>   }
> 
> }
> 
> class AdvancedPortModel extends DefaultPortModel {
> 
>   createLinkModel(): AdvancedLinkModel | null {
>     return new AdvancedLinkModel();
>   }
> 
> }
> 
> class AdvancedLinkFactory extends DefaultLinkFactory {
> 
>   constructor() {
>     super();
>     this.type = 'advanced';
>   }
> 
>   getNewInstance(): AdvancedLinkModel {
>     return new AdvancedLinkModel();
>   }
> 
>   generateLinkSegment(model: AdvancedLinkModel, widget: DefaultLinkWidget, selected: boolean, path: string) {
>     return (
>       <path
>         className={selected ? widget.bem('--path-selected') : ''}
>         strokeWidth={model.width}
>         stroke={model.color}
>         d={path}
>       />
>     );
>   }
> 
> }
> ```

@ianchanning , did you run into [this](https://github.com/projectstorm/react-diagrams/issues/440) issue when were instantiating `AdvancedLinkFactory`?

**Comment by RebeccaRol** [comment]
There is a css way - Add this scss changing stroke to whatever colour you want 

`.srd-diagram {
    .srd-default-link {
      path {
        stroke: #000;
      }

      &--path-selected{
        stroke: #000;
      }
    }
  }`

**Comment by brunojennrich** [comment]
let link = p.createLinkModel();
  link.setSourcePort(p);
  link.setTargetPort(n);
  link.options.color="#ff00ff";

works for me

<img width="291" alt="image" src="https://user-images.githubusercontent.com/2224055/156175804-7ee258fc-3e1b-47b8-8b3d-67253a2b7f74.png">
