### ISSUE TITLE
Link not visible behind the node

### ISSUE THREAD

**Issue by ethorz** [projectstorm/react-diagrams#327]
Hi,

On diagram initialize, i set nodes & links programmatically. If the node is connected to itself, the link is not visible behind the node. Prop smartRouting not help. 

Thanks

**Comment by dylanvorster** [comment]
If you really need this feature, you can now do this by using the layers inside the CanvasModel and either a) re-arrange them in a different order (could previously not do this in version 5) or you can using something like Dagre (now with first class support in version 6) to achieve this.
