### ISSUE TITLE
Link labels hide after pan diagram

### ISSUE THREAD

**Issue by lstaszewski** [projectstorm/react-diagrams#328]
Video presents this bug.

https://drive.google.com/a/inteliwise.com/file/d/1kyEzCbvmuY25Ya3oVEwp70PSMwGaQfkZ/view?usp=drivesdk

**Comment by purplesquirrels** [comment]
I am also experiencing this issue. Appears to be cutting off at the edge of the link layer svg:

![image](https://user-images.githubusercontent.com/4001667/53618032-d4a89380-3c3d-11e9-84eb-719fd9c66f32.png)

**Comment by lstaszewski** [comment]
foreignObject `overflow: visible`

**Comment by purplesquirrels** [comment]
I fixed it by adding:
`.srd-default-link__label {
        overflow: visible;
}`

**Comment by peterbozso** [comment]
@purplesquirrels you are my personal hero today.

**Comment by dylanvorster** [comment]
Also fixed in the new system
