### ISSUE TITLE
onFocus / onBlur

### ISSUE THREAD

**Issue by ajboni** [projectstorm/react-diagrams#334]
Hi! is it possible to have a proper onFocus/onBlur behaviour?
Its basically to avoid the annoying delete keys behavior like #211  and #57 but still rkeep the functionality when component is in focus...

something like this 

```
deleteKeys=this.state.focused ? [54] : []
```

**Comment by dylanvorster** [comment]
This can be solved now by injecting your own States into the state machine or actions into the ActionEventBus. In a nutshell, its no longer part of the core, and so you can even go as far as remove the functionality entirely if you want. Take a look at this line: https://github.com/projectstorm/react-diagrams/blob/23b174736c1858fa2ee5899505454bf1a408e1a7/packages/react-canvas-core/src/CanvasEngine.ts#L40
