### ISSUE TITLE
how can I edit the 'link' label value?

### ISSUE THREAD

**Issue by victoria100** [projectstorm/react-diagrams#337]
Hi, 

The plan is like this;
1.  Click the 'link' then a dialog will pop up on the 'link'
2. you can write label value then save it 
3. then the label is showing up on the 'link'. 
4. Click the 'link' again, the dialog will pop up on the 'link' again with saved label name.
5. you can edit the label value or delete it.

I  added the label value with link.addLabel("value"). 

However, I couldn't find edit label and delete label function. 
Could you please give some idea?

**Comment by PikkaPikkachu** [comment]
@victoria100 were you able to achieve this? I wish to do something similar.
