### ISSUE TITLE
Upgrading from v4.0.0 to v5.2.1 Errors GUI Not Rendering

### ISSUE THREAD

**Issue by AustinMutschler** [projectstorm/react-diagrams#338]
I have read the release notes and the changelogs but cannot find a place where Breaking Changes are documented. Could someone clear up exactly what we need to change in our code to go from v4 to v5.2.1?

Update:

I got past my original errors by changing all Factory's to Abstract Factories; however, now when I go to my grid GUI I can see that the node are rendering in React with Chrome Dev Tools; however, the grid is just white and doesn't display the GUI. Any help would be very much appreciated.

**Comment by dylanvorster** [comment]
This was a failure on my part, I simply didn't have time for this (and apologise :( ). I hope you came right. Don't think I'm going to be able to go back more than a year to find out what broke.

**Comment by AustinMutschler** [comment]
@dylanvorster Thanks for the help. I was able to figure out most of it.
