### ISSUE TITLE
[HELP] Is there a way to display 'label' on the 'link' on IE11? 

### ISSUE THREAD

**Issue by victoria100** [projectstorm/react-diagrams#339]
Hi, 
Is there a way to display 'label' on the 'link' on IE11? Do you still not support IE11? 
I saw #93 looks not support IE11. 
I tried to test. I can create Node but can't create 'link' from node to node. 
and I can't see 'label' on the 'link' 

Is there a way? 

Thanks

**Comment by dylanvorster** [comment]
Nope, IE11 is trash.
