### ISSUE TITLE
How can I add class to the DefaultNodeModel?

### ISSUE THREAD

**Issue by zaferkaymak** [projectstorm/react-diagrams#342]
I want to add a class for each node type,

node = new DefaultNodeModel(v.name, v.color);
node.id = v.id;

I can change the ID and position value. But How can I add a class for each node?

**Comment by JokerNN** [comment]
You can inherit default class and then implement any logic you want in render method

**Comment by dylanvorster** [comment]
@JokerNN dont think I dont notice your replies :3 I may have seemed like I disappeared off the face of the earth, but its still super rewarding seeing you reply \:D/
