### ISSUE TITLE
Weird connection issue

### ISSUE THREAD

**Issue by deltakosh** [projectstorm/react-diagrams#344]
Hey team! First I want to say that I LOVE react-diagram :)

We are using it for our upcoming Babylon.js Node Material editor
You can find a demo here (just click the edit button): https://www.babylonjs-playground.com/full.html#X0WKQ8#2

It works very well. The only problem is that connections seem off sometimes:
![image](https://user-images.githubusercontent.com/1306056/58347923-f87e0e80-7e13-11e9-9c7f-6d0a78750d95.png)

I'm not sure what we are doing wrong.

Can you guys help?

The relevant code is here:
https://github.com/BabylonJS/Babylon.js/tree/master/nodeEditor/src/components/diagram

**Comment by deltakosh** [comment]
We actually figured out a way by creating all the links with only one call to addAll()

thanks folks!

**Comment by mecirmartin** [comment]
@deltakosh Hey, i have similar issue #902. I basically just instantiated DefaultNode with some styling
How could i fix this misalignment?
