### ISSUE TITLE
Add ability to mark a node as "cannot be deleted"

### ISSUE THREAD

**Issue by deltakosh** [projectstorm/react-diagrams#348]
Thanks :)

**Comment by deltakosh** [comment]
By the way I would be happy to do a PR for that. Are you open to external contributors?

**Comment by dylanvorster** [comment]
1. I think this is implemented: https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/BaseEntity.ts#L24

2. This can also be done by extending the base nodes
