### ISSUE TITLE
Find the port or node coordinates on screen 

### ISSUE THREAD

**Issue by PikkaPikkachu** [projectstorm/react-diagrams#352]
Is there a way to fetch the node or port coordinates in the diagram?

**Comment by JokerNN** [comment]
I think the only way is to filter all the nodes by their coords, Im not sure if it scales well for your case

**Comment by PikkaPikkachu** [comment]
Does filtering allow me to find out the exact coordinates? I wish to find the coordinates for fixing some points on the link?

**Comment by JokerNN** [comment]
I guess `model.x` and `model.y` should contain x and y for node. I didn't try it by myself though.

But here it is in sources: https://github.com/projectstorm/react-diagrams/blob/master/src/models/NodeModel.ts#L14

**Comment by PikkaPikkachu** [comment]
I am using dagre to automatically distribute the graph, so the coordinates are being decided automatically. I am getting a value of (0,0) when I console log the value of node.x and node.y.

**Comment by JokerNN** [comment]
`I am getting a value of (0,0)` - this shouldn't happen, I just tried with dagre demo in storybook `engine.getDiagramModel().nodes` . Nodes contained proper coords

**Comment by PikkaPikkachu** [comment]
Thanks @JokerNN, I forgot to reference the engine while trying to get the nodes' coordinates, this seems to work!
