### ISSUE TITLE
Render a curved link, instead of straight one?

### ISSUE THREAD

**Issue by PikkaPikkachu** [projectstorm/react-diagrams#353]
Is there a way to render custom curved links, instead of straight ones? Any suggestions on how to proceed with this are welcomed ! Thanks !

**Comment by PikkaPikkachu** [comment]
I found that this [class](https://github.com/projectstorm/react-diagrams/blob/master/src/defaults/widgets/DefaultLinkWidget.tsx) has a function that defines the path of link, can this class be custom defined? I would like to render a beizer curve for the path of the link.

**Comment by dylanvorster** [comment]
You can do this by following this example: https://projectstorm.gitbook.io/react-diagrams/customizing/extending-default-links
