### ISSUE TITLE
Need the model used for multiple ports in the GitHub landing page

### ISSUE THREAD

**Issue by abhijitnandy2011** [projectstorm/react-diagrams#357]
Are the models used for https://github.com/projectstorm/react-diagrams/blob/master/images/example1.jpg available somewhere in this repo?

**Comment by HarunOr** [comment]
AFAIK no, you have to recreate it yourself.

**Comment by dudenamedjune** [comment]
I also asked in gitter, unfortunately no response :(

**Comment by dylanvorster** [comment]
If I got a dolalr everytime someone asked me this x_x. I might actually make them available
