### ISSUE TITLE
Cannot start storybook 

### ISSUE THREAD

**Issue by azizmuradovar** [projectstorm/react-diagrams#358]
My steps 
1) clone repo
2) yarn install
3) yarn run storybook

ERROR in [at-loader] ./src/models/NodeModel.ts:59:6
    TS2345: Argument of type 'PointModel[]' is not assignable to parameter of type 'BaseModel<any, T> | ConcatArray<BaseModel<any, T>>'.
  Type 'PointModel[]' is not assignable to type 'ConcatArray<BaseModel<any, T>>'.
    Types of property 'slice' are incompatible.
      Type '(start?: number, end?: number) => PointModel[]' is not assignable to type '(start?: number, end?: number) => BaseModel<any, T>[]'.
        Type 'PointModel[]' is not assignable to type 'BaseModel<any, T>[]'.
          Type 'PointModel' is not assignable to type 'BaseModel<any, T>'.
            Types of property 'getSelectedEntities' are incompatible.
              Type '() => PointModel[]' is not assignable to type '() => BaseModel<any, T>[]'.
                Type 'PointModel[]' is not assignable to type 'BaseModel<any, T>[]'.

**Comment by ej-santoemma** [comment]
I've checked out v5.2.1 to make it work

**Comment by azizmuradovar** [comment]
Why do I have such a problem?

**Comment by frank-martinez-27** [comment]
I created a PR to fix this issue and it was merged recently. Do a hit pull of the latest version of the library and if it works close this issue :)

**Comment by dylanvorster** [comment]
should be working in 6.0 now (please re-open if it doesn't)
