### ISSUE TITLE
Why does getPortCoords calculate coords differently than some other methods?

### ISSUE THREAD

**Issue by pero5ar** [projectstorm/react-diagrams#359]
#### Why does `getPortCoords` calculate coords differently than `getPortCenter` or `getRelativeMousePoint`?

In `getPortCoords` the canvas rectangle offsets get subtracted from the value after the value has been divided by the zoom level

https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/DiagramEngine.ts#L333-L338

while some other coordinate calculating methods, such as `getPortCenter` and `getRelativeMousePoint` use the method `getRelativePoint` to subtract the canvas rectangle offsets first and then divide the value by the zoom level.

https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/DiagramEngine.ts#L274

https://github.com/projectstorm/react-diagrams/blob/5b142c1c6136eff75b81a819b4b73de644c307ab/src/DiagramEngine.ts#L305-L314

Do these coords represent values in a different coord system and therefore the calculation is different, or is this a bug?

**Comment by dylanvorster** [comment]
Not sure if this is still valid, but I re-architected this in the new 6.0 version
