### ISSUE TITLE
Question on editing properties of Node/ Port Models

### ISSUE THREAD

**Issue by kriskrss** [projectstorm/react-diagrams#36]
Hey dylanvoster,

Firstly, huge thanks for creating this awesome project. This is really helpful for usecases dealing with flows.

I have an issue that I am unable to figure out how to solve.

I am building a flow-builder tool and I want to provide users the ability to change port/node properties on the fly. Is there a way to do this without re-rendering the whole model?

Problem is that when I change the title of the node by directly mutating the digramModel, the link gets deleted.

So I save the links' state and re-render the whole model and add all the links back again for editing to work seemlessly. 

Want to check if there is an easier way to do this.

<img width="1335" alt="screen shot 2017-03-30 at 3 31 47 pm" src="https://cloud.githubusercontent.com/assets/4058633/24529069/6567514e-155e-11e7-8605-61aa64398b4a.png">

<img width="1341" alt="screen shot 2017-03-30 at 3 32 10 pm" src="https://cloud.githubusercontent.com/assets/4058633/24529023/2405c32a-155e-11e7-94f1-1448b59a99fc.png">

<img width="1333" alt="screen shot 2017-03-30 at 3 32 18 pm" src="https://cloud.githubusercontent.com/assets/4058633/24529024/24180756-155e-11e7-8154-419259cbf759.png">

Thanks,
Sai.

**Comment by dylanvorster** [comment]
Hey, thanks for reaching out! mind jumping onto bitter quickly?

**Comment by dylanvorster** [comment]
its really strange that the links are getting deleted. The only time the system will delete the links, is if the ports happen to change, and so the links can no longer be connected. So I'm concerned that the model you are mutating is not the same model that the diagram engine is using. You should DEFINITELY be able to mutate the model and then repaint. You can also control what gets repainted down the whole tree by calling:

```typescript
//first call this and pass in an array of models that you want to change
diagramEngine.enableRepaintEntities(entities: BaseModel<BaseModelListener>[]);

//then
diagramEngine.repaintCanvas() or forceUpdate in your wrapper component

//and then finally
diagramEngine.clearRepaintEntities();
```

**Comment by dylanvorster** [comment]
to find out why the links are being deleted, take a look at this line:

https://github.com/projectstorm/react-diagrams/blob/master/src/widgets/LinkLayerWidget.ts#L49

as well as

https://github.com/projectstorm/react-diagrams/blob/master/src/widgets/LinkLayerWidget.ts#L60

**Comment by dylanvorster** [comment]
lastly, theres another cool guy thats using this project and is doing something similar, but he added text fields to the nodes themselves, for an example on how he is doing it you might find this interesting:

https://github.com/mwozniczak/adventure-weave/blob/master/src/widgets/SceneNodeWidget.tsx#L51

**Comment by mwozniczak** [comment]
Yeah, I was just about gonna jump in here and toot my own horn for a minute there\*, you beat me to it :D

@kriskrss you might wanna look at what @dylanvorster linked to, in particular what I'm doing with the composites.

Anyway, a potential workaround if the above doesn't work for you, might be have the title a new property of your NodeModel, and just render _that_ in the widget.

\*jeez i hope this is the right expression

**Comment by kriskrss** [comment]
Thanks for the quick response!, I am building a redux app around this. So trying to make sure the model transitions also go through the redux dispatcher-reducer framework.

I was storing the model in my state and re-drawing on a new engine every time.

From what you guys mentioned, may be its better to just store the engine instead.

Thanks guys!

**Comment by dylanvorster** [comment]
Can I close this issue?

**Comment by kriskrss** [comment]
Sure, I can create another one if I find that this is a bug :)
