### ISSUE TITLE
Zoom-In and Zoom-Out events for DiagramEngine

### ISSUE THREAD

**Issue by pmehta18** [projectstorm/react-diagrams#361]
Can anybody tell me how we can manage zoom-in & zoom-out events explicitly?
For example, if I want to zoom-in the engine on the click of button instead of using the mouse wheel?

Thanks in advance.

**Comment by wstuckey** [comment]
I second this question, I have been trying to figure this out for awhile now.

**Comment by pmehta18** [comment]
@wstuckey You can take reference from below snippet which I tried and see if it helps.
`let scaleFactor = 1;
function zoomIn() {
        scaleFactor += (-10 * -0.01);
        scaleFactor = Math.min(Math.max(.125, scaleFactor), 1.5);
        this.customRef.style.transform = `scale(${scaleFactor})`;
    }

    function zoomOut() {
        scaleFactor += (10 * -0.01);
        scaleFactor = Math.min(Math.max(.125, scaleFactor), 1.5);
        this.scaleFactor = Math.max(this.scaleFactor, 0.5);
        this.customRef.style.transform = `scale(${scaleFactor})`;
    }`

**Comment by dylanvorster** [comment]
to change the zoom:

https://github.com/projectstorm/react-diagrams/blob/2df09edb7e5716a68884ed6d68faa78068003f52/src/widgets/DiagramWidget.tsx#L451

To respond to zoom:

https://github.com/projectstorm/react-diagrams/blob/2df09edb7e5716a68884ed6d68faa78068003f52/src/models/DiagramModel.ts#L20

**Comment by JitendraBhamidipati** [comment]
@dylanvorster I am trying to set the zoom with dropdown. It was not working for me in 6.0.2 version.

engine.model.setZoomLevel(25)

**Comment by renato-bohler** [comment]
@JitendraBhamidipati you mean something like that?

![image](https://user-images.githubusercontent.com/25781956/80236003-dba81780-8630-11ea-9293-c5cd7ebb137c.png)

I've implemented this on my project ([logossim](https://github.com/renato-bohler/logossim)). You can try it out [here](https://renato-bohler.github.io/logossim/).

And [here's the code](https://github.com/renato-bohler/logossim/blob/5902c9198c8b8665609ee04b0d9fe7ea35b102b1/packages/%40logossim/core/Diagram/DiagramEngine.js#L286-L300) for the functions that handles these dropdown items. Basically, it calls `engine.getActionEventBus().fireAction` with some specific paramaters.
