### ISSUE TITLE
Error: <circle> attribute cx: Expected length, "501.123885270003…

### ISSUE THREAD

**Issue by PikkaPikkachu** [projectstorm/react-diagrams#363]
Hi, when I am trying to modify the points on links I have created, I get the following error.
```
Error: <path> attribute d: Unexpected end of attribute. Expected number, "….350650493915250"
Error: <circle> attribute cy: Expected length, "149.350650493915…".
```
Any clues as to why this is happening?

**Comment by zHaytam** [comment]
Hello! How did you fix this?

**Comment by PikkaPikkachu** [comment]
It's been a long time, since I worked on the project, but AFAIR it was to do with the data type of the point I was using, I was using string data type for storing numbers. Hope this helps!
