### ISSUE TITLE
How can I render custom DiagramModel? 

### ISSUE THREAD

**Issue by PikkaPikkachu** [projectstorm/react-diagrams#365]
Hi, 

I have been successfully able to implement custom nodes and links and was wondering, if it is possible to implement a default DiagramModel? I wish to add some new attributes to the class. Or is there a simpler way to do so?

Thanks.

**Comment by dylanvorster** [comment]
This is supposed to be governed via the factories which create the new models for each node. https://github.com/projectstorm/react-diagrams/blob/2df09edb7e5716a68884ed6d68faa78068003f52/demos/demo-custom-node1/DiamondNodeFactory.tsx#L15
