### ISSUE TITLE
Movement is not working correctly with smartRouting

### ISSUE THREAD

**Issue by dudenamedjune** [projectstorm/react-diagrams#368]
<img width="850" alt="Screen Shot 2019-07-18 at 4 54 37 PM" src="https://user-images.githubusercontent.com/8673104/61494792-c5bc4680-a97c-11e9-86de-c7335e234237.png">

Steps to reproduce

1. In the large app demo set the property smartRouting on DiagramWidget to true 
2. delete all of the nodes and links
3. create new node from sidebar
4. console shows error and movement is laggy

**Comment by frank-martinez-27** [comment]
Refer to the following issue, the answer is there: https://github.com/projectstorm/react-diagrams/issues/214

**Comment by dylanvorster** [comment]
Fixed (afaik)
