### ISSUE TITLE
Typescript is not compiled in npm distribution

### ISSUE THREAD

**Issue by solussd** [projectstorm/react-diagrams#37]
The prepublishOnly script is executed after tarball creation. I think Webpack needs to run as part of the "prepare" script. 

The npm package might work in projects that have a webpack loader for typescript, but that is suboptimal because it requires the library consumer to manually satisfy the libraries dev dependencies.

**Comment by dylanvorster** [comment]
Hey man can you jump onto the Gitter chat quick

**Comment by dylanvorster** [comment]
the problem was that it was missing a .npmignore, I was not aware that the dist folder was not being bundled, thanks for pointing it out!

**Comment by solussd** [comment]
Awesome. Thanks for fixing so quick!

**Comment by dylanvorster** [comment]
pleasure :)
