### ISSUE TITLE
Missing code in storybook (demo)

### ISSUE THREAD

**Issue by mitsol** [projectstorm/react-diagrams#372]
Hi! Trying to check the demo on http://projectstorm.cloud/react-diagrams I could not find the source code of the examples anymore.

**Comment by matthax** [comment]
https://github.com/projectstorm/react-diagrams/tree/master/demos

**Comment by dylanvorster** [comment]
https://github.com/projectstorm/react-diagrams/tree/master/packages/diagrams-demo-gallery/demos
