### ISSUE TITLE
Simple example not displaying correctly

### ISSUE THREAD

**Issue by psleal** [projectstorm/react-diagrams#378]
Hello,

I created a new React app and installed this module through yarn, then used the demo-simple example given on the demos folder just to see a quick graph. Running this gave me the following result:

![image](https://user-images.githubusercontent.com/8961852/62011628-01c08a00-b17b-11e9-9846-247445ae8016.png)

Is this a missing css problem, or am I missing something? I can only move the whole diagram around, not the separate nodes.

Thanks

**Comment by alex-enchi** [comment]
Hi, try to check #228 
You're missing styles for diagram

**Comment by psleal** [comment]
Thank you! 

That worked so far as it made everything blank, which then led me to #347 and after setting width, height and background color, it's working as it should.
