### ISSUE TITLE
DiagramWidget always gets height of 0

### ISSUE THREAD

**Issue by solussd** [projectstorm/react-diagrams#38]
I'm rendering the DiagramWidget in a subtree of my React view (i.e., not the top level component) and, no matter what width/height styles I apply to its container it always has a height of 0. If I explicitly specify a min-height from the browser inspector, it renders correctly.

Its styling is specified in the storm-diagrams-canvas css class. Would it make sense to allow inline styling of this component? Am I missing something obvious?

**Comment by dylanvorster** [comment]
Hi there

take a look at 
https://github.com/projectstorm/react-diagrams/issues/21#issuecomment-288198766

**Comment by dylanvorster** [comment]
Basically you are not applying the css correctly

**Comment by solussd** [comment]
Thanks. I was missing "display: flex" on the parent.

**Comment by solussd** [comment]
I can't seem to drag individual nodes (but I can drag the canvas). Is node dragging something I must implement by explicitly setting x and y on the node widgets?

**Comment by dylanvorster** [comment]
can u jump onto glitter chat quickly

**Comment by dylanvorster** [comment]
https://gitter.im/projectstorm/react-diagrams

**Comment by solussd** [comment]
Sorry- away from the computer for the next few hours.

**Comment by dylanvorster** [comment]
kk, but it should be enabled by default. Check that you have the latest version, because I recently fixed a bug that related to this issue. Locks on the model are always disabled by default.
