### ISSUE TITLE
.bem method explanation

### ISSUE THREAD

**Issue by mathiasbaldissera** [projectstorm/react-diagrams#381]
In the whole project, there are such `.bem(-somecssclass)` in classNames, but i can't figure what this method do, and how to declare the className in the css file. Somebody can helpme?

**Comment by zacharyzhy** [comment]
The method is defined in [BaseWidget](https://github.com/projectstorm/react-diagrams/blob/master/src/widgets/BaseWidget.tsx#L28), basically it appends the `selector` to the className defined in specific widgets. For example, the className for DefaultNodeWidget is `srd-default-node`, and the title div using `this.bem("__title")` ended up being `srd-default-node__title`

**Comment by zacharyzhy** [comment]
BEM http://getbem.com/

**Comment by mathiasbaldissera** [comment]
Oh, now everything makes sense.
Thanks man ^^
