### ISSUE TITLE
Demos are different.

### ISSUE THREAD

**Issue by HoosLab** [projectstorm/react-diagrams#383]
Hi~!
Before speaking, thanks for making this `NICE` library.
I found differences between "Run the demos" by yarn run storybooks And Demo Site Link "http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--simple-example".

Differences I found were two things.
1. Only Demo site link have Dynamic ports example.
2. Links behavior(curviness) differ from demo site link. (demo site link's curvy is more natural.)

Please check these differences. I'll wait for your response!

**Comment by dylanvorster** [comment]
This was because of the Lerna branch I was busy working on, version 6 Beta is now in master and correctly reflects the demos that were deployed.
