### ISSUE TITLE
Module not found: Can't resolve 'closest' in dist/main.js

### ISSUE THREAD

**Issue by flomllr** [projectstorm/react-diagrams#386]
Hey, 
I am trying to integrate the simple example into my existing react app. But as soon as I install the latest version (5.3.2) via npm, add the code from the example and run npm start, the following error occurs:
```
./node_modules/@projectstorm/react-diagrams/dist/main.js
Module not found: Can't resolve 'closest' in 'node_modules\@projectstorm\react-diagrams\dist'
```

Here is my code for reference (copied from demos/demo-simple/index.tsx)
```javascript
import {
  DiagramEngine,
  DiagramModel,
  DefaultNodeModel,
  LinkModel,
  DiagramWidget,
  DefaultLinkModel
} from '@projectstorm/react-diagrams';
import * as React from 'react';

export default () => {
  // 1) setup the diagram engine
  const engine = new DiagramEngine();
  engine.installDefaultFactories();

  // 2) setup the diagram model
  const model = new DiagramModel();

  // 3-A) create a default node
  const node1 = new DefaultNodeModel('Node 1', 'rgb(0,192,255)');
  const port1 = node1.addOutPort('Out');
  node1.setPosition(100, 100);

  // 3-B) create another default node
  const node2 = new DefaultNodeModel('Node 2', 'rgb(192,255,0)');
  const port2 = node2.addInPort('In');
  node2.setPosition(400, 100);

  // link the ports
  const link1 = port1.link(port2);
  (link1 as DefaultLinkModel).addLabel('Hello World!');

  // 4) add the models to the root graph
  model.addAll(node1, node2, link1);

  // 5) load model into engine
  engine.setDiagramModel(model);

  // 6) render the diagram!
  return <DiagramWidget className="srd-demo-canvas" diagramEngine={engine} />;
};

```

**Comment by hayk94** [comment]
Lol was opening same issue, you beat me in 16 seconds 😄

**Comment by jordanworner** [comment]
It looks like **closest** and a few other modules are listed as peer dependencies so they need to be installed manually

```
"peerDependencies": {
    "closest": "^0.0.1",
    "lodash": "4.*",
    "pathfinding": "^0.4.18",
    "paths-js": "^0.4.9",
    "react": "16.*"
}
```

**Comment by hayk94** [comment]
@jordanworner yes it works!

**Comment by flomllr** [comment]
@jordanworner Thank you!

**Comment by BrunoQuaresma** [comment]
Here is also complaining about dagre, mathjs

**Comment by schester44** [comment]
Can't resolve 'paths-js/path'

**Comment by Fulguritude** [comment]
@emotion/core
@emotion/styled
dagre
mathjs
pathfinding
paths-js
resize-observer-polyfill

These are all the dependencies I had to install before projectstorm could compile accurately

**Comment by saul-gush** [comment]
This should be added to the Readme file - it took forever to figure this out!

**Comment by andrewphillips-autologyx** [comment]
Hmmm if these packages are set as peer dependencies, does that not mean we make the assumption that the project cannot be used as a standalone package and must be used as a base project?
