### ISSUE TITLE
Troubles to delete link

### ISSUE THREAD

**Issue by DanieLazarLDAPPS** [projectstorm/react-diagrams#394]
The DefaultLinks is hard to be selected because on the click it creates a new point. Check simple demo

**Comment by dylanvorster** [comment]
hold shift + click on the link

**Comment by TranVanKung** [comment]
Hi @dylanvorster, how to disable Shift+click or any key event to delete a link, because I do not want this function on my app. And another weird thing happen, when I double click on a link, this link will be deleted, how to fix that issue

**Comment by azotklas** [comment]
+
