### ISSUE TITLE
select box cannot select links

### ISSUE THREAD

**Issue by popo1221** [projectstorm/react-diagrams#397]
I use "shift" key and mouse down to select items. But the link cannot be selected. Nodes can be selected well.

Is there any settings to enable it?

**Comment by dylanvorster** [comment]
I am able to shift-select links, and I have just pushed a fix for the select box selecting links as well

**Comment by dylanvorster** [comment]
Fixed in `@projectstorm/react-diagrams@6.0.1-beta.1`

**Comment by swanexe** [comment]
In the last version, I think it's too odd for me, to select the link I must use shift . what if, to select the link just click the link and to add Point use shift+Click. thanks
