### ISSUE TITLE
how to remove the link

### ISSUE THREAD

**Issue by geohuz** [projectstorm/react-diagrams#4]
In the gif I can see the operation of removing the link, but I couldn't figure out in the test.

**Comment by alexisvincent** [comment]
Engine.removeLink(link). Check out the source of engine for now if you want to see a list of available functions.

**Comment by dylanvorster** [comment]
Hi, if you were looking for the key command I think I made it backspace or the delete key (FN + backspace if you are on a MacBook). Hover over the link and press one of those keys :)
