### ISSUE TITLE
How to add listener on new Link created

### ISSUE THREAD

**Issue by Naveenraj006** [projectstorm/react-diagrams#400]
How to add a listener on new Link created. 

		this.engine = new DiagramEngine();
		this.engine.registerNodeFactory(new DefaultNodeFactory());
		this.engine.registerLinkFactory(new DefaultLinkFactory());
		this.engine.getDiagramModel().addListener({
     nodesUpdated: function(e){
       // Do something here
	  // alert("dd");
     },
     zoomUpdated: function(e){
      // Do something here
	  //alert("Zoom");
     },
	  linksUpdated: function(event){
		  console.log("events done:")
                 //// Want an on new link event
		 
   }
});
I tried this code  but it's not working

**Comment by dylanvorster** [comment]
Works on my side when I add the event to the `DiagramModel`
```
model.registerListener({
		eventDidFire: action('model eventDidFire')
	});
```

**Comment by Naveenraj006** [comment]
@dylanvorster My code is working fine. But, I don't know how to detect new Link created.

  linksUpdated: function(event){
	  console.log("events done:") // all events are fired here , but I want specific event with their props.
             //// Want an on new link event
}

**Comment by tkrafael** [comment]
It's very hard to infer event information. This works:
```
nodesUpdated = ({node, isCreated = false,}: any) => {
				if(node instanceof NodeModel){
					console.log(node.getID())
				}
			}
```
