### ISSUE TITLE
demo project does not run

### ISSUE THREAD

**Issue by shortwavedave** [projectstorm/react-diagrams#406]
The demo project errors out and displays a blank screen. I tried it on firefox and chrome. My OS is linux.

I went into packages/diagrams-demo-project, ran yarn, and then yarn start.

![image](https://user-images.githubusercontent.com/22798574/63277280-1b567c80-c2b6-11e9-91b7-fa7514738546.png)

here is the output from the build and run:

>  ─[$] yarn                                                                                                                      [19:13:13]
> yarn install v1.17.3
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.9: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
> info fsevents@1.1.3: The platform "linux" is incompatible with this module.
> info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> Done in 32.77s.
> (base) ┌─[david@pop-os] - [~/src/react-diagrams/packages/diagrams-demo-project] - [4498]
> └─[$] yarn start                                                                                                                [19:13:48]
> yarn run v1.17.3
> $ ../../node_modules/.bin/webpack-dev-server
> ℹ ｢wds｣: Project is running at http://0.0.0.0:9000/
> ℹ ｢wds｣: webpack output is served from /
> ℹ ｢wds｣: Content not from webpack is served from /home/david/src/react-diagrams/packages/diagrams-demo-project
> ℹ ｢wdm｣: Hash: d9228373746b8fee4644
> Version: webpack 4.38.0
> Time: 4880ms
> Built at: 2019-08-19 19:13:57
>     Asset    Size  Chunks             Chunk Names
> bundle.js  14 MiB    main  [emitted]  main
> Entrypoint main = bundle.js
> [0] multi (webpack)-dev-server/client?http://0.0.0.0:9000 ./src/main.tsx 40 bytes {main} [built]
> [../../node_modules/react-dom/index.js] /home/david/src/react-diagrams/node_modules/react-dom/index.js 1.33 KiB {main} [built]
> [../../node_modules/react/index.js] /home/david/src/react-diagrams/node_modules/react/index.js 190 bytes {main} [built]
> [../../node_modules/strip-ansi/index.js] /home/david/src/react-diagrams/node_modules/strip-ansi/index.js 161 bytes {main} [built]
> [../../node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:9000] (webpack)-dev-server/client?http://0.0.0.0:9000 4.29 KiB {main} [built]
> [../../node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
> [../../node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
> [../../node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {main} [built]
> [../../node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
> [../../node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {main} [built]
> [../../node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
> [../../node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
> [../react-diagrams/index.ts] 1.46 KiB {main} [built]
> [./src/BodyWidget.tsx] 282 bytes {main} [built]
> [./src/main.tsx] 1.53 KiB {main} [built]
>     + 1520 hidden modules
> ℹ ｢wdm｣: Compiled successfully.
>

**Comment by shoebmogal** [comment]
Same issue!

**Comment by stereobooster** [comment]
Solution is to run in the root

```
yarn build
```

**Comment by dylanvorster** [comment]
#monorepos
