### ISSUE TITLE
I love this project!!!

### ISSUE THREAD

**Issue by Aaronphy** [projectstorm/react-diagrams#408]

**Comment by florianwiech** [comment]
+1
---
@dylanvorster 
How about creating an open Slack for projectstorm, where questions, knowledge transfer and new beta releases can be worked on together?

**Comment by DanieLazarLDAPPS** [comment]
**+1**

Yeah, I am also keen do create slack project where we can create rooms with different topics. We can run free plan for it.

**Comment by dylanvorster** [comment]
Aw thanks guyz ❤️ It was a team effort though :) We do already have a gitter active here: https://gitter.im/projectstorm/react-diagrams?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge (but would also be fine to switch to slack)

**Comment by florianwiech** [comment]
Oh, there is a chat already, that's great!
@DanieLazarLDAPPS got a point, too.

**Comment by shnydercom** [comment]
Through this project I got initial interest for react, really like your work! I just open sourced an App editor with it, which wouldn't have been possible without this project. Thanks!

Do you have a section for projects using react-diagrams, or is it ok if I post a link here?

**Comment by elias-thok** [comment]
I played around with the library for a few days and I really like it as well. I'm thinking of using it for a project for data-modeling. 
Is there some code for implementations of custom-nodes out there?

**Comment by pierre-moire** [comment]
@elias-thok You can take a look at http://projectstorm.cloud/react-diagrams/?path=/story/custom-models--custom-diamond-node and the matching code https://github.com/projectstorm/react-diagrams/tree/master/packages/diagrams-demo-gallery/demos/demo-custom-node1
