### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by veeral-patel** [projectstorm/react-diagrams#412]
Hey - I'd like to be able to open a context menu when I click on a node. Is this something this library provides out of the box? If not, do you have any tips on how to achieve this?

Thanks!
Veeral

**Comment by mx2323** [comment]
The Widgets are react components. you can register an onClick listener on your react component that opens a context menu...

**Comment by veeral-patel** [comment]
Thank you @mx2323! If I have issues, I'll re-open the issue.

**Comment by jpmonettas** [comment]
Hi! I'm trying to do the same but for some reason clicking once right mouse button while moving the mouse "grabs" the node, so the node keeps following the mouse until the next click. 

Thanks for the great library!

**Comment by M2Costa** [comment]
Hello guys, does any of you have an example of how to do this? I'm trying to figure it out but just got stuck in many different approachs

**Comment by renato-bohler** [comment]
@M2Costa I've implemented this using `react-contexify`.

You can checkout the result here: [Logossim](https://renato-bohler.github.io/logossim) (just add a component and right click it).

The source code for this is mostly on these files:
- [`Component.jsx`](https://github.com/renato-bohler/logossim/blob/41138afafb2f0a99f6e5cb4be596f003d63cb1c4/packages/%40logossim/core/Component.jsx#L32): this is a base factory, you could add `MenuProvider` directly into your widgets I think. I've added this here so it will affect all node types.
- [`App.jsx`](https://github.com/renato-bohler/logossim/blob/41138afafb2f0a99f6e5cb4be596f003d63cb1c4/packages/%40logossim/page/src/App.jsx#L297-L308)
- [ContextMenus folder](https://github.com/renato-bohler/logossim/tree/41138afafb2f0a99f6e5cb4be596f003d63cb1c4/packages/%40logossim/page/src/ui-components/ContextMenus)

**Comment by M2Costa** [comment]
Thanks Renato, thats helped a lot!
