### ISSUE TITLE
how to use dagreEngine without redraw flickering

### ISSUE THREAD

**Issue by mx2323** [projectstorm/react-diagrams#413]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/528124/63959014-7b80b780-ca48-11e9-9a79-bb715bc90e51.gif)
hi everyone,  as you can see from the GIF above, i'm getting some flickering while re-rendering. 

i'm trying to use the DagreEngine redistribute() functionality. 

It somewhat makes sense why this is happening, but I'm not sure what the right way to avoid this is... 

on every render(), my React Component uses props to create a new DiagramModel, then I set the DiagramModel on the engine, and then I have this code in componentDidUpdate(). 

```
	componentDidUpdate() {
		console.log("called component did update")
	setTimeout(() => {
			this.dagreEngine.redistribute(this.model)
			engine.repaintCanvas(true)
		}, 0)
	}
```
So, on every render(), I am making a new DiagramModel and setting it, then relying on the Dagre redistribute() call in ComponentDidUpdate() to reposition it. 

Is there a way to stop a painting of a canvas until the redistribute() has been called? Either by suppressing the painting to the canvas, or calling redistribute and repaintCanvas() in render() (when I call redistribute() or repaintCanvas() in render, it doesnt seem to do anything) 

Or - am I not using the library correctly by creating a new model on every render....?

**Comment by mx2323** [comment]
Closing as I am rearchitrcting things to use a single model instead of replacing it

**Comment by mx2323** [comment]
in case anyone reaches this issue - there is an api for blocking repainting of the canvas that might be interesting. 
```

    for (let layer of this.engine.getModel().getLayers()) {
                                        layer.allowRepaint(true);
```

**Comment by gonzaloaune** [comment]
@mx2323 were you able to avoid that flickering? I'm experiencing the same :)
