### ISSUE TITLE
Seperating Rendering Framework from Diagrams Core

### ISSUE THREAD

**Issue by DanielNetzer** [projectstorm/react-diagrams#421]
Hi,
Been working a lot lately with this library and it's just fantastic what you have done here.
Since  my company isn't working with React, i've started porting a lot of the logic and core functionallity into a seperate library made with Angular.

Then came V6, adding a lot of features and performance and that made me realise I can't keep up with this library and maybe I should offer the separation of the rendering engine from the diagram engine, allowing for @storm-diagrams/react, @storm-diagrams/angular, etc...

you can see some of the code i've been working at my repo https://github.com/DanielNetzer/ngx-diagrams,
it's working nicely but still missing a lot of the features react-storm-diagrams have such as the SmartRouting.

let me know what you think about it.

**Comment by dylanvorster** [comment]
discussion moved to gitter
