### ISSUE TITLE
Module not found: Can't resolve '@emotion/core'

### ISSUE THREAD

**Issue by KyDenZ** [projectstorm/react-diagrams#438]
Hello,

After trying to install several versions of beta version 6 of React Diagrams, I have an error:
`Module not found: Can not resolve '@ emotion / core'`
Being used only in your package, why should I also install it on my project?

Thank you

**Comment by Letrab** [comment]
Because it's being used? It is also listed when you install react-diagrams that you should install it, as it is a peer-dependency.

**Comment by StarpTech** [comment]
Why did you close it? I have the same error with the latest version.

**Comment by avilde** [comment]
I have exact same error when trying out the documentation example.
`Module not found: Can't resolve '@emotion/core' in 'C:\projects\tests\editor-tests\node_modules\@projectstorm\react-canvas-core\dist\es\entities\layer'`

**Comment by dylanvorster** [comment]
As per the docs, you need to install these dependencies. Its even listed in the package.json as a peer-dep. It even says when you run yarn, that your peer dependency is missing. It has even been asked here in the issue tracker before several times which can be searched for this very title.

**Comment by avilde** [comment]
@dylanvorster care you show me exactly where in "documentation" it is written?
Oh, found it. You added in the docs:
![image](https://user-images.githubusercontent.com/364880/77034247-27243180-69b2-11ea-8ac6-ef3443069810.png)

And also please guide me to package.json line where you have this dependency?
https://github.com/projectstorm/react-diagrams/blob/15d70e988e88b748c1395805c28f69dded7ebfa8/package.json#L41

**Comment by ajthinking** [comment]
`yarn add closest lodash react mathjs dagre pathfinding paths-js @emotion/core`

Link: [docs/getting started](https://projectstorm.gitbook.io/react-diagrams/getting-started)
Thanks, avilde I also missed this.

**Comment by baloukaulrich6** [comment]
Échec de la compilation
./node_modules/@material-ui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react' in 'C:\Users\balou\bleasy-shop\node_modules\@material-ui\styled-engine'
comment corriger cette erreur je n'arrive plus a compiler

**Comment by Leshe4ka** [comment]
> Échec de la compilation
> ./node_modules/@material-ui/styled-engine/index.js
> Module not found: Can't resolve '@emotion/react' in 'C:\Users\balou\bleasy-shop\node_modules@material-ui\styled-engine'
> comment corriger cette erreur je n'arrive plus a compiler

I had the similar issue, when i try to configure @mui v.5 with JSS

./node_modules/@mui/system/node_modules/@mui/styled-engine/index.js
Module not found: Can't resolve '@emotion/react' in '/Users/username/Documents/workProjects/project/project-ui/node_modules/@mui/system/node_modules/@mui/styled-engine'
