### ISSUE TITLE
How can i make one node to be an "in" node and an "out" node at the same time?

### ISSUE THREAD

**Issue by egdlo** [projectstorm/react-diagrams#446]
sorry for my english, but what i want is something like this... i want that an out node can work as an in node as well, and same thing for in node, i want an in node to work as out node as well.
![image](https://user-images.githubusercontent.com/50607288/66006630-832ee400-e46c-11e9-8ccc-0379e3afeae5.png)

**Comment by jling90** [comment]
This section of the [documentation](https://github.com/projectstorm/react-diagrams/blob/23b174736c1858fa2ee5899505454bf1a408e1a7/docs/customizing/ports.md#specifying-if-a-link-can-be-connected) is relevant. You will want to override `canLinkToPort` to allow your desired behaviour :)
