### ISSUE TITLE
demo project doesnt seem to use css

### ISSUE THREAD

**Issue by quangas** [projectstorm/react-diagrams#449]
in my index.txs I have

`import 'storm-react-diagrams/dist/style.min.css';`

When the page renders, it just shows a white blank screen.

There's a class called `css-18f0176` and if I comment out `position: relative`, then it shows the nodes on a white background.

Any ideas?

**Comment by TranVanKung** [comment]
the "storm-react-diagrams/dist/style.min.css" does not include "bacground-color" or "background" property, so you need to add them by your self.
In my case, I add the following css code:

.srd-diagram {
  height: 100vh;
  padding: 0;
  margin: 0;

  background-color: rgb(60, 60, 60) !important;
  background-size: 50px 50px;
  display: flex;
  background-image: linear-gradient(
      0deg,
      transparent 24%,
      rgba(255, 255, 255, 0.05) 25%,
      rgba(255, 255, 255, 0.05) 26%,
      transparent 27%,
      transparent 74%,
      rgba(255, 255, 255, 0.05) 75%,
      rgba(255, 255, 255, 0.05) 76%,
      transparent 77%,
      transparent
    ),
    linear-gradient(
      90deg,
      transparent 24%,
      rgba(255, 255, 255, 0.05) 25%,
      rgba(255, 255, 255, 0.05) 26%,
      transparent 27%,
      transparent 74%,
      rgba(255, 255, 255, 0.05) 75%,
      rgba(255, 255, 255, 0.05) 76%,
      transparent 77%,
      transparent
    );
}

Let me know if it works for you!

**Comment by quangas** [comment]
Do you have to install storm-react-diagrams separately?

yarn add @projectstorm/react-diagrams@next

This doesn't install storm-react-diagrams for the CSS.

**Comment by danielricecodes** [comment]
This is really bizarre.  This should be documented...
