### ISSUE TITLE
Firstly, thank you for your efforts to make awesome library. I want to ask if I can use this library with pure ES6, and can extend custome model, widget, link, node without TypeScript. Or I must use Typesccript to work with this project. Thank you in advanced!

### ISSUE THREAD

**Issue by TranVanKung** [projectstorm/react-diagrams#456]

**Comment by Huljo** [comment]
Everything is in the title :+1:

**Comment by TranVanKung** [comment]
Thank you for replying, I figured it out!

**Comment by Azerothian** [comment]
maybe close the ticket (it is very obnoxious), if you have figured it out?

**Comment by AlexTo** [comment]
Hi, do you mind briefly explain how did you do it?

**Comment by TranVanKung** [comment]
When you using ES6, you do need type checking like TypeScript. You can using es6 for all example of this library. First, let try to run all example and code it by yourself in es6.
Some reference:
https://blog.sourcerer.io/build-interactive-diagrams-with-storm-react-diagrams-f172ae26af9d
http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--simple-example
https://github.com/projectstorm/react-diagrams/tree/5.1.0/demos
