### ISSUE TITLE
How to make the link over the node?

### ISSUE THREAD

**Issue by Wing-Lo** [projectstorm/react-diagrams#461]
I see the z-index of NodeLayerWidget is 10,and the z-index of LinkLayerWidget is less then 10,
this makes the link always blow the node,when I try to change the z-index of LinkLayerWidget to 11,
the gesture recognization comes error.

Is there any one help me?

this is the effect I want to make.
![image](https://user-images.githubusercontent.com/16633962/67547858-c827fc80-f732-11e9-8279-3610333673b2.png)

**Comment by pierre-moire** [comment]
I would recommend to extend the DiagramModel and redefine the constructor.

This way, you can invert the addLayer between the Links and the Nodes one.

**Comment by Wing-Lo** [comment]
> I would recommend to extend the DiagramModel and redefine the constructor.
> 
> This way, you can invert the addLayer between the Links and the Nodes one.

Thank you, I will try.

**Comment by dylanvorster** [comment]
I added some primitive support for layers and working them. as @pierre-moire said, there are multiple ways you should be able to achieve this.

**Comment by alexandernst** [comment]
This is how I did it: https://github.com/Develatio/react-diagrams/commit/c9e0fd1658b1ae08e99d70440a29764827409450
