### ISSUE TITLE
No way to disable delete entity key binds in CanvasWidget

### ISSUE THREAD

**Issue by s1n7ax** [projectstorm/react-diagrams#463]
I'm trying to create a diagram node with input in it.
[https://i.imgur.com/dknLNut.png](https://i.imgur.com/dknLNut.png)

But if `backspace` or `delete` key is pressed to clear the text, that node will be removed. `DeleteItemsAction` action is registered as below in the `CanvasEngine` as below.

### CanvasEngine.ts
```
	constructor() {
		super();
		this.model = null;
		this.eventBus = new ActionEventBus(this);
		this.stateMachine = new StateMachine(this);
		this.layerFactories = new FactoryBank();
		this.registerFactoryBank(this.layerFactories);
		this.eventBus.registerAction(new ZoomCanvasAction());
		this.eventBus.registerAction(new DeleteItemsAction());
	}
```

### DeleteItemsAction.ts
```
export class DeleteItemsAction extends Action {
	constructor(options: DeleteItemsActionOptions = {}) {
		options = {
			keyCodes: [46, 8],
			...options
		};
		super({
			type: InputType.KEY_DOWN,
			fire: (event: ActionEvent<KeyboardEvent>) => {
				if (options.keyCodes.indexOf(event.event.keyCode) !== -1) {
					_.forEach(this.engine.getModel().getSelectedEntities(), model => {
						// only delete items which are not locked
						if (!model.isLocked()) {
							model.remove();
						}
					});
					this.engine.repaintCanvas();
				}
			}
		});
	}
}
```

This can not be deregistered from the event bus because `DeleteItemsAction` object is not available outside.
```
const a = engine.getActionEventBus().deregisterAction(Action);
```

I could get the registered actions for `InputType.KEY_DOWN` which returns an array but unable to filter out the exact event because the `DeleteItemsAction` class is not exported from the `react-canvas-core`.
```
engine.getActionEventBus().getActionsForType(InputType.KEY_DOWN);
```

For now, it's the first action in the array. As a workaround, I could do the following,

```
    const actions = engine
        .getActionEventBus()
        .getActionsForType(InputType.KEY_DOWN);
    engine.getActionEventBus().deregisterAction(actions[0]);
```

But, I believe if all the default `Actions` were exported, that would be nice.

**Comment by hotgen** [comment]
Similar problem. Want to change inverseZoom for ZoomCanvasAction.

**Comment by alex-enchi** [comment]
Why not to stop propagation of keyboard events on keydown of the input field?

**Comment by kbruskiewicz** [comment]
> Why not to stop propagation of keyboard events on keydown of the input field?

That wouldn't be consistent with having a state machine for processing actions in the first place.

**Comment by mathiasbaldissera** [comment]
Another alternative is to lock the model when focusing the input, and unlock on blur, like described by @christianbuehlmeyer in #414
