### ISSUE TITLE
link far-end point doesn't align with the mouse position

### ISSUE THREAD

**Issue by antonioru** [projectstorm/react-diagrams#467]
## Expected Behavior
When creating a link I expect its far-end point to be aligned with the mouse pointer so that it doesn't mix up when linking 2 different items (check the screenshot)

## Current Behavior
At the moment when creating a new link its far-end point is not always aligned with the pointer so it happens sometimes that the mouse pointer is hovering a port (so it will create a link) but the link's far-end point is elsewhere (and vice versa), this it's quite misleading for the user.

## Possible Solution
Fix the bug

## Steps to Reproduce

1. Create a new link by dragging it from an out-going port of an item
2. Drag it around until it loses the mouse position

## Context (Environment)
This is happening generally when you try to connect 2 items 

## Screenshot
<img src="https://i.postimg.cc/bwnwCnmS/Screenshot-2019-11-17-at-23-47-39.png" />

**Comment by mathiasbaldissera** [comment]
Same bug here

**Comment by antonioru** [comment]
> Same bug here

I don't know if this should be considered a proper bug but I'll try to fix it as soon as possible...

**Comment by antonioru** [comment]
Apparently it depends on the size of the port: 
if the port is larger than the default size (15x15) the bug happens

**Comment by mathiasbaldissera** [comment]
Or maybe if the port is small too (i use 10x10 ports)

**Comment by antonioru** [comment]
Finally I think I've found the method responsible for setting the link position, it should be: `DragNewLinkState.fireMouseMoved` in `packages/react-diagrams-core/src/states/DragNewLinkState.ts`. 

Now I'm trying to get into the logic so I might be talking nonsense, but I think the method doesn't take into account the click starting position when dragging a new link, it just assumes it's the same point (x,y) of the port

**Comment by antonioru** [comment]
Ok I solved it, opening a MR

**Comment by antonioru** [comment]
https://github.com/projectstorm/react-diagrams/pull/469
