### ISSUE TITLE
Wrong link appearance while creating a link if zoom is activated

### ISSUE THREAD

**Issue by pierre-moire** [projectstorm/react-diagrams#470]
I am pointing at the second "Test 1" here with a zoom of around 60.

![image](https://user-images.githubusercontent.com/2143238/69262097-1e1d8200-0bc3-11ea-900d-98cffd0faae5.png)

The issue is probably introduced by the recent bugfix of #469 concerning link placement offset

EDIT : Added more details

**Comment by mathiasbaldissera** [comment]
I'll check this

**Comment by mathiasbaldissera** [comment]
Yes, it's a bug generated in the #469 bugfix, we forget to consider the zoom level in the calculation. @antonioru any idea of how to resolve this?

**Comment by mathiasbaldissera** [comment]
I fixed the bug. I'll open a new PR

**Comment by antonioru** [comment]
> I fixed the bug. I'll open a new PR

Thank you Mathias, I wasn't able to read your messages until now. 
I apologise

**Comment by pierre-moire** [comment]
I just noticed that the start point has issues too.

If you just click on the start port **without moving the mouse**, the link appear but the position is incorrect. When we start moving the cursor, the start position of the link is then ok

![image](https://user-images.githubusercontent.com/2143238/69419830-9c8e3700-0d1d-11ea-9cfb-982a12ab91fb.png)

**Comment by mathiasbaldissera** [comment]
@pierre-moire can u tell me the exactly steps to reproduce the bug? I've tried here and it's work fine

**Comment by pierre-moire** [comment]
I just zoom out then click on a out port to start creating a link. The mouse should not move at all when we click

**Comment by pierre-moire** [comment]
Note that I am not sure if it's related to my own implementation. Feel free to close the ticket if you can't reproduce it

**Comment by mathiasbaldissera** [comment]
> I just zoom out then click on a out port to start creating a link. The mouse should not move at all when we click

@antonioru can u replicate this bug? I tried here But failed to replicate

**Comment by mathiasbaldissera** [comment]
> Note that I am not sure if it's related to my own implementation. Feel free to close the ticket if you can't reproduce it

Can u share your code?

**Comment by pierre-moire** [comment]
I reproduced it on the demo itself (dynamic ports for instance).

I add a port then:
- mouse over the port
- click and maintain the mouse button clicked without moving the pointer at all
- the 2nd point of the link gets 0, 0 as coordinates, which lead to invalid representation of the link

![image](https://user-images.githubusercontent.com/2143238/69479586-2c57e200-0dff-11ea-837d-5a37ae2038a0.png)


![image](https://user-images.githubusercontent.com/2143238/69479577-13e7c780-0dff-11ea-8e1a-74c0ff1cabe9.png)

**Comment by antonioru** [comment]
> > I just zoom out then click on a out port to start creating a link. The mouse should not move at all when we click
> 
> @antonioru can u replicate this bug? I tried here But failed to replicate

Yes I do! 
There's a bug there, basically if you click on a port without dragging a new link it creates a nonsense link segment. 
I don't think this is a bug we introduced with last merges but I'll take a took at it

**Comment by antonioru** [comment]
Here's the bug in all its vivid majesty 

<img src="https://s5.gifyu.com/images/Screen-Recording-2019-11-23-at-13.52.57.gif" />

**Comment by antonioru** [comment]
Also @pierre-moire I don't think this is related to the zoom lv. 
Can you please correct the issue title?

**Comment by mathiasbaldissera** [comment]
> Also @pierre-moire I don't think this is related to the zoom lv.
> Can you please correct the issue title?

He needs to open another issue, the zoom description is from another bug already fixed
@pierre-moire please, open another issue and close and reference This one

**Comment by antonioru** [comment]
folks I've created the issue: 
#481 

@pierre-moire please close this one

**Comment by pierre-moire** [comment]
Sure, thanks!
