### ISSUE TITLE
Improve performances: add a debounce around repaintCanvas

### ISSUE THREAD

**Issue by pierre-moire** [projectstorm/react-diagrams#478]
I am animating nodes positions with easing and each time a position is updated I call repaintCanvas. The animation is not smooth because each node is triggering a repaint.

I propose to add a debounce of 10ms - 13ms around repaintCanvas to prevent unneeded and too frequent updates.

For now I am using this :

repaint = debounce(() => {
	this.engine.repaintCanvas();
}, 12);

**Comment by antonioru** [comment]
@pierre-moire this is actually a very good point of yours, I'll look into it

**Comment by pierre-moire** [comment]
@dylanvorster Thanks! By the way do you need help to categorize tickets? I would like to add labels but I don't have any right currently
