### ISSUE TITLE
Error on Internet Explorer 11 when moving a point

### ISSUE THREAD

**Issue by will-stone** [projectstorm/react-diagrams#48]
Object doesn't support property or method 'closest'

![image](https://cloud.githubusercontent.com/assets/654103/25394902/424ccc06-29d7-11e7-9a80-ecd2a877fbe0.png)

**Comment by solussd** [comment]
There is a polyfill for this: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Comment by will-stone** [comment]
I'm confused, why has this been closed? Is the polyfil going to be included?

**Comment by dylanvorster** [comment]
no, because its up to you to include poly fills as an application developer (its not my fault that IE 11 is a colossal piece of shit :) ) I would however like another opinion on this. @gen4sp @alexisvincent @solussd

**Comment by solussd** [comment]
I agree polyfills are something that the application developer needs to decide to include or not. It would be difficult to determine for the user what browsers/browser versions they want to support.

**Comment by will-stone** [comment]
Could this be included in the documentation? The polyfill, not your view on IE :) I agree that IE is a total pain in the arse but it's still a widely used browser.

**Comment by dylanvorster** [comment]
Sure, ill do a documentation bump tonight. I will also clean up a few things

**Comment by alexisvincent** [comment]
I recommend using a ponyfil, at the library level. Note, I do not mean a polyfil.

**Comment by will-stone** [comment]
That'd be great, thanks for all the hard work on this project.

**Comment by alexisvincent** [comment]
https://github.com/sindresorhus/ponyfill/blob/master/readme.md

**Comment by will-stone** [comment]
Thanks for updating with new "closest" dependency. Can you please bump the version so Yarn can upgrade the package? I know I'm asking a lot, but a tagged release process or a changelog would also be much appreciated.

**Comment by dylanvorster** [comment]
done

**Comment by will-stone** [comment]
Great, thanks.
