### ISSUE TITLE
After resizing the browser, drag and drop stop working properly 

### ISSUE THREAD

**Issue by AlexTo** [projectstorm/react-diagrams#486]
Hi 
I'm using the drag and drop example. It works ok but after resizing the browser (latest Chrome), I'm no longer able to move the nodes properly.

Chrome: lastest
"@projectstorm/react-canvas-core": "^6.0.1-beta.6",
"@projectstorm/react-diagrams": "^6.0.1-beta.6",
"@projectstorm/react-diagrams-defaults": "^6.0.1-beta.6"

Thank you

**Comment by mathiasbaldissera** [comment]
Did you try only with Storybook or with your own Application?

**Comment by AlexTo** [comment]
Good catch, I tried with my own application. However, I've moved the canvas into a modal and done a bunch of other stuff and it's working properly now so I have no idea why it wasn't working.
Closing this issue
