### ISSUE TITLE
hotkeys combinations and Read only mode

### ISSUE THREAD

**Issue by azotklas** [projectstorm/react-diagrams#490]
1) Сan you add hotkeys combinations?
Ctrl + a - Select All
Ctrl + c - copy element/s
Ctrl + v - paste element/s
Ctrl + z - cut element/s

2) Сan you add the ability to disable the drag and drop of elements (Read only mode)?

**Comment by mathiasbaldissera** [comment]
@azotklas about the "Read only mode", it already exists. It's when a model is locked (`setLocked(boolean)`)

And about the copy and paste, you can create a custom action (extending `Action` class) and register it to the `ActionEventBus` of the `Engine` (`engine.getActionEventBus().registerAction(new ActionExtension())`)
