### ISSUE TITLE
A simple form of serialization to retrieve only the graph information

### ISSUE THREAD

**Issue by AlexTo** [projectstorm/react-diagrams#493]
Hi
I'm aware that we can call model.serialize() to get the JSON but the serialized data is a bit complex with models, layers and stuff and we have to parse the JSON to reconstruct the graph in back end code.
Anyone can recommend me what is the best way to just get the vertices and edges, something like
{ A -> B, B -> C, B -> D }

Thanks a lot

**Comment by jling90** [comment]
`model.getNodes` and `model.getLinks()` will retrieve all nodes and links on the model. This will be a bit simpler than trying to strip the layers out afterwards :)

**Comment by AlexTo** [comment]
Thanks a lot, I previously had to write a bit of code in Java to extract nodes and links but this would be simpler.
