### ISSUE TITLE
Preventing node deselection when the diagram is being dragged

### ISSUE THREAD

**Issue by mlejva** [projectstorm/react-diagrams#499]
Is there any obvious way to prevent node deselection when user is moving the diagram?
It's annoying that user has to select the node again every time she changes the offset.

Also, can one change the deselection event to happen on `mouseUp` instead of `mouseDown`? This way it could be easy to recognize that user has started dragging.

**Comment by mlejva** [comment]
If there must be something new implemented, I'm happy to submit a PR if you hint me in the correct direction.

**Comment by Letrab** [comment]
You could override the `MoveItemsState` (to be able to use it you should override the `DragDiagramItemsState` and following `DefaultState` to be able to override your state machine like 

```
engine.getStateMachine().getCurrentState().childStates = [];
engine.getStateMachine().pushState(new CustomDefaultState());
```

Selection clearing is done here:
https://github.com/projectstorm/react-diagrams/blob/master/packages/react-canvas-core/src/states/MoveItemsState.ts#L27

**Comment by mlejva** [comment]
Thank you. I’ll try that probably in the next few weeks.
