### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Manuel83** [projectstorm/react-diagrams#5]
Hi,

i like to use this engine in for my open source project. Is there a npm install available?

Regards,
Manuel

**Comment by alexisvincent** [comment]
I'm sure @dylanvorster could release it. But for now you can just install from github using npm.

`npm install projectstorm/react-diagrams`

**Comment by dylanvorster** [comment]
https://www.npmjs.com/package/storm-react-diagrams
