### ISSUE TITLE
It nice to extend more functionality, especially on LinkModel

### ISSUE THREAD

**Issue by TranVanKung** [projectstorm/react-diagrams#505]
Here is the reference I find interesting: https://ej2.syncfusion.com/react/demos/?_ga=2.68098901.535664738.1576606258-1012485111.1576606258#/material/diagram/default-functionality

**Comment by renato-bohler** [comment]
Hey @TranVanKung 

In this library, you are able to extend links. Check out this [example](http://projectstorm.cloud/react-diagrams/?path=/story/custom-models--custom-animated-links) (and here's the [source code](https://github.com/projectstorm/react-diagrams/blob/47e4a145205f99686923fa03ccc8b3e5fe8c8068/packages/diagrams-demo-gallery/demos/demo-custom-link1/index.tsx)).

**Comment by TranVanKung** [comment]
Hello, thank you for immediately reply. I already see that example, but I am struggling with make an arrow on the head of a link. I also read all the issue on this repo about this problem, but it seems like no one give a clear solution for that. It has been 1 month since I struggled with this problem but I have not figure out any solution yet. And I think this library should have a link with an arrow, it is pretty important in some case, like a flowchart diagram. But I do not know why the owner of this library has not make this functionality yet. Please let me know If you have a clear solution. Thank you in advance.

**Comment by dylanvorster** [comment]
@TranVanKung `But I do not know why the owner of this library has not make this functionality yet` I work on this library solely for the benefit of others with nothing in return. If there is a feature missing, I ask others to help out such as yourself to try and add that functionality unless I am able to quickly do it. Keep in mind that there is no one funding me

**Comment by TranVanKung** [comment]
Thank you for reply my comment and for your effort on such nice library, it help me a lot on my project. I see some guys have solution for above issue. I try that solution but it does not work in my case. So I think it is better if some one or even you (who understand most about this library) can contribute the solution to that repo with this missing feature because no one give a clear solution for this feature.
