### ISSUE TITLE
"export 'CanvasWidget' was not found in '@projectstorm/react-canvas-core'

### ISSUE THREAD

**Issue by xiaopow** [projectstorm/react-diagrams#506]
Followed installation from doc and demo but getting this error. Any reason why this might happen?

**Comment by renato-bohler** [comment]
Hmm, doesn't happen to me.

Are you importing it like this?

```
import { CanvasWidget } from '@projectstorm/react-canvas-core';
```

And do you have at least these dependencies on your `package.json`?

```
"dependencies": {
    "@emotion/core": "^10.0.22",
    "@emotion/styled": "^10.0.23",
    "@projectstorm/react-canvas-core": "^6.0.1-beta.6",
    "@projectstorm/react-diagrams": "^6.0.1-beta.6",
    "@projectstorm/react-diagrams-core": "^6.0.1-beta.6",
    "@projectstorm/react-diagrams-defaults": "^6.0.1-beta.6",
    "@projectstorm/react-diagrams-routing": "^6.0.1-beta.6",
    "closest": "^0.0.1",
    "dagre": "^0.8.5",
    "lodash": "^4.17.15",
    "mathjs": "^6.2.5",
    "pathfinding": "^0.4.18",
    "paths-js": "^0.4.10",
    "resize-observer-polyfill": "^1.5.1",
  },
```

**Comment by xiaopow** [comment]
My project isn't setup with Typescript, will that matter? I had a look in the node_modules for @projectstorm/ and I see .ts files. Do I have to configure my project to compile Typescript files from the node_modules? If so, please direct me to information on how to setup my project for this. Thank you.

I have installed all those dependencies you listed, and I am importing the same way you are.
```
import { CanvasWidget } from '@projectstorm/react-canvas-core';
```

I get the following error.

"export 'CanvasWidget' was not found in '@projectstorm/react-canvas-core'

**Comment by renato-bohler** [comment]
What is your project setup? Was it made using `create-react-app`?

I'm using `create-react-app`, I'm not using Typescript, did the exact same thing and it works.

**Comment by xiaopow** [comment]
I am using Rails and webpacker

**Comment by xiaopow** [comment]
@renato-bohler are you installing the 6 beta? or the stable 5?

I am using the 6 beta
```
yarn add @projectstorm/react-diagrams@next
```

**Comment by renato-bohler** [comment]
> I am using Rails and webpacker

So this seems to be the only difference... but unfortunately I know nothing about Rails :disappointed: 

> @renato-bohler are you installing the 6 beta? or the stable 5?

I'm using the beta aswell. [Here's my repository](https://github.com/renato-bohler/logossim).

**Comment by xiaopow** [comment]
Thank you though, I'll take a look at your repo and see if I can find a fix to this.

**Comment by xiaopow** [comment]
I solved it based on the solution given here https://github.com/rails/webpacker/issues/2407. This is to do with the webpacker module.
