### ISSUE TITLE
the operations becomes very slow when the number of nodes becomes large

### ISSUE THREAD

**Issue by latifuluman** [projectstorm/react-diagrams#522]
When I create many nodes (in my example 269 nodes), everything becomes very slow. For instance I want to move all nodes to right it becomes 2 seconds but in less nodes like 5 nodes it becomes instantly. Is there any suggestion about this problem?

**Comment by latifuluman** [comment]
Them main reason of the problem is that there are many render operations in the project. I have optimized my project.Mainly I have prevented the rendering of unnecessary components. To do that I have used [shouldComponentUpdate](https://tr.reactjs.org/docs/react-component.html#shouldcomponentupdate) Method.

**Comment by Harshmakadia** [comment]
@latifuluman Can you please share which places or library class have you added shouldComponentUpdate Method?

I'm facing same issue with the performance.

**Comment by latifuluman** [comment]
Hi @Harshmakadia, 
Actually I added the shouldComponentUpdate method in high level (not in module level but in my own component). It prevented re-rendering the node in unneccessary cases.  Probably in module level you should add the method to nodemodel.ts file, but what you should focus is that you should render the nodes only in necessary cases. You can achive it in high level like me (on own components)

**Comment by Harshmakadia** [comment]
Thanks, @latifuluman, Do you have any sample repo which I can refer to? I'm having heavy re-rendering happening. If you can please guide me.
