### ISSUE TITLE
Links are getting detached on moving the node for dynamically added Ports

### ISSUE THREAD

**Issue by naishe** [projectstorm/react-diagrams#528]
I am building a node which has an Add button on it (and eventually a remove button on each port) to add as  many ports as the user want on the node.

When I drag the node around, the link does not move with the port -- makes it look like it is disconnected. The ports added in the constructor of the custom NodeModel works as expected.

I have followed the code in the Storybook for Custom Nodes and Dynamic Ports. Here is what my version looks like:

```tsx
export class CardNodeModel extends NodeModel<NodeModelGenerics & CardNodeModelGenerics> {
  constructor() {
    super({
      type: 'Card'
    });
    this.addPort(new DefaultPortModel(false, 'fourthAttempt', 'forthAttempt'));
  }
}

export class CardNodeWidget extends React.Component<CardNodeWidgetProps> {
  state = { ports: [] };
  addPort = () => {
    const ports = this.state.ports;
    this.setState({
      ports: [
        ...ports,
        {
          id: ports.length + 1,
          label: 'DynamicPort'
        }
      ]
    });
    this.props.engine.repaintCanvas();
  };
  render() {
    return (
      <div
        style={{
          backgroundColor: 'white',
          opacity: 0.4,
          border: '1px solid black'
        }}>
        <div>CUSTOM NODE</div>
        <div>
          <button onClick={this.addPort}>ADD</button>
        </div>
        <PortWidget port={this.props.node.getPort('fourthAttempt')} engine={this.props.engine}>
          <div>Fixed port</div>
        </PortWidget>
        {this.state.ports.map((p, i) => {
          const pm = this.props.node.addPort(new DefaultPortModel(false, `port-${i}`, `${p.label}-${i}`));
          return (
            <PortWidget port={pm} engine={this.props.engine}>
              <div>
                {p.label}-{i}
              </div>
            </PortWidget>
          );
        })}
      </div>
    );
  }
}

```

This is how it look if I drag the CUSTOM NODE. Notice how the port from the constructor moved along but the port added dynamically did not.
<img width="381" alt="Screen Shot 2020-01-20 at 10 25 07 AM" src="https://user-images.githubusercontent.com/845424/72699767-af7f8500-3b6f-11ea-9afd-b9ff01acbbd1.png">

**Comment by renato-bohler** [comment]
Hmm, at a first glance, it seems that in every render you are calling `this.props.node.addPort` for every port you have on your component state. This is not what you want to do, and is probably the reason why links are getting detached.

You have 2 different port lists: one on state (that has the correct amount of ports) and one on the node model itself (that probably has dozens, hundreds or even thousands of ports, because they are re-added on every render). Maybe if you serialize the diagram, you'll have a better understanding on what's happening.

At the end of the day, you don't need to keep track of the ports on your component state. Try something like that:

```Javascript
export class CardNodeModel extends NodeModel<NodeModelGenerics & CardNodeModelGenerics> {
  constructor() {
    super({
      type: 'Card'
    });
    this.addPort(new DefaultPortModel(false, 'fourthAttempt', 'forthAttempt'));
  }
}

export class CardNodeWidget extends React.Component<CardNodeWidgetProps> {
  /**
   * Changed here: removed this.setState
   */
  addPort = () => {
    const lastIndex = this.props.node.getPorts().length
    this.props.node.addPort(`DynamicPort-${lastIndex}`);
    // not sure if this is needed
    this.props.engine.repaintCanvas();
  };
  render() {
    return (
      <div
        style={{
          backgroundColor: 'white',
          opacity: 0.4,
          border: '1px solid black'
        }}>
        <div>CUSTOM NODE</div>
        <div>
          <button onClick={this.addPort}>ADD</button>
        </div>
        <PortWidget port={this.props.node.getPort('fourthAttempt')} engine={this.props.engine}>
          <div>Fixed port</div>
        </PortWidget>
        /**
         * Changed here: mapping from this.props.node.getPorts(), and not state
         */
        {Object.values(this.props.node.getPorts()).map((p, i) => {
          return (
            <PortWidget port={p} engine={this.props.engine}>
              <div>
                {p.label}-{i}
              </div>
            </PortWidget>
          );
        })}
      </div>
    );
  }
}
```

**Comment by naishe** [comment]
Hey thanks. This seems to be the right way to do it.  Except you need to do `Object.keys(this.props.node.getPorts()).length` instead of `this.props.node.getPorts().length` to get the index.

I have still been fire fighting with serialization... seems likes custom attributes in `PortModel` subclasses are not getting serialized. Thanks again for help.

**Comment by renato-bohler** [comment]
Oops, you're right. I'm editing the code on the answer.

What are these custom attributes? You can make your own `PortModel` and override `serialize` and `deserialize`. [Something like this](https://github.com/renato-bohler/logossim/blob/26804f82009dbde57aa663dafc63b7b862dbb770/packages/@logossim/core/Port/PortModel.js).

**Comment by naishe** [comment]
Yeah, I realized I was returning the same object as `super.serialize()` instead of the merged one. Thanks for taking the time to respond. I appreciate it.
