### ISSUE TITLE
Serialization using constructor.name is brittle (add identifier, merge factories and instance factories)

### ISSUE THREAD

**Issue by solussd** [projectstorm/react-diagrams#53]
I use the Google Closure compiler (advanced optimizations) as part of building my ClojureScript code, from which I'm subclassing react-diagrams' model types. `constructor.name` returns different values under different compilation scenarios and is therefore not reliable (e.g., if the serialized diagram is stored in a DB for later deserialization).

**Comment by dylanvorster** [comment]
yeah ill have to make a change to the system, but its going to require a version bump

**Comment by solussd** [comment]
Thanks– I've worked around it for now by overriding stuff.

**Comment by dylanvorster** [comment]
you can also fix this by turning off name mangling

**Comment by solussd** [comment]
Actually, I can’t w/ the google closure compiler in the mix at all. If I skip it entirely, it works (but that’s not practical for this project).

**Comment by dylanvorster** [comment]
Fixed! will be available in new major release when it ships
