### ISSUE TITLE
Can not find factory with type [custom-type]

### ISSUE THREAD

**Issue by ratnajeetshyamkunwar** [projectstorm/react-diagrams#532]
I need to save canvas in JSON and then regenerate it in some time in future. The generated canvas is serializing but when I try to regenerate it by deSerializing, for some reason, it is not identifying custom node-types.

Note: I am not using typescript.

![Screenshot 2020-01-22 at 4 11 19 PM](https://user-images.githubusercontent.com/36529897/72887518-deddef80-3d31-11ea-808b-847390462d0a.png)

**Comment by renato-bohler** [comment]
Apparently, you have a custom node model with type `'equipment'`, but never registered a factory for a node with type `'equipment'`.

Do you have a factory for this custom node? Its constructor should call `super` with argument `'equipment'`. Check the [custom node factory](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeFactory.tsx) example.

And you need to register it [like that](https://github.com/projectstorm/react-diagrams/blob/5ec4327912c730f0541ac0cd9e9cf1fe4e8ea823/packages/diagrams-demo-gallery/demos/demo-custom-node1/index.tsx#L22) on engine startup:

```JavaScript
engine.getNodeFactories().registerFactory(new DiamondNodeFactory());
```

**Comment by ratnajeetshyamkunwar** [comment]
Resolved. Thanks for the help @renato-bohler
