### ISSUE TITLE
Unable to update another node's extras

### ISSUE THREAD

**Issue by pmehta18** [projectstorm/react-diagrams#536]
When I receive event for `selectionChanged`, I can only update extras of the node which is selected and not any other node?

Do we have any method to update the extras of other node as well from the event handler of `selectionChanged` event of another node?

Thanks in advance

**Comment by renato-bohler** [comment]
I've never used it, but it seems that you can access the whole diagram from the argument given to the `selectionChanged` callback.

![](https://i.imgur.com/fBdhyx0.png)

Note that:
- `argument.entity` is the selected node itself
- `argument.entity.parent` is the `NodeLayerModel`
- You have access to all other nodes on the diagram by accessing `argument.entity.parent.models`
- If for some reason you need access to links, or stuff on other layers, you can access `argument.entity.parent.parent.layers`

---

I'm not sure if this is the prettiest of solutions, but I think it'll work for you.

**Comment by pmehta18** [comment]
@renato-bohler Hey, thanks for help. But I am getting following data as part of `selectionChanged` callback attached to node listener.
![image](https://user-images.githubusercontent.com/22170238/73446840-8d61e000-4383-11ea-97dd-f9fd2a963d33.png)

**Comment by renato-bohler** [comment]
Hmm, strange... what version of `react-diagrams` are you using?

**Comment by pmehta18** [comment]
@renato-bohler We are using version 5.2.1
Can you let me know if you made any custom node model for this or use the default one?

**Comment by renato-bohler** [comment]
Hmm so that's the difference.

I tested this on v6, using the "Events and Listeners" story, I just changed [this line](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-listeners/index.tsx#L44):

```diff
- eventDidFire: action('model eventDidFire')
+ eventDidFire: (...args) => console.log('item', args)
```

Then I got the log that I've attached previously.

I think this answer is not valid for v5 then... you could try migrating to v6, maybe? Otherwise I'm not sure if it is even possible to achieve what you need.

**Comment by pmehta18** [comment]
@renato-bohler This works if we tweak the object structure in v5.2.1. Resolved my problem for now, thanks!
