### ISSUE TITLE
How can i remove or delete a port from a node?

### ISSUE THREAD

**Issue by thiagofuzaro** [projectstorm/react-diagrams#538]
The project shows how to add a dynamic port but doesn't show how to remove or delete them. Anyone knows how?

**Comment by renato-bohler** [comment]
The base [NodeModel](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/node/NodeModel.ts) has a [removePort](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-core/src/entities/node/NodeModel.ts#L122-L132) method, but haven't used it yet.

Have you tried it already?

**Comment by thiagofuzaro** [comment]
Yes, it worked perfectly. Thanks!
