### ISSUE TITLE
window.addEventListener return noting

### ISSUE THREAD

**Issue by wangzhe1995** [projectstorm/react-diagrams#54]
I noticed that your code if unmount the component out later, window.keyup will still trigger. and we can get some error message.

the problem is:

`windowListener: window.addEventListener('keyup',(event)`

the window.addEventListener return noting.

https://github.com/projectstorm/react-diagrams/blob/01485add5c2662a152fc8345f1f5696b273f0a3a/src/widgets/DiagramWidget.ts#L175

So when you in the unmount event is not work

https://github.com/projectstorm/react-diagrams/blob/01485add5c2662a152fc8345f1f5696b273f0a3a/src/widgets/DiagramWidget.ts#L144

**Comment by dylanvorster** [comment]
ah right, we should unlisted for that event
