### ISSUE TITLE
How to automatically redistribute elements around the area?

### ISSUE THREAD

**Issue by kneeinnovation** [projectstorm/react-diagrams#544]
Hi to everyone! We create app with mindmap. Is there any feature in react-diagrams to automatically change the locations of child nodes when new child node is created?

![image](https://user-images.githubusercontent.com/61086660/74589744-a10e7700-5010-11ea-89fe-b28b3672daf6.png)

p.s. if it`s wrong place to ask such questions, please point me where (or who) to ask.

**Comment by renato-bohler** [comment]
Hey there.

Well, there is an example of auto distributing, [here](http://projectstorm.cloud/react-diagrams/?path=/story/3rd-party-libraries--auto-distribute-dagre)... but it seems that what you need is more specific, so I would guess you'll have to implement this yourself.

**Comment by kneeinnovation** [comment]
Hi! Thank you for fast reply!

**Comment by pierre-moire** [comment]
I am closing this ticket has it has been answered more than a month ago. Please feel free to reopen if needed
