### ISSUE TITLE
How to run react-diagrams for dev?

### ISSUE THREAD

**Issue by mastermind1981** [projectstorm/react-diagrams#55]
I am trying to test react-diagrams but I could not figure out how to run it locally.

I have cloned the repo used webpack in the root  directory to start it but everytime I got some some lacking dependencies. I have installed them one by one at the end I got  this types of errors:

```
    ERROR in ./src/defaults/DefaultLinkWidget.ts
    (181,13): error TS2339: Property 'props' does not exist on type 'DefaultLinkWidget'.

    ERROR in ./src/defaults/DefaultLinkFactory.ts
    (15,69): error TS2503: Cannot find namespace 'JSX'.
```

I have tried to run a demo in [runkit](https://runkit.com/591ec98ffc1ebe0012bf211c/591ec98ffc1ebe0012bf211d)  but it's giving an error.

Could you please explain step by step how to run the demos locally?

Thanks

**Comment by dylanvorster** [comment]
thats strange : / I'm going to clone the project now and give it a go quick. Its supposed to be:

1. clone
2. run yarn
3. run webpack
4. open a test folder > index file

**Comment by dylanvorster** [comment]
yeah those steps worked for me no problem... Can you run those commands and show me the output?

**Comment by mastermind1981** [comment]
It worked Thank you ...could you add them to the readme to clear the way to run it
