### ISSUE TITLE
How to get maximum zoom to fit all elements

### ISSUE THREAD

**Issue by internetautomat** [projectstorm/react-diagrams#568]
I want to create canvas with specific content. That content is specified in external document and can be changed, so I can't exatly predict, how much space will it take. 
![image](https://user-images.githubusercontent.com/21055107/76425551-736be200-63b2-11ea-8de1-838e7ab2775b.png)

After I added all needed elements, I want to get maximum zoom to fit all of them, smth like that.

![image](https://user-images.githubusercontent.com/21055107/76425571-7b2b8680-63b2-11ea-8c32-237af3c8bc3b.png)

**Comment by renato-bohler** [comment]
There's a [Zoom to fit story](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--zoom-to-fit) available. You could check out the code and see if that works for you.

**Comment by internetautomat** [comment]
> There's a [Zoom to fit story](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--zoom-to-fit) available. You could check out the code and see if that works for you.

Thank you, however this solution has one problem. If canvas is already zoomed far behind, it wan't zoom forward.

**Comment by internetautomat** [comment]
> There's a [Zoom to fit story](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--zoom-to-fit) available. You could check out the code and see if that works for you.

sorry, any ideas?
>Thank you, however this solution has one problem. If canvas is already zoomed far behind, it wan't zoom forward.

**Comment by azotklas** [comment]
this.engine.zoomToFit();

**Comment by AnwarChakhar** [comment]
I made a PR (#576) to _fit_ that need.
