### ISSUE TITLE
Backspace removes element - interferes with textboxes (make binding pluggable)

### ISSUE THREAD

**Issue by khovansky-al** [projectstorm/react-diagrams#57]
Hello. First of all, thanks for the lib, really well-thought architecture here.
While building a real-world app I have encountered an annoying problem with backspace. In my app there is a "details" area with node parameters that user can edit. This area consists of textboxes and other form elements. Now, since lib is using window event handler, every backspace press in a textbox removes selected element from diagram. Maybe 'delete' key should be more than enough?
 Thoughts?

**Comment by dylanvorster** [comment]
it was the delete key but then someone changed it to backspace. I think there is a bigger issue in that if focus is lost from the canvas, we should ignore delete keys being fired. Alternatively, or perhaps both: do you mind adding a prop to the DiagramWidget that allows you to use backspace or delete? Maybe something like: useDeleteKey: boolean?

**Comment by brunoalano** [comment]
I was opening a modal with text editor fields. I changed the behavior to check if the modal is open. You can do the same in the state for the text editor, if it has focus or not.

**Comment by dylanvorster** [comment]
I need to make this pluggable

**Comment by dylanvorster** [comment]
you can now set a list of key codes as a prop (dev branch)
