### ISSUE TITLE
When the database is fetch, the registerListener event is not responding.

### ISSUE THREAD

**Issue by wscart** [projectstorm/react-diagrams#578]
When the database is fetch, the registerListener event is not responding.
issues:
My requirement is to click the selected node, put it in the selected state through the node, and then add the input box to the node. After entering the content, press enter to assign the value of the input box to the node.
Experts, how to deal with it?

```
import React, { useRef, useEffect, useState } from 'react';
import styles from './main.less';
import * as _ from 'lodash';
import createEngine, {
    DefaultNodeModel,
    DiagramModel,
    DefaultDiagramState,
} from '@projectstorm/react-diagrams';

import {
    CanvasWidget,
} from '@projectstorm/react-canvas-core';
import { Row, Col } from 'antd';
import EditorToolbar from './components/EditorToolbar';
import EditorSidebar from './components/EditorSidebar';
import EditorPanel from './components/EditorPanel';

const FlowChat: React.FC<any> = (props: any) => {
    const [isPanel, setIsPanel] = useState(false)
    const [itemPanel, setItemPanel] = useState({})
    const { engine, model } = props;
    const container = useRef<HTMLElement | any>(null);
    model.registerListener({
        eventDidFire: (e: any) => {
            console.log(e)
            const node = e.node
            if (node) {
                node.registerListener({
                    selectionChanged: (e: any) => {
                        const isSelected = e.isSelected
                        setIsPanel(isSelected !== false)
                        // selectionChanged
                        if (isSelected === true) {
                            const item = node.options
                            setItemPanel(item)
                        }
                    }
                });
            }
        }
    });

    return (
        <div className={styles.editorMain}>
            <Row className={styles.editorHd}>
                <Col span={24}>
                    <EditorToolbar engine={engine} model={model} />
                </Col>
            </Row>
            <Row className={styles.editorBd}>
                <Col span={3} className={styles.editorSidebar}>
                    <EditorSidebar />
                </Col>
                <Col span={17} className={styles.editorContent}
                    onDrop={event => {
                        const data = JSON.parse(event.dataTransfer.getData('storm-diagram-node'));
                        const node: any = new DefaultNodeModel(data.label, data.color);
                        if (data.type === 'in') {
                            node.addInPort(`In`, false);
                            if (data.out) {
                                node.addOutPort(`Out`, false);
                            }
                        } else {
                            node.addOutPort(`Out`, false);
                        }
                        const point = engine.getRelativeMousePoint(event);
                        node.setPosition(point);
                        node.registerListener({
                            selectionChanged: (e: any) => {
                                const isSelected = e.isSelected
                                // selectionChanged
                                if (isSelected === true) {
                                    const item = node.options
                                    item.out = data.out
                                    item.schema = { type: data.name }
                                }
                            }
                        });
                        engine
                            .getModel()
                            .addNode(node);
                        engine.setModel(model);
                    }}
                    onDragOver={event => {
                        event.preventDefault();
                    }}
                >
                    <CanvasWidget engine={engine} ref={container} />
                </Col>
                <Col span={4} className={styles.editorSidebar}>
                    <EditorPanel isPanel={isPanel} engine={engine} itemPanel={itemPanel} model={model} />
                </Col>
            </Row>
        </div>
    )
}
// Thanks for the help of @Renato Bohler
// Create the engine only once
const engine = createEngine();
const state = engine.getStateMachine().getCurrentState();
if (state instanceof DefaultDiagramState) {
  state.dragNewLink.config.allowLooseLinks = false;
}

const InitEngine = (props: any) => {
    const [ model, setModel ] = useState(new DiagramModel());
    const { data, onChange } = props;
    engine.setModel(model);
    // Whenever data changes, set the engine to use a new model with this data
    useEffect(()=> {
      if(data) {
        const newModel = new DiagramModel();
        newModel.deserializeModel(JSON.parse(data), engine);
        engine.setModel(newModel);
        setModel(newModel);
      }
    }, [data]);

    return <FlowChat engine={engine} model={model} />
}

export default InitEngine;
```

**Comment by renato-bohler** [comment]
Seems like you are missing the dependencies array on the `useEffect` (it depends at least on `data`). I'm not sure if that is causing the problem though.

Try this:

```JavaScript
useEffect(()=>{
  if(data){
    const getModel = new DiagramModel();
    getModel.deserializeModel(JSON.parse(data), engine);
    engine.setModel(getModel);
  }
}, [data]);
```

Anyway, if you want to know more about `useEffect`, [here's a great article](https://overreacted.io/a-complete-guide-to-useeffect/).

**Comment by wscart** [comment]
> Seems like you are missing the dependencies array on the `useEffect` (it depends at least on `data`). I'm not sure if that is causing the problem though.
> 
> Try this:
> 
> ```js
> useEffect(()=>{
>   if(data){
>     const getModel = new DiagramModel();
>     getModel.deserializeModel(JSON.parse(data), engine);
>     engine.setModel(getModel);
>   }
> }, [data]);
> ```
> 
> Anyway, if you want to know more about `useEffect`, [here's a great article](https://overreacted.io/a-complete-guide-to-useeffect/).

Thank you for your reply. I didn't notice what wasn't written here.

**Comment by wscart** [comment]
> Seems like you are missing the dependencies array on the `useEffect` (it depends at least on `data`). I'm not sure if that is causing the problem though.
> 
> Try this:
> 
> ```js
> useEffect(()=>{
>   if(data){
>     const getModel = new DiagramModel();
>     getModel.deserializeModel(JSON.parse(data), engine);
>     engine.setModel(getModel);
>   }
> }, [data]);
> ```
> 
> Anyway, if you want to know more about `useEffect`, [here's a great article](https://overreacted.io/a-complete-guide-to-useeffect/).

Do you know how to deal with the problem of registerlistener monitoring events?

**Comment by renato-bohler** [comment]
Well, I've never used `registerListener`, so I've never experienced any issues with it.

But there another things you could try to refactor: `InitEngine` is called every render, so it seems you are creating a new `engine` and a new `model` every time the app rerenders.

```JavaScript
const InitEngine = (props: any) => {
  const { data, onChange } = props;
  // setup the diagram engine
  const engine = createEngine();
  const state = engine.getStateMachine().getCurrentState();
  if (state instanceof DefaultDiagramState) {
    state.dragNewLink.config.allowLooseLinks = false;
  }
  // setup the diagram model
  const model = new DiagramModel();
  engine.setModel(model);
  // ...
```

To avoid this, maybe you should do something like:

```JavaScript
// Create the engine only once
const engine = createEngine();
const state = engine.getStateMachine().getCurrentState();
if (state instanceof DefaultDiagramState) {
  state.dragNewLink.config.allowLooseLinks = false;
}

const InitEngine = (props: any) => {
  const [ model, setModel ] = useState(null);

  // Whenever data changes, set the engine to use a new model with this data
  useEffect(()=> {
    if(data) {
      const newModel = new DiagramModel();
      newModel.deserializeModel(JSON.parse(data), engine);
      engine.setModel(newModel);
      setModel(newModel);
    }
  }, [data]);

  // ...
}
```

Also, #524 is probably a related issue.

**Comment by wscart** [comment]
> Well, I've never used `registerListener`, so I've never experienced any issues with it.
> 
> But there another things you could try to refactor: `InitEngine` is called every render, so it seems you are creating a new `engine` and a new `model` every time the app rerenders.
> 
> ```js
> const InitEngine = (props: any) => {
>   const { data, onChange } = props;
>   // setup the diagram engine
>   const engine = createEngine();
>   const state = engine.getStateMachine().getCurrentState();
>   if (state instanceof DefaultDiagramState) {
>     state.dragNewLink.config.allowLooseLinks = false;
>   }
>   // setup the diagram model
>   const model = new DiagramModel();
>   engine.setModel(model);
>   // ...
> ```
> 
> To avoid this, maybe you should do something like:
> 
> ```js
> // Create the engine only once
> const engine = createEngine();
> const state = engine.getStateMachine().getCurrentState();
> if (state instanceof DefaultDiagramState) {
>   state.dragNewLink.config.allowLooseLinks = false;
> }
> 
> const InitEngine = (props: any) => {
>   const [ model, setModel ] = useState(null);
> 
>   // Whenever data changes, set the engine to use a new model with this data
>   useEffect(()=> {
>     if(data) {
>       const newModel = new DiagramModel();
>       newModel.deserializeModel(JSON.parse(data), engine);
>       engine.setModel(newModel);
>       setModel(newModel);
>     }
>   }, [data]);
> 
>   // ...
> }
> ```
> 
> Also, #524 is probably a related issue.

At present, this problem does lead to re rendering. I didn't expect that your method is very good. Thank you very much.

**Comment by wscart** [comment]
My requirement is to click the selected node, put it in the selected state through the node, and then add the input box to the node. After entering the content, press enter to assign the value of the input box to the node. 
Experts, how to deal with it?
