### ISSUE TITLE
Using React.createElement(x,...) instead of React.DOM.x

### ISSUE THREAD

**Issue by kriskrss** [projectstorm/react-diagrams#58]
Since using the React.DOM.x convenience wrapper is considered legacy, what do you think about converting this to React.createElement?

(Raising this as recently our company deprecated the use of React.DOM.x causing our app which uses this lib to break. I made codemods myself to fix this for now, but think it will be better for everyone to move to standards that have more support)

**Comment by dylanvorster** [comment]
where did you hear that it is considered legacy? Curious because I've been following the react blog and I haven't seen that anywhere. Theres also no way I'm going to use JSX for this and React.createElement is really a bad idea when var div = React.createFactory('div') is a much better solution...

**Comment by kriskrss** [comment]
"Convenience wrappers around React.createElement() for DOM components are provided by React.DOM. For example, React.DOM.a(...) is a convenience wrapper for React.createElement('a', ...). They are considered legacy, and we encourage you to either use JSX or use React.createElement() directly instead."

https://facebook.github.io/react/docs/react-api.html

**Comment by dylanvorster** [comment]
Closing this if/until FB decides to be stupid :P

**Comment by dylanvorster** [comment]
lol, and so FB made their move. You win. Going to use the external module and alias React.DOM.div to div

**Comment by dylanvorster** [comment]
I have started moving the project to JSX
