### ISSUE TITLE
Event listener on Node Title

### ISSUE THREAD

**Issue by afsalsymphony** [projectstorm/react-diagrams#587]
Hi All, Is there any way to  add one event to know whether user clicked on title?

**Comment by pierre-moire** [comment]
I would recommend you to trigger a new event by yourself in a custom node.

eg in the custom NodeModel : 

![image](https://user-images.githubusercontent.com/2143238/78020034-fac4c980-7350-11ea-853c-24b0245aac5f.png)

Then in the component that instanciates everything:

```
this.engine = createEngine({ registerDefaultDeleteItemsAction: false, allowLooseLinks: false });
this.model = new DiagramModel();
this.engine.setModel(this.model);
...
this.model.registerListener({
	nodeShrinkToggled: event => {
		// ... Do whatever you want
	}
})
```
