### ISSUE TITLE
How to save the options to the node?

### ISSUE THREAD

**Issue by wscart** [projectstorm/react-diagrams#588]
When reading the database again, the options of this node does not exist.
Now, how to save the options to the node and save the database again?

```
import { NodeModel, DefaultPortModel } from '@projectstorm/react-diagrams';
import { BaseModelOptions } from '@projectstorm/react-canvas-core';

export interface StartNodeModelOptions extends BaseModelOptions {
    color?: string;
	label?: string;
	icon?: string;
}

export default class StartNodeModel extends NodeModel {
    color: string;
	label: string;
	icon: string;

	constructor(options: StartNodeModelOptions = {}) {
		console.log(options)
		super({
			...options,
			type: 'start-node'
        });
        this.label = options.label || 'start';
		this.color = options.color || '#607D8B';
		this.icon = options.icon || 'icon-bofang';

		this.addPort(
			new DefaultPortModel({
				in: true,
				name: 'in'
			})
		);
	}
}
```

When this node is added, there is already a corresponding options, but when the database is read again, the options does not exist.

```
    generateModel(event: any) {
        console.log(event)
        //  This place has no options （label, color, icon)
        return new StartNodeModel();
    }
```
initialConfig: {
x: 381,
y: 37,
id: "2fd3ea58-4b1b-43c9-8c01-30ef2c1b6958",
type: "start-node",
ports: [{…}],
selected: false,
}

**Comment by renato-bohler** [comment]
You need to tell `react-diagrams`:

1. What you want to save, using the `serialize` method.
2. What you wnt to load, using the `deserialize` method.

Example:

```JavaScript
/**
 * `react-diagrams` calls this method when serializing ("saving") the diagram
 * 
 * You can ask it to save these 3 properties in addition to everything else it
 * already saves under the hood (node id, ports, etc.)
 */
serialize() {
  return {
    ...super.serialize(),
    color: this.color,
    label: this.label,
    icon: this.icon,
  };
}

/**
 * `react-diagrams` calls this method when deserializing ("loading") the diagram
 * 
 * You can ask it to load these 3 properties that were adding when serializing in
 * addition to everything else it already loads under the hood (node id, ports, etc.)
 */
deserialize(event, engine) {
  super.deserialize(event, engine);
  this.color = event.data.color;
  this.label = event.data.label;
  this.icon = event.data.icon;
}
```

**Comment by wscart** [comment]
> You need to tell `react-diagrams`:
> 
> 1. What you want to save, using the `serialize` method.
> 2. What you wnt to load, using the `deserialize` method.
> 
> Example:
> 
> ```js
> /**
>  * `react-diagrams` calls this method when serializing ("saving") the diagram
>  * 
>  * You can ask it to save these 3 properties in addition to everything else it
>  * already saves under the hood (node id, ports, etc.)
>  */
> serialize() {
>   return {
>     ...super.serialize(),
>     color: this.color,
>     label: this.label,
>     icon: this.icon,
>   };
> }
> 
> /**
>  * `react-diagrams` calls this method when deserializing ("loading") the diagram
>  * 
>  * You can ask it to load these 3 properties that were adding when serializing in
>  * addition to everything else it already loads under the hood (node id, ports, etc.)
>  */
> deserialize(event, engine) {
>   super.deserialize(event, engine);
>   this.color = event.data.color;
>   this.label = event.data.label;
>   this.icon = event.data.icon;
> }
> ```

Good. It's settled. Thank you！

**Comment by wscart** [comment]
@renato-bohler Good. It's settled. Thank you！
