### ISSUE TITLE
Control Link creation

### ISSUE THREAD

**Issue by t-gacema** [projectstorm/react-diagrams#59]
Is there a way to control which ports are connected to which?
Meaning that only certain ports should be able to be connected to others, but to do this not programmatically but through the canvas
Thanks

**Comment by dylanvorster** [comment]
Unfortunately not at the moment, we wanted to add it as an overridable method in the PortModel or NodeModel, but never got to it

**Comment by t-gacema** [comment]
I achieved this by utilizing custom port models that extend the default ones.

**Comment by smeijer** [comment]
Would be awesome if you're able to share the custom port model.

**Comment by dylanvorster** [comment]
this is now possible with a recent merge of a PR that adds this: https://github.com/projectstorm/react-diagrams/blob/9a90a5e8f5c5e11c15050a9d78a391af3a61face/src/models/PortModel.ts#L57
