### ISSUE TITLE
How to hide dots from links?

### ISSUE THREAD

**Issue by afsalsymphony** [projectstorm/react-diagrams#591]

**Comment by pierre-moire** [comment]
Can you be more precise in your demand @afsalsymphony please? A description is generally a pre-requisite and a screenshot can greatly help to understand you.

**Comment by afsalsymphony** [comment]
![image](https://user-images.githubusercontent.com/49937560/78101388-0245aa80-7405-11ea-8bfc-521f0a809b9a.png)


@pierre-moire Thank you for your reply, I am sharing the screenshot here.

i want to disable making of points from node link.

**Comment by renato-bohler** [comment]
Hmm, you could copy the whole [default link](https://github.com/projectstorm/react-diagrams/tree/master/packages/react-diagrams-defaults/src/link), but not the [`DefaultLinkPointWidget`](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-defaults/src/link/DefaultLinkPointWidget.tsx) and remove [these lines from DefaultLinkWidget](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-defaults/src/link/DefaultLinkWidget.tsx#L72-L79).

To use this (now custom) link on your project, you'll most likely have to register the factory for this link and maybe change its type from `'default'` to something else [here](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-defaults/src/link/DefaultLinkFactory.tsx#L35), [here](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-defaults/src/link/DefaultLinkModel.ts#L37).

Aaaand you'll also probably have to copy the [default port](https://github.com/projectstorm/react-diagrams/tree/master/packages/react-diagrams-defaults/src/port), register its factory, change its type from `'default'` to something else and make it use your custom link [here](https://github.com/projectstorm/react-diagrams/blob/master/packages/react-diagrams-defaults/src/port/DefaultPortModel.ts#L73).

**Comment by pierre-moire** [comment]
I also used a custom link model / widget / factory to avoid this behavior
