### ISSUE TITLE
Uncaught TypeError: Class constructor NodeModel cannot be invoked without 'new'

### ISSUE THREAD

**Issue by afsalsymphony** [projectstorm/react-diagrams#595]
Hi All,
I am getting an error while creating custom node model as title.

![image](https://user-images.githubusercontent.com/49937560/78123206-72ffbd80-742b-11ea-81a1-92c204114988.png)

![image](https://user-images.githubusercontent.com/49937560/78123374-b5c19580-742b-11ea-9e71-b27ec2122156.png)

**Comment by renato-bohler** [comment]
See #583, seems to be the same problem.

**Comment by afsalsymphony** [comment]
Hi All, finally i got the solution

We need to add below mentioned snippet in package.json


```
"babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "esmodules": true
          }
        }
      ],
      "@babel/preset-react",
      "@babel/preset-flow"
    ],
```


Thank you @renato-bohler
