### ISSUE TITLE
Change zoom behaviour

### ISSUE THREAD

**Issue by internetautomat** [projectstorm/react-diagrams#596]
Hi folks! How can I change zoom behaviour on mouse wheel? For example change zoom direction, or it's speed? Thank you in advance!

**Comment by pierre-moire** [comment]
Zoom is handled by the ZoomCanvasAction. You can override it by instantiating a custom diagramEngine, ActionEventBus and ZoomCanvasAction.

```
export class CustomDiagramEngine extends DiagramEngine {
	constructor(options) {
		super(options);
		this.eventBus = new CustomActionEventBus(this);
		this.eventBus.registerAction(new CustomZoomCanvasAction());
		this.eventBus.registerAction(new MyOtherCustomAction());
	}
...
```

**Comment by renato-bohler** [comment]
To give you an example, yesterday I implemented a custom zoom action on my project. It allows the zoom to be only in a limited set of values.

See this commit: https://github.com/renato-bohler/logossim/commit/dbc1b8b8a804d4c2974d1e5cf86d039ef32f6acc

**Comment by internetautomat** [comment]
Thank you guys!!! You are the best!
