### ISSUE TITLE
Is there any way to select a node on the canvas?

### ISSUE THREAD

**Issue by azotklas** [projectstorm/react-diagrams#597]
Is there any way to select a node on a canvas?

I have some nodes on canvas.
there are their names in the navigation panel.
I want to click on a name in the navigation panel, and a node with that name should selected on canvas.

How can I do that?

**Comment by pierre-moire** [comment]
If you have a navigation panel you likely have more than just the names but also the nodes IDs.

It can be done this way (provided this.engine is the instantiated diagramEngine)

```
this.engine.getModel().getNode(node.options.id).setSelected(true);
```
