### ISSUE TITLE
allowLooseLinks: false not working

### ISSUE THREAD

**Issue by afsalsymphony** [projectstorm/react-diagrams#608]
Hi Team,

I tried to avoid loose links in this library but it not working with allowLooseLinks: false.

```
<CanvasWidget
 engine={engine}
 model={model}
 allowLooseLinks={false}
 />
```

**Comment by afsalsymphony** [comment]
<CanvasWidget
 engine={engine}
 model={model}
 allowLooseLinks={false}
 />

**Comment by renato-bohler** [comment]
What is your `react-diagrams` version? This prop worked on v5, but to disallow loose links on v6 you'll have to do this:

https://github.com/projectstorm/react-diagrams/blob/47e4a145205f99686923fa03ccc8b3e5fe8c8068/packages/diagrams-demo-gallery/demos/demo-simple-flow/index.tsx#L11-L14

**Comment by afsalsymphony** [comment]
@renato-bohler Thank you so much for your reply, it works for me.
