### ISSUE TITLE
Collaborative diagram editing 

### ISSUE THREAD

**Issue by kneeinnovation** [projectstorm/react-diagrams#631]
Hi folks! How can I find source examples for the following scenario? Several users simultaneously follow specific link (where diagram is located) and edit the same diagram. The particular user can see in the real time all changes made by other users (who are editing the diagram at the same moment). 

Thank you in advance!

**Comment by renato-bohler** [comment]
Hmmm I really doubt there is any example of this out there. This seems like a really challenging one... it seems like a somewhat complex distributed systems problem.

But I imagine you would need to first setup some kind of networking, to communicate changes made to the diagram. Everyone would have to be connected to some WebSocket sending diffs when the user changes something and receiving and applying other user's changes to the diagram.

**Comment by kneeinnovation** [comment]
Ok Renato thank you for the reply!

**Comment by Soarex16** [comment]
For ex. you can share serialized diagram model. But I think this is an unefficient way.

**Comment by dylanvorster** [comment]
I cant even begin to explain how difficult this is given that we just implemented something like this at my work with CRDTS. Take a look at `yJS` and I truly wish you the best of luck xD
