### ISSUE TITLE
Changing node name

### ISSUE THREAD

**Issue by JRMaitre** [projectstorm/react-diagrams#635]
First of all, thanks for this library! I'm trying to use it for a project showing workflows and it seems like a good fit. 🎉 

As I'm working through this, I feel like I'm doing something wrong. I want to update the name of a node dynamically based on a form value I have, I'm currently using this function:

```
const changeNodeName = (newNodeName: string) => {
    const node = engine.getModel().getNode(nodeId) as any
    node.options.name = newNodeName
    engine.repaintCanvas()
}
```

If I don't cast `as any` TS shows an error 

![image](https://user-images.githubusercontent.com/728171/81593718-b7f50900-9374-11ea-8ab0-48de17697e0c.png)

which makes me think that's not how I'm supposed to override these values. Any insights?

I feel like I'm missing something in how I'm supposed to set custom values in the diagram (currently I'm updating the name, but in the future I'll probably want to add more properties, which I think I can just stuff in `extras` but it seems a little odd?)

**Comment by jessehanley** [comment]
Try `.getOptions` or `.getOptions.extras`

**Comment by JRMaitre** [comment]
Thank you @jessehanley! Is it expected to have to directly update these values like 
`node.getOptions().name = 'newName'` ?

**Comment by jessehanley** [comment]
Yup! That's how I've been doing it.

**Comment by JRMaitre** [comment]
Thank you!
