### ISSUE TITLE
Is there a way to have a some specific nodes locked at a position?

### ISSUE THREAD

**Issue by vickyvishal** [projectstorm/react-diagrams#641]
I want a particular node to be locked in the diagram while the other nodes will be draggable.

**Comment by renato-bohler** [comment]
I think you can call `model.setLocked(true)` on a node model... have you tried that?

**Comment by vickyvishal** [comment]
> I think you can call `model.setLocked(true)` on a node model... have you tried that?

Yes it is working. Thanks a lot

**Comment by sarastef** [comment]
It's works but what happend if I want to use the output ports to link another edges?, all the node is locked but , how can I do to abble the ports?

**Comment by renato-bohler** [comment]
So you want to lock the node, but not its ports? If that is the case, please check https://github.com/projectstorm/react-diagrams/issues/647#issuecomment-634122139.

**Comment by sarastef** [comment]
thanks!
