### ISSUE TITLE
error on calling addPort() in cutsom node

### ISSUE THREAD

**Issue by vickyvishal** [projectstorm/react-diagrams#645]
My error

<img width="815" alt="Annotation 2020-05-24 211518" src="https://user-images.githubusercontent.com/22187019/82762970-6df43480-9e04-11ea-9f28-533f2465c37a.png">

my nodeModel

![image](https://user-images.githubusercontent.com/22187019/82762896-e0b0e000-9e03-11ea-81b5-0dd4fb7784b3.png)
my portModel

![image](https://user-images.githubusercontent.com/22187019/82762904-fa522780-9e03-11ea-8d12-1f21a9e1b424.png)

**Comment by renato-bohler** [comment]
Do you have the code for the Widget as well?

**Comment by vickyvishal** [comment]
I did not have the port widget in the model. After adding there is this type error.

![image](https://user-images.githubusercontent.com/22187019/82766076-35605500-9e1c-11ea-9619-cd9f113bd208.png)

My modelWidget

![image](https://user-images.githubusercontent.com/22187019/82766087-545ee700-9e1c-11ea-9850-01caae65f4ce.png)

**Comment by renato-bohler** [comment]
Hmmm shoudn't the `PortWidget` have been created with `PortModelAlignment.BOTTOM` instead of `LEFT`?

**Comment by vickyvishal** [comment]
> Hmmm shoudn't the `PortWidget` have been created with `PortModelAlignment.BOTTOM` instead of `LEFT`?

![image](https://user-images.githubusercontent.com/22187019/82766166-039bbe00-9e1d-11ea-9803-3b1a9119a3ec.png)

**Comment by renato-bohler** [comment]
Hmmmmm, and what is `this.props.node.getPort(PortModelAlignment.BOTTOM)` returning? Can you log it?

**Comment by vickyvishal** [comment]
Here is the log for `this.props.node.getPort(PortModelAlignment.BOTTOM)`

![image](https://user-images.githubusercontent.com/22187019/82767320-13b89b00-9e27-11ea-8038-2a17c0ddc4f6.png)

**Comment by renato-bohler** [comment]
That's odd... I'm not sure what TypeScript is complaining about here :frowning_face:

**Comment by vickyvishal** [comment]
Strange but I made it work by making `"strict": false` in tsconfig.json . I don't know why it is working. Also can't see any type error on my IDE :(

**Comment by ferrantedev** [comment]
try with `port={this.props.node.getPort(PortModelAlignment.Bottom) as YourPortModelClassHere}`

for instance if you are using DefaultPortModel, then 
`port={this.props.node.getPort(PortModelAlignment.Bottom) as DefaultPortModel}`
