### ISSUE TITLE
diagram-demo-gallery yarn runs start fails

### ISSUE THREAD

**Issue by johnsmithlon** [projectstorm/react-diagrams#646]
Hi,

I wanted to try the library but cannot get the demo gallery to run (the diagrams-demo-project works fine for me). Here's the error:

PS C:\React\react-diagrams-master> yarn install                                                                                   yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.01s.
PS C:\React\react-diagrams-master> cd .\packages\diagrams-demo-gallery\                                                           PS C:\React\react-diagrams-master\packages\diagrams-demo-gallery> yarn run start                                                  yarn run v1.22.4
$ ../../node_modules/.bin/start-storybook
internal/modules/cjs/loader.js:584
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /C:/React/react-diagrams-master/node_modules/is-promise\package.json; targets must start with "./"
    at resolveExportsTarget (internal/modules/cjs/loader.js:541:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:581:20)
    at applyExports (internal/modules/cjs/loader.js:454:14)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\React\react-diagrams-master\node_modules\run-async\index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\React\react-diagrams-master\packages\diagrams-demo-gallery>

**Comment by renato-bohler** [comment]
Hey! Have you tried running `yarn build` on the project root already?

**Comment by johnsmithlon** [comment]
Thanks that fixed it. Sorry about that!

**Comment by johnsmithlon** [comment]
Actually no, I have two computers.  On one it is running fine (older machine set up a while back), on a brand new machine with fresh Windows 10 install I am getting this error.  Is there any information / diagnostics I can provide to give a clue to the issue?

**Comment by renato-bohler** [comment]
Hmmm that's odd... are you sure you ran `yarn install` and `yarn build` on the project root before running `yarn start`on the demo gallery on this new machine?

If you're sure you did that, the error message is the same? Which version of node/npm/yarn are you using?

**Comment by johnsmithlon** [comment]
Yes, I definitely run those.  From a google search, this seems to be the same issue:
https://github.com/then/is-promise/issues/13

yarn version 1.22.4
node version v14.3.0

**Comment by renato-bohler** [comment]
Hmm then probably when running `yarn install` on your new machine, you've downloaded `is-promise`'s broken version (`2.2.0`), while on the old machine you had an older (but functioning) version.

Does adding this to the project's `package.json` help?

```
"resolutions": {
  "is-promise": "2.1.0"
}
```

**Comment by johnsmithlon** [comment]
Yes, that fixes it!  Scary how things can just break so easily in the javascript world.

**Comment by renato-bohler** [comment]
> Yes, that fixes it! Scary how things can just break so easily in the javascript world.

Hahaha true... but sadly its not the first and probably not the last time this will happen :sweat_smile:

**Comment by johnsmithlon** [comment]
Should I close the issue or is this something you will be fixing in the repo?

**Comment by renato-bohler** [comment]
Hmmm I'm not sure if anyone is going to dive deep to see exactly what can be done to avoid this, as adding "resolutions" to the package only solves the problem for the demo project.

So I would say close hehe
