### ISSUE TITLE
How to make the nodes not draggable? 

### ISSUE THREAD

**Issue by vickyvishal** [projectstorm/react-diagrams#647]
I understand that `model.setLocked(true)` will make it not draggable but we cannot initiate a link from its ports. Is there a way to make the nodes not draggable but the port can initial a link?

TIA

**Comment by renato-bohler** [comment]
Hmm... apparently there's a configuration that does exactly that.

https://github.com/projectstorm/react-diagrams/blob/361fbe4ffed7d5b485c9d7e871cf891c55d6c4d7/packages/react-diagrams-core/src/states/DragNewLinkState.ts#L44-L47

It defaults to `false`, but you can change it by doing this:
```JavaScript
const state = engine.getStateMachine().getCurrentState();  state.dragNewLink.config.allowLooseLinks = false;
```

**Comment by malavshah-9** [comment]
@renato-bohler  Can you give here details example or something which i can implement.

Thanks in advance
