### ISSUE TITLE
Auto layout Graph with animation

### ISSUE THREAD

**Issue by Harshmakadia** [projectstorm/react-diagrams#657]
Hello there,

I'm using dagre library for auto-layout of the graph, but there is no animation support for that library so I was checking other libraries that can be used for auto layout with animation and I found this 

**Option 1**
[cytoscape.js-dagre](https://github.com/cytoscape/cytoscape.js-dagre) How can I used that 
along with react-diagrams?

**Option 2**
Animated node moves using [GSAP](https://www.npmjs.com/package/gsap) 
Example - 
http://projectstorm.cloud/react-diagrams/?path=/story/3rd-party-libraries--animated-node-moves-gsap
How can I integrate this with [dagre](https://www.npmjs.com/package/dagre) library?

**Comment by Wing-Lo** [comment]
Thank you! It's helps me a lot!!!

**Comment by Harshmakadia** [comment]
@Wing-Lo Did you find some solution to this?

**Comment by dylanvorster** [comment]
I think there is an animation demo for this in the demo-gallery

**Comment by SatishChandraPalakoti** [comment]
Look for cytoscape react library. It's pretty easy to incorporate.
