### ISSUE TITLE
Support for Angular?

### ISSUE THREAD

**Issue by GlitchEclipse** [projectstorm/react-diagrams#658]
I know this is a react library, but can it be supported inside an angular component? The library looks awesome and would like to use it if possible. Thanks.

**Comment by renato-bohler** [comment]
I remember that someone tried to make a port...

... here it is:

- https://github.com/projectstorm/react-diagrams/issues/421
- https://github.com/DanielNetzer/ngx-diagrams

Not sure if that even works, though...
