### ISSUE TITLE
Add github pages demo

### ISSUE THREAD

**Issue by kvolkovich-sc** [projectstorm/react-diagrams#66]
How about add interactive [github pages](https://pages.github.com/) demos + docs?

We have a couple examples:

[#1](https://opuscapita.github.io/react-rich-editors/?currentComponentId=opuscapita-react-rich-editors%2F1.0.9%2FEmailRichEditor&maxContainerWidth=44%25)
[#2](https://opuscapita.github.io/react-dates/?currentComponentId=%40opuscapita%2Freact-dates%2F0.3.0-beta.6%2FDateInput)
[#3](https://opuscapita.github.io/react-buttons/)

These demos impelemented using home-made tool [react-showroom](https://github.com/OpusCapita/react-showroom-client)

Maybe it has sense to consider other options:
* [react-storybook](https://github.com/storybooks/storybook)
* [react-styleguidist](https://github.com/styleguidist/react-styleguidist)
* Manually created demo page

**Comment by dylanvorster** [comment]
Fixed in the dev branch
