### ISSUE TITLE
crash in MoveItemsState (when click empty canvas space after popup)

### ISSUE THREAD

**Issue by flieks** [projectstorm/react-diagrams#665]
Hi 

after clicking on a node which does open my dialog, and then closing it and clicking on the canvas (not on a node bug on empty space canvas)
```
 node1.registerListener({
            eventDidFire: (e) => {
                try {
                    if(e && e.function == "selectionChanged" && e.isSelected) {
                        setOpenDialog(true)
                    }
                } catch (error) {
                }
            }
        });
```
```
Uncaught TypeError: Cannot read property 'isSelected' of null
    at Object.fire (MoveItemsState.ts:26)
    at ActionEventBus.fireAction (ActionEventBus.ts:73)
    at onMouseDown (CanvasWidget.tsx:86)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
```

It only happens after the dialog has opened and closed. Otherwise i can click the empty space and drag it fine.

![image](https://user-images.githubusercontent.com/5032389/85950941-20696b00-b960-11ea-9d8e-007e766d00bc.png)

It crashes because in here element is null after 
`const element = this.engine.getActionEventBus().getModelForEvent(event);`
```
	constructor() {
		super({
			name: 'move-items'
		});
		this.registerAction(
			new Action({
				type: InputType.MOUSE_DOWN,
				fire: (event: ActionEvent<React.MouseEvent>) => {
					const element = this.engine.getActionEventBus().getModelForEvent(event);
					if (!element.isSelected()) {
						this.engine.getModel().clearSelection();
					}
					element.setSelected(true);
					this.engine.repaintCanvas();
				}
			})
		);
	}
```

**Comment by flieks** [comment]
@tkolanko thanks this is great. When will this be merged you think ?
Or i can in meantime insert my own MoveItemState ?

**Comment by flieks** [comment]
Ok i also implemented my own MoveItemState and inserted it through
`engine.getStateMachine().pushState(new States());`
Thanks for the help

**Comment by paulocfjunior** [comment]
+1
I also tried the [same approach](https://github.com/projectstorm/react-diagrams/issues/665#issuecomment-653885329) to add a custom state handler to fix it on my side but had no success. I'm not really sure how to do that, though. (I'd love to know how to achieve that)

**Comment by DuyBui1993** [comment]
Hi,

This also happens when:
1. mouse right-clicking on the locked node (which will open the context menu)
2. mouse left on the canvas to close the context menu
3. and then dragging the canvas 

Can reproduce in the [demo of storybook](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--locked-widget)
