### ISSUE TITLE
Any way to deactivate selection? / Selection event bug

### ISSUE THREAD

**Issue by maxbasque** [projectstorm/react-diagrams#667]
First of all thanks for the library

We're building an app and we had to put some mouseDown and mouseUp handlers on the container wrapping the CanvasWidget for various reasons, but doing so breaks the selection in the library the instant you try to make a selection. I haven't fully figured out why yet, i'm guessing it has something to do with event propagation but i'm still looking into it

but anyway my main point is that we don't really need selection for our use case, so I was wondering if there was a way to turn it off? The only workaround I could find for now is to forcefully remove the state associated to selections from the childStates array in the diagramStateEngine

i'm attaching the errors we're getting when trying to handle onMouseDown on the parent container and selecting using shift for the sake of documentation

![image](https://user-images.githubusercontent.com/1126291/86131996-53247800-bab4-11ea-811c-cf6afe5a1743.png)
![image](https://user-images.githubusercontent.com/1126291/86132054-65061b00-bab4-11ea-9ba0-2e5caae7e0bc.png)

**Comment by renato-bohler** [comment]
To achieve no selection, what I would try to do is implementing a custom `State` without any selection state implemented. Something like:

- [`DefaultState.js`](https://github.com/projectstorm/react-diagrams/blob/57f4e2d83252df24aaf4a2d30b27d06883e6b231/packages/diagrams-demo-gallery/demos/demo-alternative-linking/DefaultState.ts), but removing:

**Comment by maxbasque** [comment]
I appreciate the suggestion, that is probably one way to do it indeed

**Comment by dylanvorster** [comment]
@renato-bohler I couldn't find an easy way to contact you (but I also didn't look very hard xD), just know that you are a Legend.
