### ISSUE TITLE
DefaultNodeModel

### ISSUE THREAD

**Issue by lieyongchang** [projectstorm/react-diagrams#672]
Is it possible to add multiple name to the DefaultNodeModel constructor? as shown in IMG 1.1. The image is achieve using photoshop.
![suggestion1](https://user-images.githubusercontent.com/62921597/87268291-95aa7380-c4fc-11ea-99a2-0897524a2348.png)
(IMG 1.1)

**Comment by renato-bohler** [comment]
Hey!

Well, you cannot achieve that with the `DefaultNode`, but you can implement your own node, so you can have any properties/methods implemented on `YourNodeModel` and any components/styling on `YourComponentWidget`.

You can configure your own node on your project: take a look at [this example on the storybook](https://github.com/projectstorm/react-diagrams/tree/master/packages/diagrams-demo-gallery/demos/demo-custom-node1) ([link to story](http://projectstorm.cloud/react-diagrams/?path=/story/customization--custom-diamond-node)). You could make `YourNodeModel` extend `DefaultNodeModel` and add a `subtitle` property, or you could build it extending the more generic `NodeModel` and add a `title` and then a `subtitle`...

**Comment by lieyongchang** [comment]
so if I understand this correctly, it should be something like this?

```
import React, { Component } from "react";
import * as SRD from "storm-react-diagrams";


export class MyNodeModel extends Component {
 constructor(props) {
    super(props);
       return <SRD.DefaultNodeModel subtitle: string>

}
}
```

Sorry, I am still quite new to programming.

**Comment by renato-bohler** [comment]
Ooh :confused: if you are new to programming, I'm not sure if this is a good starting point, as this task may be a little bit too much in this case.

But anyways, there's three implementations you have to do when implementing a custom node:

- a `Model` (like [`DiamondNodeModel`](https://github.com/projectstorm/react-diagrams/blob/dd5a0b7d8de5fa886b1e03b4f0d1fdce2c0cbd3d/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeModel.ts)), on which you can implement custom methods or add custom properties for your node.
- a `Widget` (like [`DiamondNodeWidget`](https://github.com/projectstorm/react-diagrams/blob/5ec4327912c730f0541ac0cd9e9cf1fe4e8ea823/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeWidget.tsx)), which is the visual representation of this node: you can access its corresponding `Model` instance (via `node` props, injected by the `Factory`) to call its methods or access its properties.
- a `Factory` (like [`DiamondNodeFactory`](https://github.com/projectstorm/react-diagrams/blob/5ec4327912c730f0541ac0cd9e9cf1fe4e8ea823/packages/diagrams-demo-gallery/demos/demo-custom-node1/DiamondNodeFactory.tsx)): this is used by `react-diagrams` to instantiate the corresponding `Model` and `Widget` upon serialization (diagram loading).

Your `subtitle` would be a property on the `Model`, which could be received from the `Factory` and set on the `Model`'s constructor, and then shown on your `Widget`.

My suggestion would be to start by copying the `DiamondNode` example and playing around with it.

**Comment by lieyongchang** [comment]
Understand! Thanks for being patient with me, and giving me the steps. Really appreciate it.
