### ISSUE TITLE
ZoomtoFit 

### ISSUE THREAD

**Issue by lieyongchang** [projectstorm/react-diagrams#675]
This is not related to #52 , click this [link ](https://github.com/rickhewes/jsx-storm-react-diagrams-demo/issues/2)to navigate to the page
I have written all the steps. The reason why I am posting it here, is because I am hoping more people will see it. 

Any suggestion is welcome.

**Comment by marian2js** [comment]
You need to wait for the canvas to be ready before trying to zoom on it.

```ts
engine.registerListener({
  canvasReady: () => engine.zoomToFit()
})
```

**Comment by lieyongchang** [comment]
![error](https://user-images.githubusercontent.com/62921597/92866711-71064580-f432-11ea-8d88-fd1e2f109d0d.PNG)

my storm react diagram version is 5.2.1, could that be the reason??

**Comment by lieyongchang** [comment]
migrate my version to 6.2.0, and call this function in the correct place solve the issue.
