### ISSUE TITLE
MacOS Screenshot recording are not working

### ISSUE THREAD

**Issue by LiveDuo** [projectstorm/react-diagrams#677]
Connecting nodes does not work with MacOS Screenshot (the default recording app - Cmd/Shift/5).

This is a problem as it is the go-to solution for creating explainer videos for apps made with React-Diagrams. 

![ezgif-4-1975a15f362c](https://user-images.githubusercontent.com/370612/87833859-c6820400-c880-11ea-9699-ddc7f1e8a3e5.gif)

Tested on Chrome and Safari.

**Comment by LiveDuo** [comment]
It may not be obvious but I was trying to get a link out of the node port but I couldn't.

**Comment by nmkettler** [comment]
Is there any update on this or has anyone figured out a temporary workaround?

**Comment by dylanvorster** [comment]
I really don't think there is anything I can do about this to be honest. I would try a different screen recording app ¯\_(ツ)_/¯.

note to self: Never really thought Id get an issue on this repo that literally requires a fix on Mac OS. 2020 man.

**Comment by nmkettler** [comment]
No worries. It's an awesome project :)

**Comment by nmkettler** [comment]
> I really don't think there is anything I can do about this to be honest. I would try a different screen recording app ¯_(ツ)_/¯.
> 
> note to self: Never really thought Id get an issue on this repo that literally requires a fix on Mac OS. 2020 man.

We actually think we may have found a solution: https://github.com/projectstorm/react-diagrams/pull/775

**Comment by sinanyaman95** [comment]
Same issue happens with CTRL + SHIFT + J on Chrome, canvas gets locked. Shift "key up" is not registered
