### ISSUE TITLE
Custom Link Demo 1

### ISSUE THREAD

**Issue by lieyongchang** [projectstorm/react-diagrams#686]
is there a Javascript version for this [demo](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-custom-link1/index.tsx)?

**Comment by renato-bohler** [comment]
Isn't it just the same, but removing type annotations?

**Comment by lieyongchang** [comment]
Like this (see below) ??
 
Typescript:
path: SVGPathElement;
circle: SVGCircleElement;

Javascript 
let path = new SVGPathElement();
let circle = new SVGCircleElement();

if so, according to the demo, SVGPathElement & SVGCircleElement is not imported. I have a feeling there will be error.

**Comment by lieyongchang** [comment]
```
import * as SRD from 'storm-react-diagrams';

// setup diagram engine
this.engine = new SRD.DiagramEngine();
this.engine.installDefaultFactories();

//      
const pathfinding =
			// eslint-disable-next-line no-mixed-operators
		        this.engine.getLinkFactories().getFactory <
			// eslint-disable-next-line no-mixed-operators
			SRD.PathFindingLinkFactory >
			SRD.PathFindingLinkFactory.NAME;
```

PathFindingLinkFactory is undefined, I am sure the syntax is correct.  I am honestly not sure what is wrong here, any help is appreciated.

**Comment by lieyongchang** [comment]
> 
> 
> Like this (see below) ??
> 
> Typescript:
> path: SVGPathElement;
> circle: SVGCircleElement;
> 
> Javascript
> let path = new SVGPathElement();
> let circle = new SVGCircleElement();
> 
> if so, according to the demo, SVGPathElement & SVGCircleElement is not imported. I have a feeling there will be error.

Just in case for anyone who wants the Javascript version, this is the [reference ](https://gist.github.com/goldhand/13c48a91eab7da54ed47e2ef7b6d67cd).

**Comment by renato-bohler** [comment]
Inside the class, you would have to remove `path: SVGPathElement` and all other class property type declarations. Something like this:

![image](https://user-images.githubusercontent.com/25781956/88539016-cdc6b180-cfe6-11ea-9878-08c776fd0205.png)

**Comment by lieyongchang** [comment]
Thanks for the clarification! at least now i have some idea.
