### ISSUE TITLE
Can I use react-diagrams in a non-react program?

### ISSUE THREAD

**Issue by laike9m** [projectstorm/react-diagrams#689]
Hi, I'm looking for a library to help me draw some diagrams and came across react-diagrams. My main job is on backend development so I want to know if react-diagrams is for me. Specifically,

1. Is it possible to use react-diagrams without using React as the frontend framework?
2. If React framework is needed, what familarity am I expected to have with it to be able to use react-diagrams?

Thanks.

**Comment by renato-bohler** [comment]
Hey.

1. Yes, `react-diagrams` works only with React. There's an [independent Angular version](https://github.com/DanielNetzer/ngx-diagrams) aswell, but I've never tried it.
2. I'm not sure what exactly you're trying to achieve, but I would expect some familiarity at least.

**Comment by laike9m** [comment]
Thanks.
