### ISSUE TITLE
PathFindingLinkFactory

### ISSUE THREAD

**Issue by lieyongchang** [projectstorm/react-diagrams#690]
```
import * as SRD from 'storm-react-diagrams';

// setup diagram engine
this.engine = new SRD.DiagramEngine();
this.engine.installDefaultFactories();

//      
const pathfinding =
			// eslint-disable-next-line no-mixed-operators
		        this.engine.getLinkFactories().getFactory <
			// eslint-disable-next-line no-mixed-operators
			SRD.PathFindingLinkFactory >
			SRD.PathFindingLinkFactory.NAME;
```

PathFindingLinkFactory is undefined, I am sure the syntax is correct.  I am honestly not sure what is wrong here, any help is appreciated.

_Originally posted by @lieyongchang in https://github.com/projectstorm/react-diagrams/issues/686#issuecomment-663453525_

**Comment by renato-bohler** [comment]
Actually, your syntax doesn't look quite right. You are not calling `getFactory` (parenthesis are missing).

Try this instead (without typescript):

```
const pathfinding = engine.getLinkFactories().getFactory(PathFindingLinkFactory.NAME);
```

**Comment by lieyongchang** [comment]
![error](https://user-images.githubusercontent.com/62921597/88616677-59b00a80-d0c7-11ea-9039-c968144f2ea8.PNG)

I had this error message, hmm.

**Comment by renato-bohler** [comment]
What version of `react-diagrams` are you using?

**Comment by lieyongchang** [comment]
i yarn add  "storm-react-diagrams": "^5.2.1"

**Comment by renato-bohler** [comment]
Oh, so there's the problem.

On version 6, `engine.getLinkFactories()` returns a `FactoryBank`, in which you can call `getFactory` on ([see here](https://github.com/projectstorm/react-diagrams/blob/v6.2.0/packages/react-diagrams-core/src/DiagramEngine.ts#L23))

On version 5, however, `engine.getLinkFactories()` returns an object on which a property key is the factory name and its value is the factory itself ([see here](https://github.com/projectstorm/react-diagrams/blob/v5.2.1/src/DiagramEngine.ts#L39)).

In this case, I think you could do something like:

```
const pathfinding = this.engine.getLinkFactories()[PathFindingLinkFactory.NAME];
```

If that doesn't work, try logging `this.engine.getLinkFactories()` and see what it returns.

---

If you are using an older version of the library, its always a good idea to refer to documentation and examples on the tag that corresponds to the version you're using. In your case:

https://github.com/projectstorm/react-diagrams/tree/v5.2.1

**Comment by lieyongchang** [comment]
This works.
```
const pathfinding = this.engine.getLinkFactories()[PathFindingLinkFactory.NAME];
```
but the outcome is this: 

![outcome1](https://user-images.githubusercontent.com/62921597/89787948-f86d4a00-db50-11ea-9a61-4a7db2a80acb.PNG)

There is no smart routing :(

**Comment by lieyongchang** [comment]
Expected outcome: 
![expected_outcome](https://user-images.githubusercontent.com/62921597/89788048-1aff6300-db51-11ea-8b88-15c91fae7dee.PNG)

**Comment by lieyongchang** [comment]
Below is the line of code of how I am using it now

```
const pathfinding = this.engine.getLinkFactories()[PathFindingLinkFactory.NAME];
let linkDatapad = sourceDatapad.link(targetDatapad, pathfinding);
```

**Comment by renato-bohler** [comment]
Hmmm I never used this smart routing feature :disappointed:  but here's the code for your expected outcome (on Storybook):

https://github.com/projectstorm/react-diagrams/blob/3ea63750118e476939fcdf1e848d911d2a584900/demos/demo-smart-routing/index.tsx#L60-L65

It is setting `smartRouting` prop to `true` on `DiagramWidget`.

**Comment by lieyongchang** [comment]
I have already set smartRouting to true 😞  🤔 

```
<div>
  <SRD.DiagramWidget
	smartRouting={true}
	maxNumberPointsPerLink={1}
	className="storm-diagrams-canvas"
	diagramEngine={this.engine}
  />
</div>
```

Actually I was referring to this [demo](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-smart-routing/index.tsx) rather then [this](https://github.com/projectstorm/react-diagrams/blob/3ea63750118e476939fcdf1e848d911d2a584900/demos/demo-smart-routing/index.tsx#L60-L65).
