### ISSUE TITLE
Restore (deserialize) diagram model with custom nodes/links/ports

### ISSUE THREAD

**Issue by stanislav-grin** [projectstorm/react-diagrams#692]
Hi all,

I have issue when trying to deserialize model which uses custom nodes.
What I do:
1. Create model using custom nodes, links etc. For example, my custom node expects some additional info which I pass to constructor during manual model creation.
2. Before component will unmount from DOM, call `engine.getModel().serialize()` and put it into Local Storage
3. When component did mount to DOM, take serialized model from storage and trying to initialize diagram using `model.deserializeModel(JSON.parse(serializedModel), engine)`.

What I have in result:
during deserialize process, custom nodes being initialized and nothing passed to constructor. Thus all logic which relies on additional info is broken and I can't restore diagram.

Here is an example of custom node model:
```js
import { DefaultNodeModel } from '@projectstorm/react-diagrams'

export class NodeModel extends DefaultNodeModel {
  constructor({ table, tablesMap, actions }) {
    // here I don't have expected options after deserialize
    super({
      name : table.name,
      color: 'rgb(0,192,255)',
      type : 'custom-node-model',
      id   : table.name
    })

    this.table = table
    this.actions = actions
    this.tablesMap = tablesMap
  }

  serialize() {
    return {
      ...super.serialize(),
      table    : this.table,
      tablesMap: this.tablesMap,
      actions  : this.actions,
    }
  }
}
```

When I create model manually, I pass options to constructor `const node = new NodeModel({ table, tablesMap, actions })` and then add node to model.

What should I do to correctly restore serialized model? Is there any other way to do it? Maybe I should to override deserialize methods somehow to respect my custom options?

Any help is much appreciated.

**Comment by renato-bohler** [comment]
> Maybe I should to override deserialize methods somehow to respect my custom options?

Yes, I believe that's the case. Try something like this:

```JavaScript=
deserialize(event, engine) {
  super.deserialize(event, engine);

  /**
   * The argument event.data should have same object returned on serialize,
   * so you just need to set the corresponding properties on your class
   */
  this.table = event.data.table;
  this.tablesMap = event.data.tablesMap;
  this.actions = event.data.actions;
}
```

And on your constructor, you would need to check if `table`, `tablesMap` and `actions` are defined. They should be defined when you call them directly, but shouldn't when deserializing.

**Comment by stanislav-grin** [comment]
Thanks @renato-bohler! I'll give it a try.

**Comment by farhanaaz1112** [comment]
@renato-bohler I have tried deserializing through the custom node model as given in the demo project.
 `deserialize(ob, engine) {
        super.deserialize(ob, engine);
        this.color = ob.color;
        this.name = ob.name;
        this.detail = ob.detail;
        this.id = ob.id;
    }`


But I'm getting the "TypeError: Cannot read property 'id' of undefined" when super.deserialize is called. I have checked the model object exists here and also has id property. Can you please help me with this? Have been stuck here since two days.
