### ISSUE TITLE
ml-matrix matrix.js Module parse failed

### ISSUE THREAD

**Issue by d2askif** [projectstorm/react-diagrams#706]
Error in ./~/ml-matrix/matrix.js
Module parse failed: ... /node_modules/ml-matrix/matrix.js Unexpected token (930:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (930:4)
 @ ./~/@projectstorm/geometry/dist/index.js 1:6006-6026

**Comment by dylanvorster** [comment]
We no longer use ml-matrix :D
