### ISSUE TITLE
Click to start linking put link first point in incorrect place if canvas zoom has been changed

### ISSUE THREAD

**Issue by stanislav-grin** [projectstorm/react-diagrams#709]
Clicking a source port after zooming-in/out canvas causes link to be placed in wrong place. I guess this is because 'transform' value changes and futher calculations of link start-position goes wrong.

### Expected Behavior
Zoom-in or zoom-out, then click to start linking - link shoud start from the clicked source port.

![image](https://user-images.githubusercontent.com/16938843/91701044-666cc600-eb7f-11ea-970c-bf1873d5d600.png)

### Current Behavior
Zoom-in or zoom-out, then click to start linking - link starts from different point depending on position of svg canvas.

![image](https://user-images.githubusercontent.com/16938843/91700960-4937f780-eb7f-11ea-843e-1e646061d7d7.png)

### Steps to Reproduce
You can reproduce it directly in example "Linking by clicking instead of dragging":
http://projectstorm.cloud/react-diagrams/?path=/story/advanced-techniques--linking-by-clicking-instead-of-dragging

1. Click zoom-in or zoom-out once or more
2. Click on source port of any node
3. See where link is started

**Comment by renato-bohler** [comment]
Interesting. This doesn't happen on the [Simple Usage](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--simple-example) example, for me. Maybe its something specific only to the example itself ([source for the example is here](https://github.com/projectstorm/react-diagrams/tree/master/packages/diagrams-demo-gallery/demos/demo-alternative-linking)).

**Comment by stanislav-grin** [comment]
Thanks for the answer. I've seen sources and think the problem is on [line 37](https://github.com/projectstorm/react-diagrams/blob/master/packages/diagrams-demo-gallery/demos/demo-alternative-linking/CreateLinkState.ts#L37). I tried to figure out how to do these calculations differently, but with no success.
Actually same issue on the Simple Usage also, but with the end-point of link while dragging it.

**Comment by stanislav-grin** [comment]
For everyone else who is interested in solution that respects canvas position and scale value, here is it:

```js
import { Action, InputType, State } from '@projectstorm/react-canvas-core'
import { PortModel } from '@projectstorm/react-diagrams-core'

function getScaleValue(element) {
  const style = window.getComputedStyle(element)
  const matrix = style.transform

  // No transform property. Simply return 1 value.
  if (matrix === 'none') {
    return {
      scale: 1
    }
  }

  const matrixValues = matrix.match(/matrix.*\((.+)\)/)[1].split(', ')

  return {
    scale: Number(matrixValues[0])
  }
}

/**
 * This state is controlling the creation of a link.
 */
export class CreateLinkState extends State {

  constructor() {
    super({ name: 'create-new-link' })

    this.registerAction(
      new Action({
        type: InputType.MOUSE_UP,
        fire: actionEvent => {
          const element = this.engine.getActionEventBus().getModelForEvent(actionEvent)

          if (element instanceof PortModel && !this.sourcePort) {
            this.sourcePort = element

            const link = this.sourcePort.createLinkModel()
            link.setSourcePort(this.sourcePort)
            link.getFirstPoint().setPosition(this.sourcePort.position.x, this.sourcePort.position.y)
            link.getLastPoint().setPosition(this.sourcePort.position.x + 20, this.sourcePort.position.y + 20)

            this.link = this.engine.getModel().addLink(link)
          } else if (element instanceof PortModel && this.sourcePort && element !== this.sourcePort) {
             if (this.sourcePort.canLinkToPort(element)) {
	      this.link.setTargetPort(element);
	      element.reportPosition();
	      this.clearState();
	      this.eject();
	    }
          }

          this.engine.repaintCanvas()
        }
      })
    )

    this.registerAction(
      new Action({
        type: InputType.MOUSE_MOVE,
        fire: actionEvent => {
          if (!this.link) {
            return
          }

          const { event } = actionEvent
          const { clientX, clientY } = event
          const svgCanvas = document.querySelector('svg') // here you should take svg canvas element using correct selector
          const clientRect = svgCanvas.getBoundingClientRect()
          const { scale } = getScaleValue(svgCanvas) // get scale value of svg

          this.link.getLastPoint().setPosition((clientX - clientRect.x) / scale, (clientY - clientRect.y) / scale)
          this.engine.repaintCanvas()
        }
      })
    )

    this.registerAction(
      new Action({
        type: InputType.KEY_UP,
        fire: actionEvent => {
          // on esc press remove any started link and pop back to default state
          if (actionEvent.event.keyCode === 27) {
            this.link.remove()
            this.clearState()
            this.eject()
            this.engine.repaintCanvas()
          }
        }
      })
    )
  }

  clearState() {
    this.link = undefined
    this.sourcePort = undefined
  }
}

```
