### ISSUE TITLE
Right-click on a link (DefaultLinkWidget) ignores `setLocked` read-only mode of the model and allows to remove the link.

### ISSUE THREAD

**Issue by sompylasar** [projectstorm/react-diagrams#71]
https://github.com/projectstorm/react-diagrams/blob/f36a8cf30444757d53ecb01e2c4c5cc05b02d70a/src/defaults/DefaultLinkWidget.ts#L85-L88

**Comment by dylanvorster** [comment]
Fixed in 2.5.2
