### ISSUE TITLE
Highlight ports on link hover

### ISSUE THREAD

**Issue by stanislav-grin** [projectstorm/react-diagrams#710]
Is there a way or any ideas on how to highlight ports which are connected by a link on link hover?
When there is a lot of nodes/ports & links between them (not like on the image - much more in complex schemas), it's hard to find which ports are related to the link. Would be very nice to have an ability somehow to highlight these ports.
![image](https://user-images.githubusercontent.com/16938843/91743667-d485ad00-ebc0-11ea-8c08-18e5b9d20e60.png)

**Comment by renato-bohler** [comment]
Hey.

The only way I can see to make something like this work is having custom link and node on your project. At a high level, you could do something like this:

1. add a custom property to their models (called `isHovered: boolean`, for example)
2. add a custom method aswell (called `setHovered`)
```JavaScript
// YourLinkModel
setHovered(isHovered: boolean) {
  this.isHovered = isHovered;
  if (this.getSourcePort()) this.getSourcePort().setHovered(isHovered);
  if (this.getTargetPort()) this.getTargetPort().setHovered(isHovered);
}

// YourPortModel
setHovered(isHovered: boolean) {
  this.isHovered = isHovered;
}
```

3. on `YourLinkWidget`, add `onMouseEnter` and `onMouseLeave` and call `setHovered` to `true` or `false` accordingly
4. on `YourLinkWidget` and `YourPortWidget`, you can now change how the widget should look when hovered.

**Comment by stanislav-grin** [comment]
Thank you @renato-bohler, that did a trick!

Best regards!

**Comment by yaliang381** [comment]
@stanislav-grin Hi, I am trying to highlight the ports when hovering on the link, did you able to handle it? When I call onMouseEnter, onMouseLeave and set the link's SourcePort and targetPort hovered:true. But how can we update the graph to show the highlighted ports?  Thank you in advance!

**Comment by renato-bohler** [comment]
Try calling `engine.repaintCanvas()` to see if this helps.

**Comment by lung-andreea** [comment]
@renato-bohler Hey, I know this is closed, but I am trying to solve a similar problem. In my case, I want to display the labels on hover of the link, so I am using the approach you described above with labels instead of ports (implementing `onMouseEnter` / `onMouseLeave`). However, the label widget's model doesn't seem to pick up on that change. I need to click the link myself and only then is it picked up and the label displays as expected, but I want this to be on hover, not on click. `engine.repaintCanvas()` does not help, unfortunately.

**Comment by lung-andreea** [comment]
Solved it. Seems like I needed to also `setSelected` on the link model to true (`onMouseEnter`) or false (`onMouseLeave`). I also used `repaintCanvas()` in both of the events, as otherwise the graph wouldn't get updated.
