### ISSUE TITLE
Detect and change port position (left/right) depending on related node position

### ISSUE THREAD

**Issue by stanislav-grin** [projectstorm/react-diagrams#711]
Hi guys,
does anybody have an idea how to implement following behavior?
A simple example is great for demonstration purposes, but when there are more nodes, and the links between them can be both in one direction and in the opposite direction, the links stop looking so nice when they come from the wrong side of their dependent node. Thus, sometimes it turns out that at the node A, which is to the left of node B, the link starts from the left side of the node, moving to the right, and can may come to the right side of the node B (and vice versa).
I wanted to somehow dynamically determine from which side to draw the port depending on the position of the connecting node, and when moving the nodes, it should automatically adjust. I don't know if I clearly explained what I meant, but I will try to show it in the picture. I would be grateful for any advice!

This how it looks when node 1 is on the left, and links go to node 2 and 3 just nice.

![image](https://user-images.githubusercontent.com/16938843/91744639-73f76f80-ebc2-11ea-89ad-4a9040296089.png)

And this what happenings when node 1 is on the right side, and links still go to node 2 and 3 starting from right side of node 1, and finishing in the left side of nodes 2 and 3. Instead, it would be nice so they are adjusted and started from the left side of node 1 and finished on the right side of nodes 2 and 3.

![image](https://user-images.githubusercontent.com/16938843/91745038-0ac42c00-ebc3-11ea-81af-4bb6375afca2.png)

**Comment by renato-bohler** [comment]
This is a difficult one. The problem is that the link pathing is not aware of the size of its parent node. You could mess with how the

**Comment by stanislav-grin** [comment]
Thank you @renato-bohler, you really helped me! I was able to implement this behavior successfully.

Best regards

**Comment by rogoja** [comment]
> Thank you @renato-bohler, you really helped me! I was able to implement this behavior successfully.
> 
> Here how it looks now (for big schemas it works perfectly also):
> 
> ![image](https://user-images.githubusercontent.com/16938843/91989915-bf805980-ed39-11ea-9601-9e3d299e3ce3.png)
> 
> Links changes their start & end positions while nodes are dragging.
> 
> Best regards

Hi, please tell me how you achieved this

**Comment by stanislav-grin** [comment]
Hi @rogoja,

I have registered a listener for the model `positionChanged` and there I've implemented such a behavior for each link:

```js
const optimizePortsPosition = link => {
  const sourcePort = link.getSourcePort()
  const targetPort = link.getTargetPort()
  const sourceNodePos = sourcePort.getNode().getBoundingBox()
  const targetNodePos = targetPort.getNode().getBoundingBox()
  const sourceMedian = sourceNodePos.getBottomMiddle().x
  const targetBottomLeftX = targetNodePos.getBottomLeft().x
  const targetBottomRightX = targetNodePos.getBottomRight().x
  const sourceBottomRightX = sourceNodePos.getBottomRight().x
  const sourceBottomLeftX = sourceNodePos.getBottomLeft().x

  if (targetBottomLeftX >= sourceMedian && targetBottomLeftX < sourceBottomRightX) {
    sourcePort.setAlignment(PortModelAlignment.RIGHT)
    targetPort.setAlignment(PortModelAlignment.RIGHT)
    sourcePort.setIn(false)
    targetPort.setIn(false)
  } else if (targetBottomRightX < sourceMedian && targetBottomRightX > sourceBottomLeftX) {
    sourcePort.setAlignment(PortModelAlignment.LEFT)
    targetPort.setAlignment(PortModelAlignment.LEFT)
    sourcePort.setIn(true)
    targetPort.setIn(true)
  } else if (targetBottomLeftX > sourceBottomRightX) {
    sourcePort.setAlignment(PortModelAlignment.RIGHT)
    targetPort.setAlignment(PortModelAlignment.LEFT)
    sourcePort.setIn(false)
    targetPort.setIn(true)
  } else if (targetBottomRightX < sourceBottomLeftX) {
    sourcePort.setAlignment(PortModelAlignment.LEFT)
    targetPort.setAlignment(PortModelAlignment.RIGHT)
    sourcePort.setIn(true)
    targetPort.setIn(false)
  }

  link.setHovered(false)
}
```

Hopefully this will give you an idea or direction to go. Probably not the most elegant solution, but I hope if you find a better solution you will share it as well =)
