### ISSUE TITLE
Prevent creation of extra Points on a Link

### ISSUE THREAD

**Issue by Tohid1999** [projectstorm/react-diagrams#714]
I need a listener to prevent creation of extra Points on a Link (all Points except the first and last one)
These Points
![points](https://user-images.githubusercontent.com/38454327/92444624-6b0d2c00-f1c8-11ea-90f2-b0980f2f3e9c.PNG)

i used the `linksUpdated` listener but it doesn't fire when i create Point on a Link

**Comment by renato-bohler** [comment]
If you want to customize how many points you can have in your link, you'll need to have a custom link set up in your project.

Once you have that, you can override `addPoint` method on `YourLinkModel` and add your logic. This is the default method inherited by `LinkModel`:

https://github.com/projectstorm/react-diagrams/blob/8ded9cd30e2d605c31f24270d38b1053dbda64dc/packages/react-diagrams-core/src/entities/link/LinkModel.ts#L289-L293

To prevent more than `MAX_POINTS` points on your link, you can override it with something like:

```JavaScript
addPoint(pointModel, index) {
  if (this.points.length >= MAX_POINTS) return;
  return super.addPoint(pointModel, index);
}
```

**Comment by JackieZhang-Coding** [comment]
> 

Hi, Boss.How can I  override addPoint method in the file https://github.com/osstotalsoft/atlas/blob/main/react-ui/src/features/designer/diagram/states/DragNewLinkState.js.
Now I only add `this.link.addPoint = () => {}` in line 40.

**Comment by JackieZhang-Coding** [comment]
> If you want to customize how many points you can have in your link, you'll need to have a custom link set up in your project.
> 
> Once you have that, you can override `addPoint` method on `YourLinkModel` and add your logic. This is the default method inherited by `LinkModel`:
> 
> https://github.com/projectstorm/react-diagrams/blob/8ded9cd30e2d605c31f24270d38b1053dbda64dc/packages/react-diagrams-core/src/entities/link/LinkModel.ts#L289-L293
> 
> To prevent more than `MAX_POINTS` points on your link, you can override it with something like:
> 
> ```js
> addPoint(pointModel, index) {
>   if (this.points.length >= MAX_POINTS) return;
>   return super.addPoint(pointModel, index);
> }
> ```
@renato-bohler 
Hi, Boss.How can I override addPoint method in the file https://github.com/osstotalsoft/atlas/blob/main/react-ui/src/features/designer/diagram/states/DragNewLinkState.js.
Now I only add this.link.addPoint = () => {} in line 40.
Thank you very much!

**Comment by renato-bohler** [comment]
> @renato-bohler Hi, Boss.How can I override addPoint method in the file https://github.com/osstotalsoft/atlas/blob/main/react-ui/src/features/designer/diagram/states/DragNewLinkState.js. Now I only add this.link.addPoint = () => {} in line 40. Thank you very much!

You can't. You have to override the `addPoint` method on your custom link's class, and this is why you'll need to have a custom link set up in your project.

For example, here's the `LinkModel`'s `addPoint` method on Logossim: https://github.com/renato-bohler/logossim/blob/12c22ac7ca18de1eb4d2725713fa1a47d95c7441/packages/%40logossim/core/Link/LinkModel.js#L193-L197 _(note that it does not prevent creation of extra points, though)_

The link is registered using the `LinkFactory` here: https://github.com/renato-bohler/logossim/blob/29aec84c17e8a7e500951e57c4bacb0d46775964/packages/%40logossim/core/Diagram/DiagramEngine.js#L63
