### ISSUE TITLE
model.addListener is not a function

### ISSUE THREAD

**Issue by lieyongchang** [projectstorm/react-diagrams#718]
storm react diagram version : 6.2.0
![error](https://user-images.githubusercontent.com/62921597/93067429-cac67400-f6ad-11ea-98d9-9a4d6450c317.PNG)

I have look through the [documentation](https://projectstorm.gitbook.io/react-diagrams/getting-started/using-the-library), I cant find anything about event listener. 

anyone could point me to the right syntax?

**Comment by renato-bohler** [comment]
On version 6, `addListener` has been renamed to `registerListener`, acording to this changelog:

https://github.com/projectstorm/react-diagrams/blob/dd5a0b7d8de5fa886b1e03b4f0d1fdce2c0cbd3d/packages/react-diagrams-core/CHANGELOG.md#L15

**Comment by lieyongchang** [comment]
Thanks! it worked
