### ISSUE TITLE
Zoom centering at mouse position with mouse wheel

### ISSUE THREAD

**Issue by sompylasar** [projectstorm/react-diagrams#72]
Right now the diagram ignores where you point the mouse pointer when spinning the wheel / swiping the touchpad, so the diagram is always scaling to the left top corner, which is counter-intuitive UX compared to, for example, Google Maps.

**Comment by JokerNN** [comment]
Hello!
I managed to implement this
Example:
![Demo](https://media.giphy.com/media/l378iUVQ8VyL1JTqg/giphy.gif)

Diff: https://github.com/projectstorm/react-diagrams/compare/master...JokerNN:master

onWheel handler became huge so maybe it's better to have it as class method
Also important to mention that swapping scale and transition made things mach more easier.

Hope this help @dylanvorster

**Comment by dylanvorster** [comment]
This is super legit, could you open up a PR!

**Comment by JokerNN** [comment]
Sure: https://github.com/projectstorm/react-diagrams/pull/87

**Comment by dylanvorster** [comment]
Let it be known that @JokerNN is awesome, this is now available in 3.1.0
