### ISSUE TITLE
Diamond node example

### ISSUE THREAD

**Issue by emrebil** [projectstorm/react-diagrams#728]
Hello, I'm trying to run that diamond node example but get the following error.

Code piece:
export declare namespace S {
	export const Port = styled.div`
		width: 16px;
		height: 16px;
		z-index: 10;
		background: rgba(0, 0, 0, 0.5);
		border-radius: 8px;
		cursor: pointer;

		&:hover {
			background: rgba(0, 0, 0, 1);
		}
	`;
}

Error:
A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.ts(1254)

I saw solutions to upgrade Typescript to version 2.(something) but I am using TS 4.0.3. Anyone knows the solution or runs the example?

**Comment by dylanvorster** [comment]
ive bumped the version of typescript in the project, still need to get to a release though
