### ISSUE TITLE
Can I use it in Vue.js ?

### ISSUE THREAD

**Issue by PePoDev** [projectstorm/react-diagrams#730]
Interested on this project. And I need to use in my my Vue project.

It's possible ?

**Comment by dylanvorster** [comment]
yes https://database.blog/how-to-vue-integrate-libraries/

**Comment by PePoDev** [comment]
@dylanvorster  Thanks for fast response

But can you show me a example of integration ?

I try with my self, And not sure what I'm doing.

**Comment by xanxuz** [comment]
@PePoDev did you successfully managed to integrate react-diagrams into Vue? if so, how did you do?

**Comment by PePoDev** [comment]
> @PePoDev did you successfully managed to integrate react-diagrams into Vue? if so, how did you do?

No, I'm not.

**Comment by PePoDev** [comment]
> @PePoDev did you successfully managed to integrate react-diagrams into Vue? if so, how did you do?

No 😥
