### ISSUE TITLE
Question: Is there any capability/functionality that tells if there is any change made in engine

### ISSUE THREAD

**Issue by agarwalishan** [projectstorm/react-diagrams#745]
Is there any functionality in engine that can tell if there is any change made to it. I want this so that I can implement AutoSave feature. Or if this is not even possible then also please tell me.
@renato-bohler  @dylanvorster

**Comment by renato-bohler** [comment]
There's no built in callback that is called whenever anything changes, as far as I know.

If you need autosave feature, what I would recommend is to autosave every X seconds. That's what I do in logossim ([here](https://github.com/renato-bohler/logossim/blob/40fda1385151ad966564471d87c0f9e8203f1226/packages/%40logossim/page/src/App.jsx#L70)).

**Comment by agarwalishan** [comment]
@renato-bohler Thanks for answering.
