### ISSUE TITLE
_this.port.createLinkModel is not a function

### ISSUE THREAD

**Issue by davidsu06** [projectstorm/react-diagrams#747]
Hi, I'm getting this error when I start dragging a link from a port, then I go outside of the CanvasWidget, I release the mouse click, and then I come back to the CanvasWidget and press click again.

How could I fix it?

Thanks for your help!!

![image](https://user-images.githubusercontent.com/57465385/96510328-f5629a00-1222-11eb-8a2c-3265fa3236de.png)

**Comment by berabulut** [comment]
Have you found a fix?

**Comment by davidsu06** [comment]
I decided to create a reference to the canvas wrapper and add an event listener for 'mouseleave' for this wrapper. Then, when the 'linksUpdated' listener of the model is called I keep the track of the current dragging link in a variable, so with this I can check in the mouse leave listener if that variable isn't null, which means I'm trying to drag a link out of the wrapper.

So, if I'm dragging the link, I call the '**engine.getStateMachine().popState()**' method which pops the drag link state, and then I repaint the canvas with '**engine.repaintCanvas()**'.

Tracking the link when linksUpdated listener is fired:
![image](https://user-images.githubusercontent.com/57465385/97223719-27817800-179e-11eb-9981-2c1c3b603cbf.png)

Deleting the last drag link state and repainting the canvas if 'currentDrag' isn't null:
![image](https://user-images.githubusercontent.com/57465385/97223653-0fa9f400-179e-11eb-88f3-d0f68ea4524a.png)

I'm not sure if this is the best way to solve it, for me it's working.

**Comment by berabulut** [comment]
Where do you call mouseLeaveListener?

**Comment by davidsu06** [comment]
I haven't used RightAnglePortModel so I can't tell you if it has to be applied in a different way.

I have a wrapper for the canvas:
![image](https://user-images.githubusercontent.com/57465385/97441075-4abf3b00-18f6-11eb-91d9-80d855408a37.png)


And I basically register and unregister the listener in the componentDidMount and componentWillUnmount method respectively:
![image](https://user-images.githubusercontent.com/57465385/97441009-37ac6b00-18f6-11eb-97d9-9f408b6f4430.png)

![image](https://user-images.githubusercontent.com/57465385/97441037-409d3c80-18f6-11eb-859c-57ab019defa9.png)

**Comment by KurtKellens** [comment]
I still have this issue, while creating a link between two components.

**How to reproduce:** 
- Start drawing a link
- Before releasing the left-mouse button on an input, press the second mouse button (while holding the left-mouse button)

I would expect the link should be removed. especially when the option allowLooseLinks is false.
`new DragNewLinkState({ allowLooseLinks: false }); `

![image](https://user-images.githubusercontent.com/13856225/132320714-bbec0890-b964-4405-8a36-132b6d5190a2.png)

Hopefully, this issue can be fixed 
Any help appreciated!

**Comment by davidsu06** [comment]
> I still have this issue, while creating a link between two components.
> 
> **How to reproduce:**
> 
> * Start drawing a link
> * Before releasing the left-mouse button on an input, press the second mouse button (while holding the left-mouse button)
> 
> I would expect the link should be removed. especially when the option allowLooseLinks is false.
> `new DragNewLinkState({ allowLooseLinks: false }); `
> 
> ![image](https://user-images.githubusercontent.com/13856225/132320714-bbec0890-b964-4405-8a36-132b6d5190a2.png)
> 
> Hopefully, this issue can be fixed
> Any help appreciated!

Just checked and happened for me too.

**Comment by davidsu06** [comment]
https://github.com/projectstorm/react-diagrams/issues/885
