### ISSUE TITLE
Unable to update custom node dimensions more then once.

### ISSUE THREAD

**Issue by smashboy** [projectstorm/react-diagrams#753]
I'm trying to build dynamic nodes, but I'm not able to call updateDimensions multiple times. Width and height won't update on second call.

![image](https://user-images.githubusercontent.com/30213662/96986562-817a0780-152a-11eb-8f6b-cfd1c1f6ec9a.png)

**Comment by renato-bohler** [comment]
Maybe you need to call `this.editorEngine.repaintCanvas()` inside the `setTimeout` callback?

**Comment by smashboy** [comment]
@renato-bohler I was trying that too, I can't undedstand how it works at all.
I wrote handler in my custom Widget that should repaint canvas each time I'm trying to update dimensions, but it still doesn't work properly. `TableNodeView` is a RFC and I'm calling `updateDimensions` in useEffect on first mount to adjust size to content that is inside node. It is updating dimensions only when I click on table.

![image](https://user-images.githubusercontent.com/30213662/97009658-08d87280-154d-11eb-9adb-defe4bd9af1d.png)

![image](https://user-images.githubusercontent.com/30213662/97010119-ac298780-154d-11eb-88ef-bcdc68a3b149.png)

**Comment by smashboy** [comment]
Also I was trying to pass `this.props.node.isSelected` and `this.props.node.updateDimensions` directly to my RFC component and when they are called I'm getting errors, because of this issue also have to wrap or call functions directly in `TableNodeWidget`

![image](https://user-images.githubusercontent.com/30213662/97010931-ba2bd800-154e-11eb-86aa-b175854c5b74.png)

**Comment by smashboy** [comment]
Also I don't think that calling `repaintCanvas()` is even doing something with dimensions. With or without calling `repaintCanvas()` it works the same.

**Comment by smashboy** [comment]
Looks like node is getting updated if I `console.log` dimensions after updating them in `my updateDimenions method`, but they are not getting passed to render function.

**Comment by ilyaborodin** [comment]
@smashboy did you find solution?

**Comment by smashboy** [comment]
@ilyaborodin Yes, it is a weird one. My NodeWidget component is wrapped in [mobx ](https://mobx.js.org/README.html) observer and because of that new props were not passed to NodeWidget. So I've had to make observable part as a separate component in order to get new props. Btw not only width was not getting updated, other props were not getting updated too.
![image](https://user-images.githubusercontent.com/30213662/98919110-1f804280-24d7-11eb-9f68-96b8b45bd032.png)
