### ISSUE TITLE
Connection path is dissapearing 

### ISSUE THREAD

**Issue by berabulut** [projectstorm/react-diagrams#754]
If I extend the page by dragging nodes right or left links path's are dissapearing. Do anyone know how to fix this?

![gif](https://user-images.githubusercontent.com/45367283/97106525-3fd89080-16d3-11eb-9176-fce48e7952f3.gif)
![download](https://user-images.githubusercontent.com/45367283/97106586-bf665f80-16d3-11eb-8b37-a691a3214f2d.png)

**Comment by sinanyaman95** [comment]
Take a look at issue #666 It may solve this problem

**Comment by berabulut** [comment]
Thanks it solved. Overflow should be visible.
![download](https://user-images.githubusercontent.com/45367283/97291510-16e30780-185b-11eb-8dd1-45c734640bb5.png)
