### ISSUE TITLE
Does this architecture support nested vs linked nodes? See example screenshot.

### ISSUE THREAD

**Issue by bebbi** [projectstorm/react-diagrams#758]
Component diagram example:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/2752391/97852178-b3435900-1cf6-11eb-86b6-d74d7d843ad0.png">

**Comment by thipokch** [comment]
I wonder if you could also have another network/diagram when you expand a node, like Houdini. That'll be awesome!

**Comment by thipokch** [comment]
@bebbi  — See  #329  👀 
Hope that'll help.

**Comment by bebbi** [comment]
I'm closing this in favor of these other tickets..
