### ISSUE TITLE
Connectors / Links with sharp edges and/or snap to grid

### ISSUE THREAD

**Issue by terndrup** [projectstorm/react-diagrams#76]
Hey guys, 

amazing project you have going here! I'm very interested in maybe contributing to some of the things and I was wondering if you had looked at all into "snap to grid" behaviour when placing Nodes as well as the ability for connectors to have sharp edges (90 degree angles) rather than the free flowing curved ones.

If the nodes were placed into a grid of variable size (i.e. the user can dynamically specify the size of the grid to make sure you can always place a node where you want) I think that would be a great addition.

In your demo 5 you already drew a grid background so this is maybe something that's already on your roadmap?

Anyway, just a suggestion!

**Comment by dylanvorster** [comment]
Implemented in the dev branch :)

**Comment by terndrup** [comment]
Node snap to grid looks great! Did you implement the sharp edge connectors too and am I missing it? Connectors still looking smooth on mine, do I enable it somehow?
