### ISSUE TITLE
Full javascript implementation of this project ?

### ISSUE THREAD

**Issue by andean00** [projectstorm/react-diagrams#760]
Hi !

This is such an excellent project !!  I need exactly this to model a graph that depics several nodes, edges and most importantly: nodes having multiple ports and labels. This package does it all, just amazing ! 

But I have been struggling trying to just use *only javascript*, because I did not use React in my project, nor typescript (blame it on Microsoft and webassembly, I know.. I know...).

I do get javascript interop though, which is working fine. I even did a babylonjs 3D project and it worked flawlessly.
Is there any repo that has an implementation of this particular project having: 
- all the required modules and dependencies in one or many javascript files
- Ideally, 1 bundle, minified version of it
- Ideally, an example of index.html that has all what it needs to make it exactly as the React counterpart 
 
Or step by step guidelines on how to convert this project in React to plain javascript and which js files use from the index page ?
Thanks in advance and regards ! 

Javier

**Comment by zHaytam** [comment]
Hello,

Not 100% sure this is what you need, but I made https://github.com/zHaytam/Blazor.Diagrams which is a Blazor library inspired by react-diagrams.

**Comment by dylanvorster** [comment]
@zHaytam nice work
