### ISSUE TITLE
Regarding performance

### ISSUE THREAD

**Issue by NeerajaGoli** [projectstorm/react-diagrams#761]
Hi everyone,
   I’m implementing react storm diagrams for representing ER diagrams.I have tried 10 tables with 10 rows each (attached image) and is rendering quite faster.But i have a requirement of  50 tables with around 1000 rows each.When i’m trying to do so, there is a delay in loading the diagram. Can anyone suggest me what i can do here to improve the performance?
![image](https://user-images.githubusercontent.com/61870685/98361412-7f976480-2051-11eb-92fb-48f4433a6e96.png)

**Comment by adaladam** [comment]
Hey, do you have a working sample on codesandbox? I could try playing around there and find something out there

**Comment by NeerajaGoli** [comment]
Hi, please find the below link
https://github.com/NeerajaGoli/Sample-ERD

**Comment by dylanvorster** [comment]
Yeah unfortunately, you are going to need to get creative to render 50 * 1000 styled divs and have the entire system be performant. Most browsers would actually struggle to render that many rows in a standard html table.
