### ISSUE TITLE
Latest package is still requiring ml-matrix but docs say it is no longer required

### ISSUE THREAD

**Issue by RossCoeH** [projectstorm/react-diagrams#763]
I am getting a compile error in latest version: "@projectstorm/react-diagrams": "^6.2.0", installed by  yarn today

Summary - it looks like your latest code is not using the latest of some subfiles. My version Point.ts is out of date to your master in my case.

your docs say ml_matrix has been removed from peer dependencies , but the code fails with message
./node_modules/@projectstorm/geometry/dist/es/Point.js
Module not found: Can't resolve 'ml-matrix' in 'C:\Users\Ross\Documents\Program_js\3vx_canvas_pstorm\node_modules\@projectstorm\geometry\dist\es'

first lines of code in this file are
```import { Matrix } from 'ml-matrix';

export class Point {
	x: number;
	y: number;

```
It suggests your latest build is not using the latest code for Point
**direct dependencies** as listed when using yarn upgrade are
success Saved 984 new dependencies.
info Direct dependencies
├─ @emotion/core@10.1.1
├─ @emotion/styled@10.0.27
├─ @projectstorm/react-diagrams@6.2.0
├─ @reduxjs/toolkit@1.4.0
├─ @testing-library/jest-dom@4.2.4
├─ @testing-library/react@9.5.0
├─ @testing-library/user-event@7.2.1
├─ add@2.0.6
├─ closest@0.0.1
├─ dagre@0.8.5
├─ ml-matrix@6.5.3
├─ pathfinding@0.4.18
├─ paths-js@0.4.11
├─ react-dom@17.0.1
├─ react-redux@7.2.2
├─ react-scripts@4.0.0
├─ react@17.0.1
├─ redux@4.0.5
├─ typescript@4.0.5
└─ yarn@1.22.10

**Comment by dylanvorster** [comment]
published
