### ISSUE TITLE
Error: @emotion/core package has been renamed to `@emotion/react`

### ISSUE THREAD

**Issue by alxAgu** [projectstorm/react-diagrams#766]
I'm getting this error after having followed the official docs steps. Any ideas?

Running on  "@projectstorm/react-diagrams": "^6.0.1-beta.7"

Thanks.

**Comment by alxAgu** [comment]
**UPDATE:** I just tried v6.2.0 with the same results

**Comment by patrickap-bkklinde** [comment]
Hi alxAgu,

I think [this](https://github.com/projectstorm/react-diagrams/issues/765#issuecomment-729490089) will help you.

**Comment by sagivo** [comment]
change your package.json file to have: 
`"@emotion/core": "^10.0.0"`

**Comment by dylanvorster** [comment]
i will be updating the library dependencies soon
