### ISSUE TITLE
how do I add extra field to DefaultNodeModel

### ISSUE THREAD

**Issue by bewithme** [projectstorm/react-diagrams#768]
how do I add extra field to DefaultNodeModel and make it can be serialized and deserialized ?

**Comment by sinanyaman95** [comment]
Option 1: You can override the DefaultNodeModel and add the fields you want to serialize() and deserialize() methods
Option 2: You can use the extras:{} field that is default on DefaultNodeModel and store your extra fields in that as a json objec

**Comment by rzfzr** [comment]
For whatever reason I'm having issues accessing the extra prop after deserialize, are there any examples?
I'm using the DefaultNodeModel, tried to add extras as is ports but no success

**Comment by sinanyaman95** [comment]
@rzfzr How are you trying to access the extras field?
