### ISSUE TITLE
Demo for end-users creating Nodes 

### ISSUE THREAD

**Issue by terndrup** [projectstorm/react-diagrams#77]
Hey,

so it seems to me that Demo 5 is already going in this direction (judging by the sidebar application layout) so correct me if I'm wrong but I think a Demo showing how an end-user can create nodes, place them and move them around as well as connect them would be really valuable for people who are looking into this lib. 

So basically, how about you/we enhance demo 5 to provide buttons in the sidebar that "spawn" a new instance of a node in the diagram.

I think this would provide a good example of something very real-world that people could use this library for rather than just the screenshots provided.

Any thoughts on this?

**Comment by dylanvorster** [comment]
this is sort of related to #66

**Comment by terndrup** [comment]
Yeah it is, though a bit more specific. I kinda think the demo I described is the one I'd personally like to see looking at a project like this so I thought I would suggest it.

**Comment by dylanvorster** [comment]
Fixed in dev branch
