### ISSUE TITLE
How to avoid or limit points with PortWidget

### ISSUE THREAD

**Issue by davidsu06** [projectstorm/react-diagrams#771]
Hi, I need to avoid or limit the creation of points when clicking a link, I'm currently using PortWidget.

Thanks for your help!

**Comment by berabulut** [comment]
This code does not allow any points in a link. It's inside my diagram constructor.
`this.diagramEngine.maxNumberPointsPerLink = 0;`

**Comment by davidsu06** [comment]
Thanks! It works perfectly. Do you maybe know how to show the link label when hovering the link?
