### ISSUE TITLE
Link label when hovering the link

### ISSUE THREAD

**Issue by davidsu06** [projectstorm/react-diagrams#772]
Hi, how could I archieve that the link label appears when hovering the link itself?

Thanks for your help!

**Comment by dylanvorster** [comment]
you would need to use a custom link with some custom hover logic. The links render 2 paths 1 which is displayed and another which is invisible but much thicker. We then use hover mouse hover states on the invisible thicker link to determine if the link is under the mouse cursor. Please take a look at the custom links.
