### ISSUE TITLE
Adding a link targeting new node

### ISSUE THREAD

**Issue by mrelier** [projectstorm/react-diagrams#78]
Hi ! First of all, thank you for this amazing project :)

I have an issue when I try to add a new node and a new link at the same time.

```
buttonAddRefus() {
    //Create a new node
    const newNode = new DefaultNodeModel("Node 3","rgb(192,255,0)");
    newNode.x = 500;
    newNode.y = 100;

    //Create new link
    let newLink = new LinkModel();

    //Set source on existing port : all is fine
    let portStep = _.find(this.props.engine.diagramModel.getNodes(), {"name":"Node 2"})
    newLink.setSourcePort(portStep.ports["out-1"]);

    //Set target on new node : will generate exception
    let newPort = newNode.addPort(new DefaultPortModel(true,"out-1", 'In'));
    newLink.setTargetPort(newPort);

    //Add node and link to model
    let model = this.props.engine.diagramModel;
    model.addNode(newNode);
    model.addLink(newLink);

    //refresh
    this.props.engine.repaintCanvas()
} 
```

this generates this error on console :  \node_modules\storm-react-diagrams\dist\main.js:1 Cannot find Node Port element with nodeID: [1985738d-ccad-41cb-ac80-293d56b79d57] and name: [out-1]

This is fine when the target node already exists. I also saw that a setTimeout before adding the link works, but... hum... :)

How can I fix it ? Thank you :)

**Comment by dylanvorster** [comment]
This might be fixed in caadbf4a9a0b03bde4ee32c5f1b9789ee7ed34bb

**Comment by dylanvorster** [comment]
Fixed in 2.5.2

**Comment by dylanvorster** [comment]
(I hope :P)

**Comment by PikkaPikkachu** [comment]
@dylanvorster I am facing the same problem! Any suggestions to get away with this issue?
@mrelier were you able to resolve the issue ?

**Comment by ShiroYacha** [comment]
I am dragging a new link to an empty spot and release to create a node then connect the link to a port. The link is dangling at (0,0) of the node. None of the tricks worked for me (e.g. setTimeout, refresh the canvas)... the only workaround i found is to `var newLink = link.clone()` and then `newLink.setTargetPort()` then remove the old link and add the new one... no `setTimeout` is required... hope this help you...

also might be a workaround for https://github.com/projectstorm/react-diagrams/issues/223

**Comment by PikkaPikkachu** [comment]
Thanks @ShiroYacha !
