### ISSUE TITLE
How to store custom data inside a Node ?

### ISSUE THREAD

**Issue by maxtsh** [projectstorm/react-diagrams#789]
hello everyone.
I have a problem with storing custom data inside a node JSON object which I want to use after serialization.

I added a Modal popup to my node and want to ask my user to give me some information about the flow so I added a state to my node-widget component but How can I pass that data to output serialized data?

**Comment by renato-bohler** [comment]
I've done this on my project: check [`PortModel`](https://github.com/renato-bohler/logossim/blob/bde09afec0c590c103f5a779d17a367002f1bc78/packages/@logossim/core/Port/PortModel.js#L13-L32).

Basically, `react-diagrams` will call `yourNodeInstance.serialize()` whenever it needs to serialize your node model, and it will call `yourNodeInstance.deserialize(event, engine)` whenever it needs to deserialize your node model. `event.data` is what you returned in `serialize`.

**Comment by maxtsh** [comment]
Oh, man thanks. @renato-bohler. 
I got the point. very cool.
