### ISSUE TITLE
Outdated main.js in npm release 2.5.3

### ISSUE THREAD

**Issue by chlumper** [projectstorm/react-diagrams#82]
Hi,

I think something went wrong during the release of the npm package version 2.5.3 (on npmjs.com) because the file 'dist/main.js' has a timestamp prior the actual release of the new version 2.5.3 at 4th of Sep 14:07 UTC / 16:07CEST.

![image](https://user-images.githubusercontent.com/25345228/30038671-8d3e6528-91c7-11e7-864d-961bbf5cecd3.png)

and it doesn't contain the following change in the generated output:
https://github.com/projectstorm/react-diagrams/blob/892706af3c6693d892977262e71cada85c5f3a5b/src/defaults/DefaultLinkWidget.tsx#L177

Looking forward to a fixed release.
Thanks!

**Comment by dylanvorster** [comment]
well spotted

**Comment by dylanvorster** [comment]
give me 10 mins

**Comment by dylanvorster** [comment]
npm is fighting me #garbage

**Comment by dylanvorster** [comment]
Fixed

**Comment by chlumper** [comment]
Thank you for your quick resolution of the issue! :-)
