### ISSUE TITLE
Feature Request: Limit the zoom levels

### ISSUE THREAD

**Issue by asnaseer-resilient** [projectstorm/react-diagrams#823]
It would be great if we had the capability to limit how far in/out a user could zoom. Our UI/UX designer has requested this on our app which makes use of this wonderful library. He wanted to limit zooms to between 1% and 400%.

**Comment by renato-bohler** [comment]
This is totally possible. I've done this in my project. You'll need to implement a custom `ZoomAction`.

On my implementation, the user can have the zoom only at a given set of levels.

You can check out the implementation here:
- asking `react-diagrams` not to add the default zoom action [on initialization](https://github.com/renato-bohler/logossim/blob/master/packages/%40logossim/core/Diagram/DiagramEngine.js#L39)
- registering the custom action [on initialization](https://github.com/renato-bohler/logossim/blob/master/packages/%40logossim/core/Diagram/DiagramEngine.js#L49-L60)
- custom [`ZoomAction`](https://github.com/renato-bohler/logossim/blob/master/packages/%40logossim/core/Diagram/actions/ZoomAction.js)

You can try it out here: https://renato-bohler.github.io/logossim/

**Comment by asnaseer-resilient** [comment]
@renato-bohler Really appreciate your insights - I managed to accomplish what my UI/UX designer wanted by following your guidance 👍
