### ISSUE TITLE
unable to start demo/help needed

### ISSUE THREAD

**Issue by dcbhz** [projectstorm/react-diagrams#83]
Hello,

i am trying to run the demo example and is not able to start them up.
(i am very new to this)

i have downloaded the zip file and unzipped it.

ran command npm install

Next, ran the command npm install webpack --save-dev , added the command "webpack" : "webpack" into the package.json's scripts section.

Next i tried to execute npm run webpack command and was met with the missing modules errors (dependencies). 
ran the commands below to add the missing dependencies

npm install @storybook/storybook-deployer

npm install closest

npm install lodash

npm install react

and ran npm run webpack again. 

right now i met with the errors saying : 
Property "props" missing
Property "state" missing etc

have attached a part of the error as image 
![9-11-2017 4-04-59 pm](https://user-images.githubusercontent.com/29365585/30264416-2cf26702-970b-11e7-981b-17708fe67099.png)

any help would be greatly appreciated, thank you.

**Comment by JokerNN** [comment]
Hello.
It feels like you've made lot of actions that are unnecessary (like installing react/closest/lodash).
so I would try from the very beginning. The point is that you don't need to install packages by name and you don't need to edit `package.json`

0. If you're haven't done this before - execute `npm install -g webpack`
1. Download zip(https://github.com/projectstorm/react-diagrams/archive/master.zip) OR do git clone https://github.com/projectstorm/react-diagrams.git
2. In terminal switch to `react-diagrams` directory
3. Execute `npm install`
4. Execute `npm run storybook` - this will run storybook with demos on `localhost:9001` if this port is free 
5. OPTIONAL: If you want to build the library you can execute `webpack`.

**Comment by dylanvorster** [comment]
@JokerNN You are awesome

**Comment by horcrux2301** [comment]
@JokerNN I did the above and get the following error after I execute `npm run storybook`

    ERROR in [at-loader] ./src/Common.ts:3:22
        TS2307: Cannot find module '_debugger'.

What should I do?
