### ISSUE TITLE
Selection box cause an error

### ISSUE THREAD

**Issue by rougsig** [projectstorm/react-diagrams#867]
Steps to reproduce:
1. Go to [demo](http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--canvas-drag)
2. Try to select with box (shift + mouse click)
3. See error in the console:
   Firefox: `Uncaught ReferenceError: TouchEvent is not defined`
   Chrome: `Uncaught TypeError: Cannot read properties of undefined (reading 'x')`
  
Expected result:
Selection box is visible and select nodes.

**Comment by rougsig** [comment]
Bug is [here](https://github.com/projectstorm/react-diagrams/blob/be422431d2dc44706ea95b8fd41bbbb18e39e370/packages/react-canvas-core/src/states/SelectionBoxState.ts#L31).

`event.event` (which is SyntheticEvent, not TouchEvent or MouseEvent) will give false in this should use `event.nativeEvent` will give valid type check.

Fix can be like this:
```typescript
const nativeEvent = event.event.nativeEvent
if (nativeEvent instanceof MouseEvent) {
  rel = this.engine.getRelativePoint(nativeEvent.clientX, nativeEvent.clientY);
} else if (nativeEvent instanceof TouchEvent) {
  const touch = nativeEvent.touches[0];
  rel = this.engine.getRelativePoint(touch.clientX, touch.clientY);
}
```

**Comment by vadimshvetsov** [comment]
It comes from #828 . I'm ready to PR something like this:
```ts
getBoxDimensions(event: AbstractDisplacementStateEvent): ClientRect {
		let rel: Point;
	        if (event.event instanceof TouchEvent) {
		  const touch = event.event.touches[0];
		  rel = this.engine.getRelativePoint(touch.clientX, touch.clientY);
		} else {
                  rel = this.engine.getRelativePoint(event.event.clientX, event.event.clientY)
                }
                ...
	}
```
So I'm suggesting to use second path by default instead of assuming that it is MouseEvent. Do you have better idea for fast fix @renato-bohler ?

**Comment by renato-bohler** [comment]
> It comes from #828 . I'm ready to PR something like this:
> 
> ```ts
> getBoxDimensions(event: AbstractDisplacementStateEvent): ClientRect {
> 		let rel: Point;
> 	        if (event.event.touches) {
> 		  const touch = event.event.touches[0];
> 		  rel = this.engine.getRelativePoint(touch.clientX, touch.clientY);
> 		} else {
>                   rel = this.engine.getRelativePoint(event.event.clientX, event.event.clientY)
>                 }
>                 ...
> 	}
> ```
> 
> So I'm suggesting to use second path by default instead of assuming that it is MouseEvent. Do you have better idea for fast fix @renato-bohler ?
> 
> It looks like `React.MouseEvent` is a TS type. I'm not sure that it can be used with `instanceof`. We can use `event.event.nativeEvent` and `instanceof` native event as second option.

Hmm, it's weird that this same code works on my project... but well, it seems to me that your change will address that issue.
