### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by LiamP95** [projectstorm/react-diagrams#888]
Hi there I wasn't able to find an email address for you so that's why I'm reaching out to you this way! My name is Liam Patrick and I work for an aerospace company called Cabin Management Solutions located in the Houston area. We like what react-diagrams has to offer and could be a good starting point for what we are trying to accomplish. If a paid consulting arrangement to get us started or perhaps even to enhance the software to meet our needs interests you, please reach out to our software department head, Clay Hopperdietzel at chopper@cmsaero.com.

**Comment by malavshah9** [comment]
@LiamP95  If you have found someone, than you can close this issue. As open issues count stopping someone from using this lib.

Thanks!!
