### ISSUE TITLE
LinK doesn't delete when it's not connected to a target port

### ISSUE THREAD

**Issue by DaSilvaRemi** [projectstorm/react-diagrams#895]
Hello @dylanvorster , and all devs

On LinkModel.js the link doesn't delete on the port if it is not connected to the target port. 

Original Code
`remove() {
        if (this.sourcePort) {
            this.sourcePort.removeLink(this);
        }
        if (this.targetPort) {
            this.targetPort.removeLink(this);
        }
        super.remove();
    }`

My solution
`remove() {
        if (this.sourcePort) {
            this.sourcePort.removeLink(this);
        }
        if (this.targetPort) {
            this.targetPort.removeLink(this);
        }
        super.remove();
     delete this;
    }`

**Comment by malavshah9** [comment]
@DaSilvaRemi  Yes, If that is working than you can close this issue. 

Thanks!!
