### ISSUE TITLE
Problem with build

### ISSUE THREAD

**Issue by gen4sp** [projectstorm/react-diagrams#9]
Its split out a lot of new files in /src
<img width="291" alt="screen shot 2017-03-04 at 20 06 06" src="https://cloud.githubusercontent.com/assets/4303628/23580620/30cf3868-0116-11e7-9024-14950de169ae.png">

**Comment by dylanvorster** [comment]
thats because JetBrains is compiling your software. I will add the compileOnSave: false to the tsconfig, then Jetbrains will do the right thing (I use netbeans so this is not a problem)

**Comment by gen4sp** [comment]
No, it is not JetBrains. 
seems, adding "outDir": "./dist" to tsconfig solve the issue

**Comment by dylanvorster** [comment]
have you tried with the latest commit? i added the "compileOnSave": false,

**Comment by dylanvorster** [comment]
I'm using webpack to build the library, so Jetbrains should not spit out any files at all. The IDE should respect that directive.

**Comment by gen4sp** [comment]
I build by run "tsc" in root folder. Files appear after that command.
I've added  "compileOnSave": false, by myself, it doesn't work out.

**Comment by dylanvorster** [comment]
yeah don't run tsc, rather run `webpack`

**Comment by dylanvorster** [comment]
the reason we use webpack compared to tsc, is that webpack will spit out a single UMD bundle, which tsc cannot do (tsc can only spit out multi file UMD files)

**Comment by gen4sp** [comment]
Ok, thanks! 
Please, update the doc then, the "build" part )

**Comment by dylanvorster** [comment]
will do
