### ISSUE TITLE
Upgrading from 2.5.5 to 3.1.2 deletes my links after onMouseUp

### ISSUE THREAD

**Issue by DrummerHead** [projectstorm/react-diagrams#91]
After moving a node, the `linksUpdated` event fires on the model and then the `links` array on model is empty. Does not happen on `2.5.5`

I'm willing to create a test repo but perhaps there's an easy fix or migration change I overlooked (from what I read, there are no API changes from 2.5.5 to 3.1.2, is that right?)

Cheers!

**Comment by dedelp** [comment]
Perhaps related to #123? @DrummerHead are you using `allowLooseLinks:false` by chance?
