### ISSUE TITLE
Can't build with nextJS "self is not defined"

### ISSUE THREAD

**Issue by burak94t** [projectstorm/react-diagrams#926]
İmporting with ssr, works fine in dev mode but fails when I try to build.

<img width="843" alt="Ekran Resmi 2022-04-07 13 04 40" src="https://user-images.githubusercontent.com/31184205/162175190-145d0e9d-b6e7-43a6-a3a1-faa22bf2625a.png">

**Comment by burak94t** [comment]
Fixed it, my diagram components was in pages folder and I moved them to components folder in the root directory, it's fixed the issue.

**Comment by BenAllenUK** [comment]
@burak94t I did this and it didnt change anything. Any other ideas?

**Comment by dincho-kostadinov** [comment]
@burak94t After I import the component dynamic and add ssr:false the diagram had a huge performance issue it works very slow.  Any idea?

**Comment by kenneho** [comment]
> @burak94t After I import the component dynamic and add ssr:false the diagram had a huge performance issue it works very slow. Any idea?

I'm not getting react-diagrams to work with NextJS. Could I ask you to share some code or other helpful information?
