### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by Nesterov-Konstantin** [projectstorm/react-diagrams#93]
Hello,
I've just discovered this library and noticed that I can't spawn new connection in this example in case if I'm using IE11: 
http://www.projectstorm.io/react-diagrams/?selectedKind=React%20Diagrams&selectedStory=Performance%20Test&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Do you officially support this browser? Would be great if yes :)

**Comment by alex-enchi** [comment]
I don't think project is officially supporting IE11...

But can you check please what is the document mode of the browser https://stackoverflow.com/a/27494616/8279092
it'll be quite helpful

Layer with links is svg layer and IE, as usual, has problems with it.

**Comment by Nesterov-Konstantin** [comment]
Hi, 
The browser is running in Standards mode for IE11, since the tags on your demo page are all in place.
I can interact with the chart, drag items, the only thing that seems broken is **port click** behavior - it just start the node drag, new link is not being created.
![image](https://user-images.githubusercontent.com/12291524/30938919-6c99b7f8-a3e4-11e7-9389-d106676e5507.png)

**Comment by serchduran** [comment]
@Nesterov-Konstantin  @dylanvorster  I'm not able to run the demo in IE11, neither the online demo or a local build, @Nesterov-Konstantin screenshot shows it works fine in IE11 but today it is not happening, can you verify it, please?

**Comment by serchduran** [comment]
@Nesterov-Konstantin  @dylanvorster  I'm not able to run the demo in IE11, neither the online demo or a local build, @Nesterov-Konstantin screenshot shows it works fine in IE11 but today it is not happening, can you verify it, please?
