### ISSUE TITLE
react 17   and 6.7.0  version install package.

### ISSUE THREAD

**Issue by prakashsvmx** [projectstorm/react-diagrams#937]
trying the following example (same code without the helpers import)  inside my project:
http://projectstorm.cloud/react-diagrams/?path=/story/simple-usage--links-with-labels

"react": "^17.0.2",
 "@projectstorm/react-diagrams": "^6.7.0",

`yarn add @projectstorm/react-diagrams`

the following error is thrown . 

`Module not found: Error: Can't resolve 'pathfinding' in '/home/test-rd-project/node_modules/@projectstorm/react-diagrams-routing/dist/engine'
`

**Comment by ycang89** [comment]
check this https://projectstorm.gitbook.io/react-diagrams/getting-started#install-the-peer-dependencies
