### ISSUE TITLE
[Bug] Cannot use vite to build react-canvas-core 

### ISSUE THREAD

**Issue by Ad-Bean** [projectstorm/react-diagrams#942]
I cant use `vite && vite preview` to build react-diagrams, the problem is the same as #842 while there's a small difference is that i got Uncaught TypeError.

![image](https://user-images.githubusercontent.com/54789193/167376645-8f775d8a-1ae7-4b86-9e55-b2e510086606.png)

![image](https://user-images.githubusercontent.com/54789193/167376985-7105154d-463a-4718-aa7a-bde51be6c097.png)

FYI, here is the preview page https://pr-22.d5mcpjv08hm7c.amplifyapp.com/

Please help with the issue, thanks a lot!

**Comment by Ad-Bean** [comment]
Solved by using webpack, which I dont think it's the right answer.

**Comment by ryzencool** [comment]
I also encountered this problem. is there any update on this?
